### ISSUE TITLE
How to install without CocoaPods

### ISSUE THREAD

**Issue by AAverin** [googlemaps/google-maps-ios-utils#100]
I'm not using CocoaPods in my project.
Would be great to have some guideline on how to install library as a git submodule

**Comment by domesticmouse** [comment]
I'm curious what you are using for dependency management, if not CocoaPods. If you are doing it by hand, then the majority of the setup required for including this as a git submodule is reconfiguring your Xcode project to include the files from this repository. Please re-open this bug if you need more assistance.

**Comment by mountainvat** [comment]
You can follow the similar instructions for Swift integtation: https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

**Comment by AAverin** [comment]
As a new iOS developer, it took me a few hours of messing with ObjectiveC headers to make it work in the end. The guide that @mountainvat  linked is very basic and doesn't mention the need to change almost all header files

**Comment by muhammadalkhalaf** [comment]
Is there any full guide for that ????
