### ISSUE TITLE
Move cluster item count number

### ISSUE THREAD

**Issue by blavejr** [googlemaps/google-maps-ios-utils#103]
Hi I have built a map with custom cluster icons but I can't seem to figure out how to move the text showing how many markers I have in the cluster.
I want to move this text from the centre to a label in the corner of my custom cluster icon.

**Comment by mountainvat** [comment]
You can use the `- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker` delegate in https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/View/GMUDefaultClusterRenderer.h to set a suitable anchor for the marker being render. 

For more information on customizing markers, see: https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md
