### ISSUE TITLE
GMUStaticCluster missing from library header

### ISSUE THREAD

**Issue by mandisaw** [googlemaps/google-maps-ios-utils#104]
Clustering library header file, GMUMarkerClustering.h, is missing a header entry for GMUStaticCluster.h, preventing callers from accessing the protocol. I was able to resolve it by adding an import for this file specifically.

Library Version: 2.0.0, via Cocoapods

**Comment by domesticmouse** [comment]
Could you please create a Pull Request against this project with your fix? Thanks!

**Comment by mandisaw** [comment]
Done! I submitted a CLA as well, let me know if there's a problem.

**Comment by domesticmouse** [comment]
Thanks for your PR!
