### ISSUE TITLE
Custom markers inside cluster, Swift

### ISSUE THREAD

**Issue by vanjau** [googlemaps/google-maps-ios-utils#105]
Is it possible to customize markers inside cluster, using Swift? Markers should be different depending of the category. I'm only manage to find Obj-C solutions, where I need to extend GMUDefaultClusterRenderer and override this method:
`- (GMSMarker *)markerWithPosition:(CLLocationCoordinate2D)position
                             from:(CLLocationCoordinate2D)from
                         userData:(id)userData
                      clusterIcon:(UIImage *)clusterIcon
                         animated:(BOOL)animated`

and also a "dirty" way where I directly in previous method change clusterIcon image, but there I can't use different categories.

Thanks for help in advance.

**Comment by mountainvat** [comment]
Follow the delegates as in this example? https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md

**Comment by vanjau** [comment]
@mountainvat 
I manage to find solution, but unfortunately it's not straightforward in Swift. I changed markerWithPosition method (put else statement) in GMUDefaultClusterRenderer.m class and only after that everything works like it should.

**Comment by mountainvat** [comment]
Are you able to export a PR so that I can take a look?

**Comment by vanjau** [comment]
@mountainvat 
Sorry, what do you mean by "PR"?

**Comment by domesticmouse** [comment]
PR is a shorthand for a Git Pull Request. We'd love to see what you did, thanks!

**Comment by vanjau** [comment]
Thanks for explanation.
Unfortunately, I can't export a PR to you, but I answered on SO, so maybe that can help you.

https://stackoverflow.com/a/44107523/6336996

**Comment by domesticmouse** [comment]
I'm closing this out for the time being, as I can't see a solid path forward. If you have suggestions for changes in the API surface to make this easier in Swift, please feel free to re-open this bug. Thanks!
