### ISSUE TITLE
GeoJSON importer Swift

### ISSUE THREAD

**Issue by mrigo** [googlemaps/google-maps-ios-utils#106]
Hello everyone!
is there any idea of creating the Swift version of the GeoJSON importer already created in ObjC ?

Thanks in advance!

**Comment by mountainvat** [comment]
There's a KML demo in the SwiftDemoApp that you can take a look. The GeoJSON should be similar.
https://github.com/googlemaps/google-maps-ios-utils/blob/master/samples/SwiftDemoApp/SwiftDemoApp/KMLViewController.swift
