### ISSUE TITLE
POI didn't contain,right?

### ISSUE THREAD

**Issue by YangLiMey** [googlemaps/google-maps-ios-utils#107]
I want to know where is the POI things existed,but didn't find in ios sdk

**Comment by domesticmouse** [comment]
This is the issue tracker for the Google Maps iOS Utils library. Please see the [Google Maps SDK for iOS Support](https://developers.google.com/maps/documentation/ios-sdk/support) for options for getting support for issues with Google Maps SDK for iOS. Thanks!
