### ISSUE TITLE
When Zoo in not show more markers

### ISSUE THREAD

**Issue by tiagoMaua** [googlemaps/google-maps-ios-utils#11]
When the app start, show total of 253 marks in one circle, apparently fine. After zoo in, not show separated markers.

 My _mapView is instantiated from a UIView.

In Xcode, not show issues or warnings. In console not show error.

 iOS 8
 Google Maps Version: Google Maps SDK for iOS version: 1.9.13516.0

I will do more tests, but if someone can help, I will be very grateful!

**Comment by tiagoMaua** [comment]
ok i find my mistake:

 I use the class Spot way wrong.
 Correct Implementation:


    for (GMSMarker* markers in markersCriados) {
        spot.location = markers.position; // pass position of marker to spot
        spot.marker = markers; // after pass position, pass the self marker to spot object.
        [clusterManager_ addItem:spot];
    }

**Comment by domesticmouse** [comment]
Tiago, I suspect you are using one of the forks, as this code base doesn't include clustering. Glad to hear you sorted out your problem!
