### ISSUE TITLE
Command failed due to signal: Abort trap: 6

### ISSUE THREAD

**Issue by mohammad19991** [googlemaps/google-maps-ios-utils#111]
Subclassing `GMUClusterItem` makes tests fail, check below:

`class PointOfInterest: NSObject, GMUClusterItem {
    var position: CLLocationCoordinate2D
    var name: String
    var price: String
    var currency: String

    init(position: CLLocationCoordinate2D, name: String, price: String, currency: String) {
        self.position = position
        self.name = name
        self.price = price
        self.currency = currency
    }
}`

removing `GMUClusterItem` makes my tests work again, I'm not sure why but this is how I got it working. I'm adding `Google-Maps-iOS-Utils` manually not using cocoapods.

**Comment by domesticmouse** [comment]
Can you please make a Github repository with a minimised reproduction case of this issue? The above description isn't enough for me to be able to see what the issue is.

Also, any particular reason for not using CocoaPods?

**Comment by domesticmouse** [comment]
Closing this out as stale for now. Please re-open if you upload a repro case. Thanks!
