### ISSUE TITLE
cluster images (Objective-C)

### ISSUE THREAD

**Issue by blavejr** [googlemaps/google-maps-ios-utils#113]
Hi I am trying to change the clusters marker images to images I am getting from a json.
1. I download a json containing the urls of some items I want to cluster.
2. I create POIItems from these urls and pass them to the cluster manager.

what I would like is to have the last item in the cluster be the cluster images.

I have tried to use - (id<GMUClusterIconGenerator>)icongeneratorWithBuckets
but this seems to generate the icons before the json is even downloaded and after is it is downloaded it doesn't even run this function anymore.

How can I generate these marker icons using information from the items in the clusters?

**Comment by mountainvat** [comment]
If I understand you correctly you are trying to use custom cluster images downloaded over the network? If it is the case, I'd suggest you perform the download of the images first. Once they've come back, start adding the items to the cluster manager. The defaultIconGenerator also has constructor to take custom images for each bucket.

**Comment by blavejr** [comment]
This is some what what I have done but what I need to get is the cluster. once I have the cluster I can than determine which item is last in that cluster. once this is determined I can use that image as the icon of the cluster. I hope this makes sense.

**Comment by blavejr** [comment]
This method
- (GMSMarker *)renderer:(id<GMUClusterRenderer>)renderer markerForObject:(id)object;

could be what I am looking for but I have no idea how to use the object given and what to return.

**Comment by blavejr** [comment]
I guess my real question is how do I use this
-- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker {
    if ([marker.userData isKindOfClass:[MarkerDetails class]])

to check for cluster markers instead of item markers?

**Comment by domesticmouse** [comment]
Closing this out as WAI. Please re-open if you need us to make any other changes. Thanks!
