### ISSUE TITLE
Drop support for iOS 7

### ISSUE THREAD

**Issue by jschmid** [googlemaps/google-maps-ios-utils#115]
Google Maps SDK for iOS finally [dropped support for iOS 7](https://developers.google.com/maps/documentation/ios-sdk/releases) with release 2.3.0.

There are a lot of discussions here (like #23) to be able to use CocoaPods with Swift.

Is this going to happen sometime soon? Thanks!

**Comment by domesticmouse** [comment]
Please raise a bug request for dropping the static binary on the [Google Maps SDK for iOS issue tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker).

With that out of the way, I should mention that using Google Maps SDK for iOS with Swift has been possible for some time, and is not dependent on dropping the static binary build.
