### ISSUE TITLE
Handling cluster events, how to get userData for the item?

### ISSUE THREAD

**Issue by AAverin** [googlemaps/google-maps-ios-utils#116]
I am handling tap events on clusters and cluster items, but I can't find a way to access underlying object for markers, because `GMUCluster` doesn't have userData objects.
Is it safe to cast `GMUCluster` to `GMSMarker`?
```
extension MapViewController : GMUClusterManagerDelegate {
    func clusterManager(_ clusterManager: GMUClusterManager, didTap cluster: GMUCluster) -> Bool {
        //cluster.items contains list of GMUClusterItem objects
        //how can I get underlying custom data for every item?
    }
    
    func clusterManager(_ clusterManager: GMUClusterManager, didTap clusterItem: GMUClusterItem) -> Bool {
        let item = clusterItem.userData as MyItem -> userData is not present

    }
}

```

**Comment by domesticmouse** [comment]
I am a tad confused. The core intent of the [GMUClusterAlgorithm](https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/Algo/GMUClusterAlgorithm.h) is to cluster [GMUClusterItem](https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/GMUClusterItem.h)s, a protocol that you can implement on your own data classes. You can render the generated clusters to a map using a [GMUClusterRenderer](https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/View/GMUClusterRenderer.h). You should not be attempting to cluster `GMSMarker` objects directly...

**Comment by AAverin** [comment]
I think I was able to cast GMUClusterItem directly to my custom item and it worked

**Comment by domesticmouse** [comment]
That would work, `GMUClusterItem` is a protocol after all. Glad it is working for you!
