### ISSUE TITLE
Xcode crashing after install GMS Utils

### ISSUE THREAD

**Issue by juniorgarcia** [googlemaps/google-maps-ios-utils#117]
Xcode version 8.3.1 (8E1000a) is instantly crashing when autocompleting `GMUClusterManagerDelegate` for some reason. I could create a child class of `GMUClusterItem` without crashing but could not go further with the documentation due this crash.

I tried to configure manually and with CocoaPods but both give me the same crash.

**Comment by domesticmouse** [comment]
I'd argue this is an issue with Xcode, and as such I'd suggest you upgrade to a more recent version of Xcode and/or raise issues with Apple. Thanks!
