### ISSUE TITLE
Want to display cluster selection

### ISSUE THREAD

**Issue by tapan-nathvani** [googlemaps/google-maps-ios-utils#118]
In the application, user can select multiple cluster so how can we change the image when select a cluster and when that cluster expand the same image will be set to expanded cluster also. And when user deselect the cluster we need to make it default.

How can we achieve this ?

In - (BOOL)clusterManager:(GMUClusterManager *)clusterManager didTapCluster:(id<GMUCluster>)cluster

We are not able to changed the icon of the selected cluster..is there any way to get GMSMarker in this position or is there any other delegate method from there we can do the same thing ?

**Comment by domesticmouse** [comment]
I'm going to have to ping @mountainvat for confirmation on this, but my reading of the code is that you can't do it directly with the code as it currently stands. 

The model is currently that you create a set of `GMUClusterItem`s that are clustered by `GMUClusterManager`, and the generated `GMUCluster`s will be rendered onto a `GMSMapView` using a `GMUClusterRenderer`.

My feeling is that you will need to add additional data members to `GMUCluster` that you can then change the behaviour of your `GMUClusterRenderer` implementation to achieve your desired output.

**Comment by mountainvat** [comment]
I think you can hook up to the `- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker` delegate on the default cluster renderer to build a mapping between a cluster and the marker. Then you can use that mapping to figure out the GMSMarker associated with your cluster in the `- (BOOL)clusterManager:(GMUClusterManager *)clusterManager didTapCluster:(id)cluster`.
An possible implementation of this approach is you can add a `marker` field to your GMUCluster implementation object to store the associated marker to avoid having to maintain a dictionary.

**Comment by tapan-nathvani** [comment]
@mountainvat I can add a marker but then suppose user does zoom in/out of the map then that cluster should be selected and its sub part (pins or cluster) also selected ? How can we achieve this ?

**Comment by tapan-nathvani** [comment]
Here i am doing something to changed the image...

- (BOOL)mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker {
  if ([_delegate respondsToSelector:@selector(clusterManager:didTapCluster:)] &&
      [marker.userData conformsToProtocol:@protocol(GMUCluster)]) {
    id<GMUCluster> cluster = marker.userData;
      
      if([marker.snippet isEqualToString:@"Selected"]) {
          [marker setIcon:[marker setIcon:<have to set default one>]];
          marker.snippet = @"";
      }
      else {
          [marker setIcon:[UIImage imageNamed:@"Background"]];
          marker.snippet = @"Selected";
      }
      
    if ([_delegate clusterManager:self didTapCluster:cluster]) {
      return YES;
    }
  }


If user going to select any cluster then we are changing the image but in ClusterManager there is no way to set it by default if user deselect that cluster.. And one more issue is that a cluster is selected and user zoom in/out the map at that time how can i show the selected cluster or items ? 

And - (void)addOrUpdateClusters:(NSArray<id<GMUCluster>> *)clusters animated:(BOOL)animated of GMUDefaultClusterRenderer class... this method called every time when user changed cluster visible area (Zoom in/out).. So please suggest me if i need to do something in this method as well.

**Comment by mountainvat** [comment]
I'd suggest you maintain the selected state independently from the library code and use them in the willRenderMarker delegate to decide which image to show. If a cluster becomes visible (because of panning) the willRenderMarker will be called so that you can update the marker before.

Please note that all the default clustering algorithms are stable meaning that for a given zoom level the clustering will always the same result. You can use this knowledge to compare if two clusters are value equal using their member items (even if they are not reference equal because of reclustering).

**Comment by tapan-nathvani** [comment]
but now the problem is willRenderMarker not calling

**Comment by mountainvat** [comment]
Can you please be more elaborate on what do you think should warrant a willRenderMarker event here?
