### ISSUE TITLE
Target has transitive dependencies when pod lib lint

### ISSUE THREAD

**Issue by ivampir** [googlemaps/google-maps-ios-utils#119]
I want use GoogleMaps in my pod.

My podspec:

Pod::Spec.new do |s|

  s.name = 'TCSExperiments'
  s.summary = 'Library for Experiments'
  s.authors = 'v.ampilogov'
  s.homepage = 'http://www.tinkoff.ru'
  s.version = '0.0.3'
  s.platform = :ios
  s.ios.deployment_target = '8.0'
  s.license = { :type => 'MIT' }
  s.source = { :git => 'https://stash.tcsbank.ru/scm/mi/experiments.git', :tag => s.version.to_s }
  s.source_files = '**/*.{h,m,swift}'
  s.requires_arc = true
  s.dependency 'GoogleMaps'
}

When i try lint my podspec I have an error:
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/cp/mr2xc0hn11lf5kf8bk34w9jh0000gp/T/CocoaPods/Lint/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /private/var/folders/cp/mr2xc0hn11lf5kf8bk34w9jh0000gp/T/CocoaPods/Lint/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and /private/var/folders/cp/mr2xc0hn11lf5kf8bk34w9jh0000gp/T/CocoaPods/Lint/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)) during validation.
[!] TCSExperiments did not pass validation, due to 1 error.

I thought after https://github.com/googlemaps/google-maps-ios-utils/issues/23 it have to work. But I still have the same problem.

**Comment by madBureaToT** [comment]
@ivampir : Have You Got solution for this. I am facing same issue. If You solved then please Provide the solution actually i have also tried #23 But still facing same issue.
