### ISSUE TITLE
Same Location Multiple Marker - Marker Animating Issues

### ISSUE THREAD

**Issue by kalidosstesark** [googlemaps/google-maps-ios-utils#121]
How to avoid marker animation ? 

Reference : 

![googlemapissues](https://user-images.githubusercontent.com/24803874/27468131-a10cb916-5805-11e7-9dbf-21433d879bfc.gif)

**Comment by sanghavan** [comment]
I got same issue

**Comment by Gajalakshmi94** [comment]
I too have same issue. I don't know how to fix that?
![skype_video](https://user-images.githubusercontent.com/36196391/45344043-56d5ca80-b5c0-11e8-8564-0c9c1524a1ae.gif)

**Comment by takeshi-akutsu** [comment]
How did you guys solve this problem??

**Comment by Thanhnc85** [comment]
// At zooms above this level, clusters will be expanded.
// This is to prevent cases where items are so close to each other than they are always grouped.
static const float kGMUMaxClusterZoom = 20;

I have changed kGMUMaxClusterZoom = 21. If markers have same location then they are always grouped. And I show makers in collectionView below bottom map when tap on cluster :)

**Comment by bhavikvwteam** [comment]
I am facing same issue while using GMSMarker with same location.

**Comment by Yagnik13** [comment]
The same issue facing when zooming out on the map.

**Comment by Yagnik13** [comment]
> The same issue facing when zooming out on the map.

I just add zIndex to GMSMarker and it stops flickering in the map so you guys also try that solution. for more info link provided below. 

https://stackoverflow.com/questions/16808563/set-a-marker-over-all-other-markers-in-google-maps-sdk-ios

**Comment by Gajalakshmi94** [comment]
Thanks

Regards,
Gajalakshmi D
