### ISSUE TITLE
Change pin image without affecting cluster

### ISSUE THREAD

**Issue by cancem123** [googlemaps/google-maps-ios-utils#122]
I am trying to change the orginal red pin to the different image icon but it is changing the clustering circle view while I just want the pin it self. Is there a way for it?

    private func generateClusterItems() {
                
        for item in storeList {
            
            let item = POIItem(position: CLLocationCoordinate2DMake(item.coordinates.latitude, item.coordinates.longitude), name: "")
            
            clusterManager.add(item)
        }
    }

    func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
        
        marker.icon = UIImage(named: "storePin")
    }

**Comment by pavlidismi** [comment]
did you find an answer to this?

**Comment by domesticmouse** [comment]
I believe what you will need to do is to add attributes to the items you cluster so the renderer code can choose the right marker for the unclustered items.

/cc @mountainvat

**Comment by lolkyfan** [comment]
Cluster manager creates markers for both, cluster items and clusters. It also sets the cluster items and clusters as marker's userData property.
In your renderer(_:, willRenderMarker:) you need to check if renderer is sending you marker for cluster item or cluster:
```
func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
    if marker.userData is POIItem {
        marker.icon = UIImage(named: "storePin")
    }
}
```

**Comment by PradnyaAC** [comment]
the render method is not being called anyone please let me know why this is happening
