### ISSUE TITLE
Change default text color for cluster

### ISSUE THREAD

**Issue by inna0** [googlemaps/google-maps-ios-utils#127]
Hello!

I'm using clustering for my app. I'm wondering, is there a way to change default white color for text in cluster? 
<img width="329" alt="screen shot 2017-07-26 at 17 59 49" src="https://user-images.githubusercontent.com/30472432/28628114-5eef6c54-722c-11e7-9a00-5edd9870e9f3.png">

**Comment by prashant-andani** [comment]
you can add any styling by adding third parameter like the below
`let clusterOptions = {
 styles: [
  {
            textColor: "green",
            textSize: 14,
            fontFamily: "Open Sans"
          }
        ]
};`

`let clusterer = new window.MarkerClusterer(
       mapInstance,
        markersArray,
       clusterOptions
);`

**Comment by rrizlan-zapmii** [comment]
@inna0 could you please tell me how you were able to change the cluster image like that in the image you have attached?

**Comment by rrizlan-zapmii** [comment]
> @inna0 could you please tell me how you were able to change the cluster image like that in the image you have attached?

Found the solution, Thanks,
Used the render method ( https://stackoverflow.com/questions/71129102/how-to-specify-custom-cluster-marker-for-a-google-map )

**Comment by cpro90** [comment]
@rrizlan-zapmii Unfortunatly your solution applies to Google Maps Javascript Clustering but not to the iOS SDK. Has anyone found a solution for google-maps-ios-utils so far?
