### ISSUE TITLE
Swift version of the GMUDefaultClusterRenderer protocol is missing a nullable annotation

### ISSUE THREAD

**Issue by jum** [googlemaps/google-maps-ios-utils#128]
The swift version of GMUDefaultClusterRenderer protocol is not allowing NULL results for creating markers:

`diff --git a/src/Clustering/View/GMUDefaultClusterRenderer.h b/src/Clustering/View/GMUDefaultClusterRenderer.h
index 3e6c299..37bf830 100644
--- a/src/Clustering/View/GMUDefaultClusterRenderer.h
+++ b/src/Clustering/View/GMUDefaultClusterRenderer.h
@@ -43,7 +43,7 @@ NS_ASSUME_NONNULL_BEGIN
  * Note that changing a marker's position is not recommended because it will
  * interfere with the marker animation.
  */
-- (GMSMarker *)renderer:(id<GMUClusterRenderer>)renderer markerForObject:(id)object;
+- (nullable GMSMarker *)renderer:(id<GMUClusterRenderer>)renderer markerForObject:(id)object;

 /**
  * Raised when a marker (for a cluster or an item) is about to be added to the map.
`

**Comment by mountainvat** [comment]
Can you please create a Pull Request for this? Thanks.

**Comment by jum** [comment]
Added pull request #129.
