### ISSUE TITLE
Issue While same coordinates

### ISSUE THREAD

**Issue by Arbaz7786** [googlemaps/google-maps-ios-utils#13]
I am using this class for showing pis as cluster but while i have same coordinate it shows pin number instead of pin.
I am not able to see to pin when at same coordinate.
So that I am not able to tap on the pin.
![mapissue](https://cloud.githubusercontent.com/assets/12610968/10334163/2dd8644a-6d06-11e5-90e4-14fbf5da1efb.png)

**Comment by domesticmouse** [comment]
I believe this bug report is destined for a fork that implements marker clustering. This repo only contains a QuadTree implementation.
