### ISSUE TITLE
Missing animation when kGMUMaxClusterZoom is reached

### ISSUE THREAD

**Issue by blurpy** [googlemaps/google-maps-ios-utils#131]
I was overriding shouldRenderAsCluster in GMUDefaultClusterRenderer to set my own max zoom level for clusters, when I noticed that the animation stopped working when reaching that level.

**To reproduce:**
Open GMUDefaultClusterRenderer and change kGMUMaxClusterZoom to something smaller, like 13. Start the DevApp and zoom in on the map by tapping until level 14 is reached.

**Expected outcome:**
Markers animating out of the clusters when reaching the max zoom level specified.

**Observed outcome:**
Markers "just appear" out of nowhere, and the clusters disappear.

**What to do?**
In my app there are 2 reasons to uncluster. Either because the cluster has too few items, or because it reaches the max cluster zoom level. Unclustering usually happens for each level, with an animation. Except when reaching the max level, which makes it look inconsistent.

I have tried to figure out a solution for this on iOS, and I think I need some input before spending any more time on it. I solved the exact same issue on Android (see https://github.com/googlemaps/android-maps-utils/issues/408), but doing the same on iOS fixes the animation, but introduces a new problem where the animation replays when zooming closer.

Any suggestions appreciated.

**Comment by blurpy** [comment]
OK, so I've been experimenting a bit more, and found a way of avoiding the repeated animation issue. I don't know for certain if this creates other issues yet, but it looks promising.

The code changes I made in the library can be seen here:
https://github.com/blurpy/google-maps-ios-utils/commit/a1129080a23138e1ba9f768e80768cdd31f70c16

This is a hack that is very similar to the one I did on Android, but instead of 1 added callback it's 2.
The first one allows the animation to function again, and the second one makes it possible to fix the repeated animation.

Using the code as is will make no difference, it will behave just like before. To get the fixes to work the methods needs to be overridden or replaced.

Replacing the default code with this works for me:

```
// Removed check of zoom level. This in combination with zoom level check in the next method
// enables animations on max zoom level.
- (BOOL)shouldRenderAsCluster:(id<GMUCluster>)cluster atZoom:(float)zoom {
  return cluster.count >= kGMUMinClusterSize;
}

// Using the same floor method as the cluster manager to avoid clusters showing because
// of rounding differences.
- (BOOL)shouldRenderAsClusterForAnimation:(id <GMUCluster>)cluster atZoom:(float)zoom {
  NSUInteger currentIntegralZoom = (NSUInteger) floorf(zoom + 0.5f);
  return cluster.count >= kGMUMinClusterSize && currentIntegralZoom < kGMUMaxClusterZoom;
}

// Disables any rendering of clusters when both previous and current zoom level is below
// max zoom level. Seems safe, as there should be no changes to clusters at this point anyway.
- (BOOL)shouldRenderClusters:(float)previousZoom currentZoom:(float)currentZoom {
  NSUInteger previousIntegralZoom = (NSUInteger) floorf(previousZoom + 0.5f);
  NSUInteger currentIntegralZoom = (NSUInteger) floorf(currentZoom + 0.5f);

  BOOL skipRender = previousIntegralZoom >= kGMUMaxClusterZoom &&
          currentIntegralZoom >= kGMUMaxClusterZoom &&
          previousIntegralZoom != currentIntegralZoom; // To allow manual recluster

  return !skipRender;
}
```

It's not a very elegant API, so I hope there is a better solution out there. I will be testing this further to see if I find any issues.

**Comment by domesticmouse** [comment]
Closing this out, as I believe @kirkhunter's PR fixes this issue. Please comment if this isn't the case. Thanks!
