### ISSUE TITLE
Is it possible to add new markers to the ClusterManager without closing the info windows?

### ISSUE THREAD

**Issue by jasperrietrae** [googlemaps/google-maps-ios-utils#133]
On Android it's possible to add new markers by `clusterManager.addItem` followed by `clusterManager.cluster`, but on iOS calling `cluster` closes the info popup window. What can I do about this?

**Comment by domesticmouse** [comment]
Hey @mountainvat, does the clusterer update mechanism keep markers that are already present on screen, or does it clear everything and add new markers?

**Comment by mountainvat** [comment]
As it is implemented it clears everything and add new markers. I do not see a workaround here unfortunately.

Is the info window of a item marker or a cluster marker?

**Comment by jasperrietrae** [comment]
@mountainvat I see, alright. It doesn't clear on Android when using the ClusterManager, which is quite bad in terms of consistency. Any way we could get that fixed?

It's an info window of an item marker.

**Comment by jasperrietrae** [comment]
We hack-fixed it by showing the previously displayed infowindow again after a refresh in didRender. We'd prefer a proper solution, but until then we can use this.

**Comment by khaptonstall** [comment]
Ran into this same issue. Thanks to @jasperrietrae for leading me towards the solution as I was also a little puzzled at this.

For those looking for a code sample, here is what I ended up doing (Note that the `currentSelectedMarker` is an optional `GMSMarker` I store on my class to keep track of which marker is selected. Also `MyCustomClusterItem` is my own class conforming to `GMUClusterItem` protocol. The item stores an `id` property I associate with the object that it is mapping.):

```swift
extension MyMapViewController: GMUClusterRendererDelegate {

    func renderer(_ renderer: GMUClusterRenderer, didRenderMarker marker: GMSMarker) {
        guard let myCustomerClusterItem = marker.userData as? MyCustomerClusterItem,
            let currentMarker = self.currentSelectedMarker?.userData as? MyCustomerClusterItem else {
            return
        }
        
        if myCustomerClusterItem.id == currentMarker.id {
            self.currentSelectedMarker = marker
            self.mapView.selectedMarker = marker
        }
    }
    
}
```

**Comment by domesticmouse** [comment]
Closing this out as not implementable.
