### ISSUE TITLE
GeoJSON, properties not reflected on marker userData

### ISSUE THREAD

**Issue by juvs** [googlemaps/google-maps-ios-utils#136]
When use Point on GeoJSON, this creates a GMSMarker, but when try to access properties from JSON is suppose to find it on userData attribute from marker, but is always nil. Well actually I found that from any Geometry type this attribute is not set, for now I only need for Point, so...

Checking the code for GMUGeometryRender.m I found there's no logic to assing this attribute, so I import the code to my project following this instructions: [https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md)

And did the following changes:

```objective-c
- (void)renderPoint:(GMUPoint *)point
          container:(id<GMUGeometryContainer>)container
              style:(GMUStyle *)style {
  CLLocationCoordinate2D coordinate = point.coordinate;
  GMSMarker *marker = [GMSMarker markerWithPosition:coordinate];
  if ([container isKindOfClass:[GMUPlacemark class]]) {
    GMUPlacemark *placemark = container;
    marker.title = style.title ?: placemark.title;
    marker.snippet = placemark.snippet;
  } else if ([container isKindOfClass:[GMUFeature class]]) { //Here check if is feature...
      GMUFeature *feature = container; //Convert to feature
      marker.userData = feature.properties; //Set userData with properties
  } else {
    marker.title = style.title;
  }
  if (style.anchor.x && style.anchor.y) {
    marker.groundAnchor = style.anchor;
  }
  if (style.heading) {
    marker.rotation = style.heading;
  }
  if (style.iconUrl) {
    __weak GMSMarker *weakMarker = marker;
    __weak GMSMapView *weakMap = _map;
    dispatch_async(_queue, ^{
      UIImage *image = [[self class] imageFromPath:style.iconUrl];
      image = [UIImage imageWithCGImage:image.CGImage
                                  scale:(image.scale * style.scale)
                            orientation:image.imageOrientation];
      dispatch_async(dispatch_get_main_queue(), ^{
        GMSMarker *strongMarker = weakMarker;
        GMSMapView *strongMap = weakMap;
        strongMarker.icon = image;
        if (!_isMapCleared) {
          strongMarker.map = strongMap;
        }
      });
    });
  } else {
    marker.map = _map;
  }
  [_mapOverlays addObject:marker];
}
```

This more and emergency change, I will work on an Pull request to fix for all types of geometries.

Hope this help.

Regards.

**Comment by paul-aigue** [comment]
Hello, is your pull request up for this feature ? :)

**Comment by juvs** [comment]
@paul-aigue No, there isn't a pull request, sorry, no time to do the entire changes for all types of geometry.

**Comment by domesticmouse** [comment]
Hey @juvs, I'd like to patch in your change, but I can't until after you have signed the CLA. Please create a pull request and our bot will ask you to fill in a form. Thanks!

**Comment by maxrandolph** [comment]
This would be great to implement :)

Thanks @juvs

**Comment by SzymonMatysik** [comment]
Hello, this problem is still a thing. While parsing GeoJSON into points, the properties of feature are gone, any further fix is planned regarding this issue?
