### ISSUE TITLE
GMUHeatmapTileLayer.h file not found

### ISSUE THREAD

**Issue by jigs777** [googlemaps/google-maps-ios-utils#137]
google-maps-ios-utils-master/samples/SwiftDemoApp/SwiftDemoApp/SwiftDemoApp-Bridging-Header.h:20:9: error: 'Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h' file not found
#import <Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h>

**Comment by juvs** [comment]
Did you follow this instructions?

https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

**Comment by mountainvat** [comment]
Heatmap has not been released publicly so you will also need to point to :git => "https://github.com/googlemaps/google-maps-ios-utils" in your Podfile.

**Comment by yozef** [comment]
+1
