### ISSUE TITLE
breaks google maps delegate method "idleatcameratposition" when map is panned

### ISSUE THREAD

**Issue by occurrentarts** [googlemaps/google-maps-ios-utils#14]
is still called when zoomed.

**Comment by occurrentarts** [comment]
the comment suggests that this decision was deliberate, but should still be highlighted to save others some time and frustration.

commenting out this line re-enabled the callback on pan in my case...

- (void)mapView:(GMSMapView *)mapView idleAtCameraPosition:(GMSCameraPosition *)cameraPosition {
    assert(mapView == _mapView);
    
    // Don't re-compute clusters if the map has just been panned/tilted/rotated.
    GMSCameraPosition *position = [mapView camera];
    
    /**
    if (previousCameraPosition != nil && previousCameraPosition.zoom == position.zoom) {
        return;
    }
    **/
     
    previousCameraPosition = [mapView camera];
    
    [self cluster];
    
    if ([self delegate] != nil
        && [self.delegate respondsToSelector:@selector(mapView:idleAtCameraPosition:)]) {
        [self.delegate mapView:mapView idleAtCameraPosition:cameraPosition];
    }
}

**Comment by domesticmouse** [comment]
This appears to be a bug report for a different google-maps-ios-utils project. This one doesn't contain any code to do with rendering, just a quad box implementation. Thanks!

**Comment by occurrentarts** [comment]
gotcha, sorry about that!
was meant for this fork: https://github.com/DDRBoxman/google-maps-ios-utils
