### ISSUE TITLE
GoogleMaps.h file not found from GMUClusterManger.h while archiving xcode project

### ISSUE THREAD

**Issue by xtnguyen** [googlemaps/google-maps-ios-utils#140]
Everything works perfectly on the simulator and when building on devices from xcode however this error keeps persisting when I archive my project. My bridging header path is indicated to the correct one, I don't see how i can resolve the issue
<img width="847" alt="screen shot 2017-09-06 at 21 31 30" src="https://user-images.githubusercontent.com/14217467/30130893-0e5eca6a-934b-11e7-97be-2dbcaa25c9c5.png">

**Comment by domesticmouse** [comment]
Can you please upload a minimal reproduction case to GitHub so that I can investigate?

**Comment by jimmy-devine** [comment]
I'm getting this same issue whenever I try to build my project with Google Maps. I used the instructions to build for Swift here: https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md.

I'll upload a reproduction case when I can.

**Comment by Daxito** [comment]
Hi,
I am also getting this error (File not found, see screenshot) when trying to Build, my pod file has pod 'GoogleMaps', not sure what is still missing, please advice.

![image](https://user-images.githubusercontent.com/16787057/36113519-b2293152-0ff2-11e8-816a-99453e39a8e1.png)

**Comment by domesticmouse** [comment]
I'd still appreciate a repro case. Thanks!

**Comment by mihirpmehta** [comment]
Getting exact same error after updating pods on exact same place

**Comment by xkawi** [comment]
was encountering this issue earlier on, would like to share how I found and fix the issue.

Chances are your GoogleMaps dependency is not installed properly during `pod install` process, which you can verify by tapping on the "Pods" project within  your Xcode, then expand "Pods > GoogleMaps", you should see a few folders and files under GoogleMaps. If you don't, that means it's not installed properly.

I then updated my Podfile to replace `pod 'GoogleMaps', '2.5.0'` to `pod 'GoogleMaps'` - remove the fixed version, which will install latest one, v2.7.0 as of this comment date. Then I did these:

1. `pod repo update`
2. `pod install`
3. clean the project and re-build again.

hope it helps.

**Comment by v-ken** [comment]
Started to get this error when updated from Xcode 10.1 to 10.2

**Comment by waydevin** [comment]
> Started to get this error when updated from Xcode 10.1 to 10.2

Same here. Had to rollback to the previous verison of GoogleMaps to keep it works.

**Comment by Manu-NGL** [comment]
I am getting the same error after I updated from XCode 10.1 to 10.2.....?....Any workarounds for this....?
<img width="1028" alt="Screenshot 2019-05-11 at 2 06 50 AM" src="https://user-images.githubusercontent.com/15637617/57555271-76143a00-7391-11e9-99ee-88160c826e4d.png">

**Comment by Manu-NGL** [comment]
> Started to get this error when updated from Xcode 10.1 to 10.2

are you able to solve this.....?

**Comment by mrsnax** [comment]
Same here GoogleMaps.h still not found :(

**Comment by arriolac** [comment]
Is this still an issue for folks?

**Comment by arriolac** [comment]
Closing this issue. Please reopen and specify repro steps if it still occurs.

**Comment by movezapp** [comment]
Im having this same issue

**Comment by arriolac** [comment]
@movezapp 

What package manager are you using? Can you provide steps to repro?
