### ISSUE TITLE
Heatmap from KML

### ISSUE THREAD

**Issue by yozef** [googlemaps/google-maps-ios-utils#141]
I've noticed Heatmap has been implemented as an initial commit.

Since most cases will utilize HeatMap from a KML (or JSON) file, the standard for KML files for Heat Maps look like this:
```<kml>
	<Document>
		<Style id="pointstyle_45_normal">
			<IconStyle>
				<color>ff0000ff</color>
				<scale>0.5</scale>
				<Icon>
					<href>http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png</href>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<scale>0</scale>
			</LabelStyle>
		</Style>
...
...
<Folder>
			<name>Some Folder Name</name>
			<Folder>
				<name>Site Verification_2015</name>
				<ScreenOverlay>
					<name>Legend</name>
					<Region>
						<LatLonAltBox>
							<north>51.3944154833333</north>
							<south>51.3825243333333</south>
							<east>-110.4203428</east>
							<west>-110.43127875</west>
						</LatLonAltBox>
						<Lod>
							<minLodPixels>256</minLodPixels>
							<maxLodPixels>-1</maxLodPixels>
						</Lod>
					</Region>
					<Icon>
						<href>images\EC Deep.jpg</href>
					</Icon>
					<overlayXY x="0.98" xunits="fraction" y="0.01" yunits="fraction"/>
					<screenXY x="0.98" xunits="fraction" y="0.01" yunits="fraction"/>
				</ScreenOverlay>
				<Folder>
					<name>points</name>
					<Region>
						<LatLonAltBox>
							<north>51.5844154833333</north>
							<south>51.53825243333333</south>
							<east>-110.4203428</east>
							<west>-110.43127875</west>
						</LatLonAltBox>
						<Lod>
							<minLodPixels>1</minLodPixels>
							<maxLodPixels>-1</maxLodPixels>
						</Lod>
					</Region>
					<Placemark>
						<name>0.826770</name>
						<styleUrl>#pointstyle_49</styleUrl>
						<ExtendedData>
							<SchemaData>
								<SimpleData name="SomeName">EH-31 2</SimpleData>
								<SimpleData name="Dataset">30/11/2016 9:32 AM</SimpleData>
								<SimpleData name="Product">NO Product</SimpleData>
								<SimpleData name="Obj. Id">1</SimpleData>
								<SimpleData name="Time">30/11/2015</SimpleData>
								<SimpleData name="Elevation(ft)">1875.328084</SimpleData>
								<SimpleData name="Distance(ft)">0.000000</SimpleData>
								<SimpleData name="Track(deg)">0.000000</SimpleData>
								<SimpleData name="Duration(s)">0.000000</SimpleData>
								<SimpleData name="Swth Wdth(ft)">60.000000</SimpleData>
								<SimpleData name="EC Shallow(dS/m)">0.661143</SimpleData>
								<SimpleData name="EC Deep(dS/m)">0.826770</SimpleData>
								<SimpleData name="Speed(mph)">0.000000</SimpleData>
								<SimpleData name="Prod(ac/h)">0.000000</SimpleData>
								<SimpleData name="Date">30/11/2016</SimpleData>
							</SchemaData>
						</ExtendedData>
						<Point>
							<coordinates>-110.6853428,51.5836416166667,0
</coordinates>
						</Point>
					</Placemark>
... list of Placemark(s)....
```

The **weight** of each point (from **coordinates**) in this case: EC Deep(dS/m), maybe this could be a custom variable to look for or simply reference the name.

At the moment using this KML with latest release v2.0.0 shows only the default red markers on the map, I guess adding the heatmap utils from the KML rendered is easier now?

I could also provide a sample KML file.

**Comment by domesticmouse** [comment]
Hey @Tilps is this a use case that your code should support, or is it something we need to add code for?

**Comment by domesticmouse** [comment]
I had a chat with the engineer that wrote this code, and there isn't an obvious hint to the KML parser that the KML it is ingesting is meant to be a heatmap instead of a cluster of points. Is there some form of standard around heatmaps as KML that we can leverage here?

**Comment by yozef** [comment]
Hi @domesticmouse The KML for Heatmaps is just a set of coordinates in the `<Placemark>` tag, with their appropriate weight. In this case the weight is in the `name` (this can also be found in simple data). Since the Weight of each point can be custom (depends on the device which generates the heatmap), it could be construed that parameter of the weight can be passed as an argument into the HeatMap KML parser, this is one possibility.

**Comment by yozef** [comment]
Update: I was able to extract the data points myself from the KML (basically parsed the XML/KML file), and converted them into an Array of points `{ longitude: x.xxxx, latitude: y.yyyy, intensity: 0.5 }`

However, if I paste this KML into Google Earth, and use google-maps-ios-utils, there is a sharp difference in rendering.

Take for example, the KML into Google Earth:
<img width="282" alt="gearth" src="https://user-images.githubusercontent.com/287256/30809433-b47f137c-a1cf-11e7-97fd-e483ad850237.png">

and the same KML, converted to an Array then rendered via google-maps-ios-utils:
I populated the array with each point (long/lat) with its own intensity of that point _(0.65, or 0.78, etc; instead of the default 1.0)_.
To get an idea of the Data (small sample):
```
[{"intensity":0.82677,"longitude":-105.4203428,"latitude":50.3836416166667},
{"intensity":0.799817,"longitude":-105.420342883333,"latitude":50.3836596666667},
{"intensity":0.758801,"longitude":-105.420343916667,"latitude":50.3837242333333},
{"intensity":0.771691,"longitude":-105.420348083333,"latitude":50.38382675},
{"intensity":0.786145,"longitude":-105.420349016667,"latitude":50.3839542333333},
{"intensity":0.780676,"longitude":-105.420350266667,"latitude":50.3841017666667},
{"intensity":0.801379,"longitude":-105.4203486,"latitude":50.3842652666667},
{"intensity":0.80802,"longitude":-105.420346633333,"latitude":50.3844434833333},
...
{"intensity":0.502547,"longitude":-105.4310083,"latitude":50.3940183}];
```

When creating the array of GMUWeightedLatLng:
```
for item in object {
          let latitude = item["latitude"]
          let longitude = item["longitude"]
          let intensity = item["intensity"]
          let coords = GMUWeightedLatLng(coordinate: CLLocationCoordinate2DMake(latitude as! CLLocationDegrees, longitude as! CLLocationDegrees), intensity: intensity as! NSNumber)
          list.append(coords)
}
```

At Zoom: 4
<img width="136" alt="2017-09-25 at 9 08 56 am" src="https://user-images.githubusercontent.com/287256/30809874-419ab77e-a1d1-11e7-87c0-23ef2969ab88.png">

Note: Zooming in further, shows no heatmap.

At Zoom 6:
<img width="102" alt="2017-09-25 at 9 09 07 am" src="https://user-images.githubusercontent.com/287256/30809881-47509bca-a1d1-11e7-9b2d-fc631d0106e2.png">

As you can see the rendering of the heatmap is very different. Especially since I am utilizing the **individual intensity of each point**.

**Comment by domesticmouse** [comment]
A heatmap and a collection of points with their individual intensity encoded in each point are two very different things. I suggest you read the code for the heatmap library to understand how it works.

**Comment by maxdea** [comment]
Yosef, it does not work...
Using "the standard for KML files for Heat Maps", at the bottom it says
"... list of Placemark(s)...."

which is the format to specify to insert a set of coordinates with the relative weights in order to be displayed in Google Earth? 
Thanks
