### ISSUE TITLE
Why in demo clustering so slow?

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [googlemaps/google-maps-ios-utils#144]
When I try zoom the map, something block UI, and I need wait when animation finished for next zoom.
Why it happens, anybody know ? How to fix it, and make clustering smooth ?

**Comment by domesticmouse** [comment]
Please upload your sample code to GitHub so I can have a look at what is going on. Thanks!

**Comment by SerhiiMatvieiev** [comment]
I used this demo project:
https://github.com/googlemaps/google-maps-ios-utils/tree/master/samples/SwiftDemoApp

**Comment by domesticmouse** [comment]
My suspicion is that the re-clustering, being expensive on the CPU, will not be kicked off until the map idle event fires.

You could, in theory, do some interesting work with changing the clustering algorithm to work in a more real time fashion, but given the high CPU impact that might have, it isn't something I want to take on at this point.

/cc @mountainvat thoughts?

**Comment by mountainvat** [comment]
What device did you run it on? And what is your use case? The sample code has 10k items and were running fine on our test devices.
