### ISSUE TITLE
Clusters count not decrements properly in Google Map iOS.

### ISSUE THREAD

**Issue by AllionKanishka** [googlemaps/google-maps-ios-utils#145]
I've been using this util classes and its all working fine. And my app is developed for both iOS and Android using Google Map SDk iOS/Android. My issue is goes as follows. 

When I zoom out (on zoom level = 5.0) it shows one 50+ clustering circle. When zoom in (on zoom level = 6.0) it suddenly drops to 3 x 10+ clustering circles where as in Android its 3x20+. Is there anyway to control this behaviour or is this normal? (i.e. In Android it perfectly decrements no of clusters count)

**Comment by mountainvat** [comment]
Can you try changing the bucket size?
https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/View/GMUDefaultClusterIconGenerator.m has default buck sizes: [@10, @50, @100, @200, @1000]

**Comment by AllionKanishka** [comment]
Thank you very much! Its working.
