### ISSUE TITLE
problem with animatesClusters 

### ISSUE THREAD

**Issue by theolof** [googlemaps/google-maps-ios-utils#150]
Using the default `GMUDefaultClusterRenderer` and the default `GMUDefaultClusterIconGenerator`.

When `animatesClusters` is true, not all markers are shown when zooming in. This happens around every other time.

Let's say I have 5 markers in a cluster and zoom in, sometimes only 3 markers are shown, sometimes 2, sometimes 5.

I check the delegate function `willRenderMarker` and all 5 are called here, but not all are shown for some reason.

If I set `animatesClusters` to false, it works as expected.

**Comment by mountainvat** [comment]
Do you have a repro case here?
Thanks.

**Comment by kirkhunter** [comment]
I've created a pull request to address this issue. If a cluster is not to be rendered as a cluster, is partially visible, and the cluster item representative is off the screen then it's possible that the cluster would fail to be rendered even though there may be visible cluster items. This is causing the markers to disappear especially as a result of incremental zoom changes.
