### ISSUE TITLE
Run SwiftDemo error, and How to render Heatmap to street router service from google API.

### ISSUE THREAD

**Issue by minhvn** [googlemaps/google-maps-ios-utils#151]
Hi Guys, 
I download and rebuild sample code of SwiftDemo but it show error :(, before I have pod install. When install, it missing folder heatmap, and I install manual follow instruction but it show 9error.
![screen shot 2017-10-11 at 9 32 47 pm](https://user-images.githubusercontent.com/187747/31447272-c91c0282-aecb-11e7-92c1-479d136831cb.png)

I want show many geo to street router "from location to destination" when enter or scroll to map region with heatmap, please help me.
Thank you very much.

**Comment by domesticmouse** [comment]
Which SwiftDemo are you using?
