### ISSUE TITLE
Heatmap is not updated when new data is set

### ISSUE THREAD

**Issue by ivorcho** [googlemaps/google-maps-ios-utils#154]
Hello,

Updating the dataset of coordinates is not updating the heatmap. All my test were on iOS simulator with os version 10.3. Here is the method I use for updating the dataset:
```
- (void)setCoordinates:(NSArray<AIRMapCoordinate *> *)coordinates
{
  _coordinates = coordinates;
  
  NSMutableArray<GMUWeightedLatLng *> * data = [NSMutableArray arrayWithCapacity:coordinates.count];
  for(int i = 0; i < coordinates.count; i++)
  {
    [data addObject:[[GMUWeightedLatLng alloc] initWithCoordinate:coordinates[i].coordinate intensity:1.0]];
  }
  
  if (_tileLayer == NULL) {
    _tileLayer = [[GMUHeatmapTileLayer alloc] init];
    _tileLayer.radius = _radius;
    _tileLayer.opacity = _opacity;
    _tileLayer.weightedData = data;
  } else {
    NSLog(@"Clearing tile data");
    _tileLayer.weightedData = data;
    [_tileLayer clearTileCache];
  }
}
```

I read in the documentation that I have to call `[_tileLayer clearTileCache];` but it seems not to work. First time the heatmap is loaded it is rendered, but when I want to update the data and it goes to the else statement, but heat map does not get rerendered . To make it work I had to clone your project and modify the `- (void)setWeightedData:(NSArray<GMUWeightedLatLng *> *)weightedData` method to call the `- (void)prepare` method in it:
```
- (void)setWeightedData:(NSArray<GMUWeightedLatLng *> *)weightedData {
  _weightedData = [weightedData copy];
  [self prepare];
  _dirty = YES;
}
```

Do you have any clue why is this happening? And is my solution good enough? Any help will be appreciated.

**Comment by domesticmouse** [comment]
Hey @Tilps, any thoughts?

**Comment by Tilps** [comment]
As per the documentation on GMUHeatmapTileLayer, properties are only captured when setting the map property.  You can recapture the settings without changing the map by doing _tileLayer.map = _tileLayer.map - this will correctly trigger [self prepare] internally.
