### ISSUE TITLE
After update GoogleMaps pod to 2.5.0  project doesn't build

### ISSUE THREAD

**Issue by Igorsnaki** [googlemaps/google-maps-ios-utils#156]
After update GoogleMaps pod to latest version ( 2.5.0), project doesn't built!
On version 2.3.1 and previous there was no such problem 

ld: framework not found GoogleMaps
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by domesticmouse** [comment]
The correct place to raise issues about Google Maps SDK for iOS is our [Issue Tracker](https://issuetracker.google.com/savedsearches/5050151). Please review the Issue Tracker for similar issues, and if you can't see one, please create a new bug describing the issue.

This issue tracker on GitHub is for the add on open source Utilities library codebase.
