### ISSUE TITLE
heat map battery issue

### ISSUE THREAD

**Issue by hc0405** [googlemaps/google-maps-ios-utils#157]
I put points (around 18 ~ 35 points) in the map every time in different zoom level .
After tested, battery quality from 100% to 82% (18%)  in  45 mins.
and Android vision about 6%.

**Comment by hc0405** [comment]
event only 1 point. battery drop quickly too.

**Comment by domesticmouse** [comment]
I'm curious what your testing protocol here is? Did you have the app open and the screen on for the whole 45 minutes? You might want to look at https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/MeasuringEnergyImpact.html

**Comment by hc0405** [comment]
the test method is :
1. No heat map only cluster and drag map 45 mins (about use 3%)
2. heat map (50 points ) and drag map 45 mins (about 18 %) (every idle will reset heat map data)
3. heat map (1 point)  and drag map 45 mins (about 18 %) (every idle will reset heat map data)

**Comment by domesticmouse** [comment]
Now that I understand your method I can see what is happening. I feel the way you are testing the library is not representative of usage, and if it is you would be best off pre-baking the clustering server side. This isn't a usage style we intend to optimise for.

**Comment by hc0405** [comment]
but, the android version does not have this problem.  and why?

**Comment by hc0405** [comment]
If you can see my first comment in this issue, battery usage was about 18% in 45 min for iOS devices. However battery usage was only 6% for android devices. Would you know the reason for the difference in two OS and how we can lower the battery usage to similar android performance?

**Comment by hc0405** [comment]
@tilps hi, would you be able to assist in this battery issue for iOS devices? Thanks.
