### ISSUE TITLE
Unable to find a specification for `Google-Maps-iOS-Utils`

### ISSUE THREAD

**Issue by vijaytholpadi** [googlemaps/google-maps-ios-utils#16]
Trying to perform `pod install` in the Obj-C sample project throws this error.

Temporarily solved it by changing the podfile to 

```
source 'https://github.com/CocoaPods/Specs.git'

target 'ObjCDemoApp' do
  pod 'GoogleMaps'
  #pod 'Google-Maps-iOS-Utils'
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils'
end
```

**Comment by mountainvat** [comment]
We could not reproduce the issue on our end. Is it still happening to you?

**Comment by vijaytholpadi** [comment]
Looks like the Cocoapod spec was not being resolved for `Google-Maps-iOS-Util`.

Yes, if I remove the hardcoded github URL then I am experiencing the same.

Also, `gem update` says everything is unto date.

<img width="569" alt="screen shot 2016-07-20 at 9 05 07 am" src="https://cloud.githubusercontent.com/assets/1171868/16974335/39e1feb0-4e59-11e6-9718-8e790d0d484e.png">

**Comment by mountainvat** [comment]
If you add the line below to the top of your Podfile, does it work?
source 'https://github.com/CocoaPods/Specs.git'

**Comment by vijaytholpadi** [comment]
Sorry looks like I had forgotten to mention to you the whole contents of the Podfile that I am seeing.

It looks as follows:

```
source 'https://github.com/CocoaPods/Specs.git'

target 'ObjCDemoApp' do
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
end
```

Btw  pod 'GoogleMaps' resolves correctly, its only  pod 'Google-Maps-iOS-Utils' that faces this issue.

P.S - I have updated my previous comment too.

**Comment by vijaytholpadi** [comment]
Hi @mountainvat ,

Removed and re-setup my cocoapods master repo.
Looks like it had not got updated and was causing this issue. I am guessing that a `pod repo update` also might have helped.

Thank you for your time. Please go ahead and close this issue.

**Comment by mountainvat** [comment]
That's great! Thanks for the update.

**Comment by LucaJeevanjee** [comment]
> Sorry looks like I had forgotten to mention to you the whole contents of the Podfile that I am seeing.
> 
> It looks as follows:
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> 
> target 'ObjCDemoApp' do
>   pod 'GoogleMaps'
>   pod 'Google-Maps-iOS-Utils'
> end
> ```
> 
> Btw pod 'GoogleMaps' resolves correctly, its only pod 'Google-Maps-iOS-Utils' that faces this issue.
> 
> P.S - I have updated my previous comment too.

This worked for me. Thank You. I've been trying to fix for ages
