### ISSUE TITLE
touch on map when use heat map

### ISSUE THREAD

**Issue by hc0405** [googlemaps/google-maps-ios-utils#160]
Hi, we are experiencing an event occurance issue on heatmap for iOS devices. Most of the time when we click on the heatmap, we do not receive the didTapAtCoordinate event on some heat point. We are unable to find a pattern to this issue as it occurs randomly
(I use cluster and heat map at the same time.)

**Comment by domesticmouse** [comment]
Can you please put together a minimal reproduction case and put it up on Github? I can't debug something without being able to reproduce it. Thanks!
