### ISSUE TITLE
Cluster position on the sea

### ISSUE THREAD

**Issue by jose46moreno** [googlemaps/google-maps-ios-utils#161]
How can I improve the position of the cluster?

As you can see, he puts them in the water.

I tried to create a subclass of GMUCluster to be able to set the property position, but I do not get it.

Please, help me.

![simulator screen shot - iphone x - 2017-12-23 at 20 35 23](https://user-images.githubusercontent.com/8105593/34322174-d42e428c-e820-11e7-9a32-15bceb2ecd61.png)

**Comment by domesticmouse** [comment]
The clustering algorithm is unaware of the geography that it is clustering over, and thus can't fix the problem you are seeking to work around.
