### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by miche-atucha** [googlemaps/google-maps-ios-utils#162]
on Clustering/View/GMUDefaultClusterIconGenerator.m:195:12: Incompatible pointer types initializing 'UIColor *' with an expression of type 'UIImage *'

**Comment by mountainvat** [comment]
Good catch. Would you mind creating a PR? on line 35, https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/View/GMUDefaultClusterIconGenerator.m#L35, the _backgroundColors should be of type NSArray<UIColor *> * rather than NSArray<UIImage *> *.

Thanks.

**Comment by mountainvat** [comment]
Fixed by PR https://github.com/googlemaps/google-maps-ios-utils/pull/163
