### ISSUE TITLE
Google Maps iOS SDK not able to show “LineString” from GeoJson File

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [googlemaps/google-maps-ios-utils#170]
I have installed Google Maps SDK for my Swift application. I run the sample code from google, its working fine. But, If I try to load my GeoJson file on maps, its rendering data, but, not showing anything.
if type is "Ploygon" its loading, but, if type is "LineString" its not showing anything.

 

> let camera = GMSCameraPosition.camera(withLatitude: -28, longitude: 137, zoom: 4)
> 
>     mapView = GMSMapView.map(withFrame: CGRect.zero, camera: camera)
>     self.view = mapView
> 
> 
>     let path = Bundle.main.path(forResource: "lines_String", ofType: "json")
>     let url = URL(fileURLWithPath: path!)
>     let geoJsonParser = GMUGeoJSONParser(url: url)
>     geoJsonParser.parse()
> 
>     let renderer = GMUGeometryRenderer(map: mapView, geometries: geoJsonParser.features)
> 
>     renderer.render()
> 
>     // Do any additional setup after loading the view, typically from a nib.
> }

Can anyone suggest me, how to show linestring in Google maps for iOS?

**Comment by domesticmouse** [comment]
Hi @AnilkumarRabhasa, 

Can you upload your sample app on GitHub somewhere so I can debug it?

brett

**Comment by AnilkumarRabhasa** [comment]
Hi, @domesticmouse thanks so much for your quick response, I have already raised query in stackover.  Please check,
https://stackoverflow.com/questions/49236503/google-maps-ios-sdk-not-able-to-show-linestring-from-geojson-file

**Comment by AnilkumarRabhasa** [comment]
Let me know if you need anymore, but, can you please give the solution for this since I was struck here from 2 days.

**Comment by AnilkumarRabhasa** [comment]
@domesticmouse Can I know why it is closed?

**Comment by domesticmouse** [comment]
I've closed this issue because you have (correctly) migrated this issue to StackOverflow.

**Comment by AnilkumarRabhasa** [comment]
Oh Okay, Thanks!
