### ISSUE TITLE
Is it possible to zoom marker 

### ISSUE THREAD

**Issue by gerryats** [googlemaps/google-maps-ios-utils#171]
Is their any way to zoom selected marker or Change marker color without changing icon?

**Comment by domesticmouse** [comment]
The Google Maps iOS SDK is an OpenGL context, and the icons are images uploaded into the OpenGL context. Changing the icons requires uploading new images to the OpenGL context.

**Comment by domesticmouse** [comment]
With that said, please raise a feature request on our [Issue Tracker](https://developers.google.com/maps/support/#issue_tracker)
