### ISSUE TITLE
Whether it can be displayed accurate number in cluster marker ？

### ISSUE THREAD

**Issue by wangliguang** [googlemaps/google-maps-ios-utils#173]
If it is have 225 markers.  the cluster marker show 225，rather than 200+

**Comment by wangliguang** [comment]
Whether can control when show normal marker by zoomLevel?

**Comment by wangliguang** [comment]
Whether can control when show normal marker by zoomLevel

**Comment by domesticmouse** [comment]
The logic that rounds counts down appears to be around https://github.com/googlemaps/google-maps-ios-utils/blob/97abfa78285562ae9522b91dd9d4b89edb717e15/src/Clustering/View/GMUDefaultClusterIconGenerator.m#L113

I'd suggest you clone the repo and adjust it to your needs.
