### ISSUE TITLE
I need to switch marker type between normal marker and cluster marker by zoomlevel。

### ISSUE THREAD

**Issue by wangliguang** [googlemaps/google-maps-ios-utils#174]
My project need to switch marker type between normal marker and cluster marker by zoomlevel.  
for Example,  I want to show normal marker when the zoomlevel of map > 15 and show show cluster marker when the zoomlevel of  map < 15.

What should I do. Thanks very much

**Comment by kirkhunter** [comment]
You can change kGMUMaxClusterZoom manually in GMUDefaultClusterRenderer.m
Or you can try subclassing GMUDefaultClusterRenderer and overriding shouldRenderAsCluster

**Comment by wangliguang** [comment]
thanks
