### ISSUE TITLE
didTapAtCoordinate not showing selected Marker

### ISSUE THREAD

**Issue by PatoSalazarNascent** [googlemaps/google-maps-ios-utils#176]
I want to change the icon of my selected marker to a deselected one if the user taps on the map.  I am usign the following delegate method :

```
 internal func mapView(_ mapView: GMSMapView, didTapAt coordinate: CLLocationCoordinate2D) {
        print("\(map.selectedMarker) ===> Selected Marker")
    }
```

however map.selectedMarker always comes nil. Even when the documentation says ```This is called before deselecting any currently selected marker (the implicit action for tapping on the map) ```
so I was expecting  to be able to see my selected marker.

This is the code I am running when a marker gets  tapped

```
    internal func mapView(_ mapView: GMSMapView, didTap marker: GMSMarker) -> Bool {
        
        if map.selectedMarker == marker {
            return true
        }
        
        if let selectedMarker = map.selectedMarker {
            deselectActiveMarker(currentSelectedMarker: selectedMarker)
        }
        
        selectMarker(marker: marker)
       
        return true
    }
 ```

the selectMarker(marker: marker) method is the following one:

```
private func selectMarker(marker: GMSMarker) {
        
        marker.iconView?.setAnchorPoint(anchorPoint: CGPoint(x: 0.5, y: 0))
        
        if let cluster = marker.userData as? GMUCluster {
            
            let count = "\(cluster.count)" as NSString
            
            if let icon = UIImage(named: "clusterSelected") {
                marker.iconView = UIImageView(image: createIconWithCount(drawText: count, inImage: icon, isSelected: true))
            }
        }
        else {
            if let icon = UIImage(named: "pinSelected") {
                marker.iconView = UIImageView(image: icon)
            }
        }
        
        marker.iconView?.transform = CGAffineTransform(scaleX: 0, y: 0)
        UIView.animate(withDuration: 0.3, delay: 0, usingSpringWithDamping: 0.8, initialSpringVelocity: 5, options: .curveEaseIn, animations: {
            marker.iconView?.transform = CGAffineTransform(scaleX: 1, y: 1)
        }, completion: {
            [weak self = self]
            _ in
            
            guard let instance = self else { return }
            
            instance.map.selectedMarker = marker
        })
    }
 ```

Hopefully you can help me. Thanks

**Comment by kirkhunter** [comment]
What worked for me was subclassing GMUClusterItem (or in your case GMUCluster), giving it custom properties like whether it's selected, and icon, and I kept a reference to the selectedMarker in my MapViewController, which I made nil in mapView(_:didTapAt:).

**Comment by PatoSalazarNascent** [comment]
I do understand the idea, however, I am using the Clustering library and I don't know how to feed a custom subclass of GMUCluster to the clustering manager...

**Comment by PatoSalazarNascent** [comment]
I'll close the issue as I found a work around. Thanks anyways @kirkhunter

**Comment by Albinzr** [comment]
@PatoSalazarNascent What work around did you find?

**Comment by harjeetk** [comment]
@PatoSalazarNascent What was the workaround you found?
