### ISSUE TITLE
CoreData: annotation:  Failed to load optimized model at path

### ISSUE THREAD

**Issue by FizzXiaoyu** [googlemaps/google-maps-ios-utils#177]
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/58C9F157-EE69-4CDD-AE3A-7A7C415D581E/zzp.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'

**Comment by domesticmouse** [comment]
I think you will find the right place to log this issue is actually through the Google Maps SDK for iOS [Issue Tracker](https://developers.google.com/maps/support/#issue_tracker).

**Comment by FizzXiaoyu** [comment]
So that's the problem with your demo.

**Comment by domesticmouse** [comment]
This issue is a problem with the Google Maps SDK for iOS, not the utils library.
