### ISSUE TITLE
CoreData: annotation: Failed to load optimized model at path

### ISSUE THREAD

**Issue by FizzXiaoyu** [googlemaps/google-maps-ios-utils#178]
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/5A7FB194-7AD8-49F2-BA55-461BEED745A1/征仔拍.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'

**Comment by nastassia-kavaliova** [comment]
Have the same issue.
The log is 
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/.../My.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'

**Comment by domesticmouse** [comment]
This is an issue with Google Maps SDK for iOS, not this utility library. Please file an issue on the [Google Maps SDK for iOS tracker](https://issuetracker.google.com/issues/new?component=188833&template=789005).
