### ISSUE TITLE
No clustering for less than 4 markers

### ISSUE THREAD

**Issue by pabloelizalde** [googlemaps/google-maps-ios-utils#18]
I experienced that I need to have at least 4 markers for the clustering to be performed. When I have 3 markers, there is no clustering, no matter in which zoom level I am.

![screenshot 2016-07-20 13 14 07](https://cloud.githubusercontent.com/assets/3242710/16984716/17b70a10-4e7c-11e6-9cf6-030a2eb86b0a.png)

Is there something I am missing? Thanks

**Comment by mountainvat** [comment]
That's the default behavior of the GMUDefaultClusterRenderer class

- (BOOL)shouldRenderAsCluster:(id<GMUCluster>)cluster atZoom:(float)zoom {
  return cluster.count >= kGMUMinClusterSize && zoom <= kGMUMaxClusterZoom;
}
kGMUMinClusterSize is 4.

What you can do is create a custom renderer which derives from GMUDefaultClusterRenderer and override that method to your own liking (for example removing the cluster.count >= kGMUMinClusterSize clause).

**Comment by pabloelizalde** [comment]
Great! Thanks for the quick response 👍

**Comment by rajatvns** [comment]
i want to know how i create custom marker in a cluster plz help me

**Comment by mountainvat** [comment]
@rajatvns Can you please open a new ticket and describe in detail what you are trying to achieve?

Some pointers without know exactly what you need:
If you wanted to customize the individual cluster item marker, please see this https://github.com/googlemaps/google-maps-ios-utils/issues/21

If you wanted to customize the cluster marker, you can use the default GMUDefaultClusterIconGenerator or extends the GMUDefaultClusterRenderer.

**Comment by jose46moreno** [comment]
What is the value of  kGMUMaxClusterZoom?
