### ISSUE TITLE
Crash after open/close map multiple times

### ISSUE THREAD

**Issue by spensko** [googlemaps/google-maps-ios-utils#181]
>  An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
> Key path: camera
> Observed object: <GMSMapView: 0x1329e7a00; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x1c1c4b7f0>; layer = <GMSMapLayer: 0x1c5449060>>
> Change: {
>     kind = 1;
>     new = "GMSCameraPosition 0x1c1c45ac0: target:(51.179, -1.826) bearing:0.000 zoomLevel:4.000 viewingAngle:0.000";
> }
> Context: 0x0'

I have UIVIew subclass, with GMSMapView and GMUClusterManager inside

```
 var mapView: GMSMapView!
   var clusterManager: GMUClusterManager!
```

```
    override init(frame: CGRect) {
        super.init(frame: frame)
        mapView = GMSMapView(frame: frame)
        addSubview(mapView)
      
            let iconGenerator = GMUDefaultClusterIconGenerator()
            let algorithm = GMUNonHierarchicalDistanceBasedAlgorithm()
            let renderer = GMUDefaultClusterRenderer(mapView: mapView,
                                                     clusterIconGenerator: iconGenerator)
            clusterManager = GMUClusterManager(map: mapView,
                                               algorithm: algorithm,
                                               renderer: renderer)
            renderer.delegate = self
            clusterManager.setDelegate(self, mapDelegate: self)
    }
```

after open/close controller with map several times (~3-10 times) i get this crash

**Comment by michael-mckenna** [comment]
We are having the same problem. Did you ever find a solution?

**Comment by spensko** [comment]
No, but _mapView is always null in
`- (void)dealloc {
  [_mapView removeObserver:self forKeyPath:kGMUCameraKeyPath];
}`

so observer may exist while GMUClusterManager already deallocated

**Comment by michael-mckenna** [comment]
@spensko Great, thanks!

**Comment by CristianoCastro** [comment]
I was having the same problem. ClusterManager has weak reference to mapView, so when deallocating, if the mapView is null already, it won't remove itself from observer, leading to crashes

**Comment by Tequilag** [comment]
Why issue is closed, if the problem still exist?

**Comment by crazyjooe** [comment]
Having the same issue, nilling cluster won't help!

**Comment by aliakhtar49** [comment]
Can someone look into this , it's related to this issue

https://stackoverflow.com/questions/54129679/random-kvo-block-crashes-when-allocating-mapview-happens-only-when-open-close-s

**Comment by iKorich** [comment]
that helped for me - Issue #215
