### ISSUE TITLE
No custom images for marker items if GMUDefaultClusterRenderer delegate is class instance

### ISSUE THREAD

**Issue by fongd** [googlemaps/google-maps-ios-utils#188]
Not sure how to phrase this issue, but hopefully this makes sense. I'm using Swift 4.1, Xcode 9.3.1, Google Maps installed as a CocoaPod, google-maps-ios-utils installed following the instructions here: https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

I'm trying to customize the marker items by creating a custom cluster renderer using something like this:

```
class CustomClusterRenderer: NSObject, GMUClusterRendererDelegate {
    func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
        if let userData = marker.userData {
            print(userData)
        }
        guard let _ = marker.userData as? POIItem else { return }

        if let image = UIImage(named: "marker") {
            marker.iconView = UIImageView(image: image, highlightedImage: nil)
        }
    }
}
```

In my view controller's viewDidLoad, I create an instance of this class and assign it as the `GMUDefaultClusterRenderer` delegate:

```
let renderer = GMUDefaultClusterRenderer(mapView: map, clusterIconGenerator: iconGenerator)
let customClusterRenderer = CustomClusterRenderer()
renderer.delegate = customClusterRenderer
```

When I run this, I still get the default marker images instead of my custom marker pin.

However, if I instead modify my view controller to extend `GMUClusterRendererDelegate` and implement `renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker)` in there like so:

```
class ViewController: UIViewController, GMUClusterRendererDelegate {
    override func viewDidLoad() {
        super.viewDidLoad()
        …
        let renderer = GMUDefaultClusterRenderer(mapView: map, clusterIconGenerator: iconGenerator)
        renderer.delegate = self
    }

    func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
        if let userData = marker.userData {
            print(userData)
        }
        guard let _ = marker.userData as? POIItem else { return }
        
        if let image = UIImage(named: "marker") {
            marker.iconView = UIImageView(image: image, highlightedImage: nil)
        }
    }
}
```

Then the marker icons are properly customized as I want them.

Is there something I'm doing wrong here or do I need to implement some additional steps when I try to use an instance as GMUDefaultClusterRenderer's delegate? I originally wanted to create a separate delegate class to create a cleaner separation but I'm willing to just extend ViewController if it's easier.

**Comment by kirkhunter** [comment]
Your second implementation is correct. You probably already know this but, generally, the delegate defines a protocol, and some other class implements it. So if you create a custom renderer delegate, you may define a method signature, and your map view controller will extend your custom renderer delegate and implement the method it defined.

**Comment by breakline87** [comment]
Can you guys please update the documentation and provide samples on how to set custom images for both the cluster images and markers? At the moment it's rather lacking
