### ISSUE TITLE
MyLocation Marker is always behind custom markers

### ISSUE THREAD

**Issue by PatoSalazarNascent** [googlemaps/google-maps-ios-utils#189]
Hi.

When is set the map to display MyLocation `map.isMyLocationEnabled = true`, the blue dot marker always seems to have a lesset zIndex that any other marker. Is there a way to change the ZIndex of the myLocation marker so it always displays above other markers (including cluster ones)

Thanks

**Comment by domesticmouse** [comment]
This looks like a question for Google Maps SDK for iOS. Please raise the question on this [bug tracker instead](https://developers.google.com/maps/documentation/ios-sdk/support).
