### ISSUE TITLE
"Module 'GoogleMapsBase' not found" Error with Google Maps SDK for iOS V2.0.0

### ISSUE THREAD

**Issue by clauci** [googlemaps/google-maps-ios-utils#19]
I just downloaded Google-Maps-iOS-Utils V1.0.0. and GoogleMaps iOS V2.0.0 with CocoaPods:

![screen shot 2016-07-27 at 8 46 50 am](https://cloud.githubusercontent.com/assets/16472728/17160414/62428644-53d7-11e6-93a4-fadb9da460d5.png)

Two compiler errors "Module 'GoogleMapsBase' not found" then occur:

![screen shot 2016-07-27 at 8 47 32 am](https://cloud.githubusercontent.com/assets/16472728/17160466/c09a5a78-53d7-11e6-8fff-94734e2304e6.png)

![screen shot 2016-07-27 at 8 47 15 am](https://cloud.githubusercontent.com/assets/16472728/17160452/b1389586-53d7-11e6-80f6-4975e22bf2a5.png)

My code was working with Google-Maps-iOS-Utils V1.0.0 and GoogleMaps V1.13.2.

Please help resolve this issue. Thank you!

**Comment by domesticmouse** [comment]
Cross reference: https://code.google.com/p/gmaps-api-issues/issues/detail?id=10190

**Comment by clauci** [comment]
Thank you!!

**Comment by nagender04031989** [comment]
When I compile my static framework with the Google Maps iOS SDK integrated. It compiles fine, however when I add that framework in my project, it states the error "framework GoogleMapsBase SDK not found for arm64". Same error occur for armv7 architecture also. My custom framework is woking good till I am compiling for dynamic framework but as I change the "Mach-O Type" key in build setting in my framework to "Static". It is generating this error when I add my static framework to my project. 
![screen shot 2017-05-01 at 11 24 27 am](https://cloud.githubusercontent.com/assets/28248926/25573261/4de624f2-2e61-11e7-86ab-ef63dd51686d.png)

**Comment by mountainvat** [comment]
Maybe you want to include GoogleMaps into your project too?

**Comment by nagender04031989** [comment]
@mountainvat then purpose of my SDK is not fulfilled. My concern is why it is working for dynamic type but not for static. Is there anything needs to be done extra for static framework?

**Comment by mountainvat** [comment]
Can you please post some more detailed error messages?

**Comment by nagender04031989** [comment]
By selecting my target, I got the following errors(image atta
![screen-shot-2017-05-01-at-12 15](https://cloud.githubusercontent.com/assets/28248926/25574461/52bf768a-2e6c-11e7-8f64-7625e5ae62fb.png)
ched)

**Comment by mountainvat** [comment]
Just curious are you also linking in the GoogleMaps Utils library or just the GoogleMaps SDK?

**Comment by nagender04031989** [comment]
Just SDK only.

**Comment by mountainvat** [comment]
I can see that another issue has been raised on the SDK issue tracker (https://issuetracker.google.com/issues/37727522). Would you mind tracking that bug instead because it's directly related to the SDK. Also it may help if you could provide a minimal reproduction case.
Thanks.

**Comment by avadeshgoibibo** [comment]
@nagender04031989 Did you find any solution? Same problem for me.
