### ISSUE TITLE
Constant idle CPU usage on VCs containing a google map

### ISSUE THREAD

**Issue by Hendies567** [googlemaps/google-maps-ios-utils#191]
Hi there, I'm using the Swift version of this clustering SDK within my application (latest google-maps-ios-utils version, GoogleMaps 2.7.0, Swift 4.1, Xcode 9.4 beta). My issue is that google maps doesn't seem to allow the CPU to actually idle when there's no screen interaction.
Via Xcode Instruments' CPU Profiler, numerous symbols are shown to keep firing in the background. I've attached a few screenshots of the issue below (which profiles a VC after the google map has loaded in (with no screen interaction).

<img width="795" alt="screen shot 2018-05-30 at 12 50" src="https://user-images.githubusercontent.com/26363840/40719173-88016180-640a-11e8-9ffd-94bc71b1edf1.png">

<img width="741" alt="screen shot 2018-05-30 at 12 45 35" src="https://user-images.githubusercontent.com/26363840/40718315-792ab470-6407-11e8-9c38-73c8685bbe2f.png">

As you can see, google map components are firing off for the majority of that profiling timespan, even though the view isn't being manipulated at all.
Our setup is as follows:

```
gmap.settings.setAllGesturesEnabled(false)
var bounds = GMSCoordinateBounds()
let iconGenerator = GMUDefaultClusterIconGenerator()
let algorithm = GMUNonHierarchicalDistanceBasedAlgorithm()
renderer = GMUDefaultClusterRenderer(mapView: gmap,
                                     clusterIconGenerator: iconGenerator)
clusterManager = GMUClusterManager(map: gmap, algorithm: algorithm,
                                   renderer: renderer)
renderer.delegate = self

let tapGesture = UITapGestureRecognizer(target: self, action: #selector(mapTapped))
mapView.addGestureRecognizer(tapGesture)
let item =
    ClusterItem(position: CLLocationCoordinate2DMake(self.cityLocations[0].latitude, self.cityLocations[0].longitude), name: self.cityLocations[0].name, type: "Location", imgString: locationPhotos[0].url)
clusterManager.add(item)
self.clusterItems.append(item)
clusterManager.cluster()
for item in clusterItems {
    bounds = bounds.includingCoordinate(item.position)
}
clusterManager.cluster()

DispatchQueue.main.asyncAfter(deadline: (.now() + 0.1)) {
    gmap.frame = CGRect(x: self.mapView.bounds.origin.x , y: self.mapView.bounds.origin.y-2, width: self.mapView.bounds.size.width, height: self.mapView.bounds.size.height+4)
    if self.cityLocations.count == 1 {
        gmap.camera = GMSCameraPosition.camera(withLatitude: self.cityLocations[0].latitude, longitude: self.cityLocations[0].longitude, zoom: 10.0)
    } else {
        gmap.moveCamera(GMSCameraUpdate.fit(bounds, with: UIEdgeInsetsMake(50.0 ,50.0 ,50.0 ,50.0)))
    }
    self.mapView.addSubview(gmap)
}

func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
    if marker.userData is GMUCluster {
    } else {
        if let data = marker.userData as? ClusterItem {
            marker.icon = markerIcon(type: data.type)
            marker.title = data.name
        }
    }
}
```
Things I've tried:
- On willRenderMarker, setting the marker's iconView property to nil
- On willRenderMarker, setting the marker's tracksViewChanges property to false
- Removing all google maps code (which resulted in the CPU being able to idle properly)

Any help would be greatly appreciated.

**Comment by domesticmouse** [comment]
Please raise an issue on the [Google Maps SDK for iOS Issue Tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker). This is the issue tracker for the open sourced utility library, not Google Maps SDK for iOS itself.

Thanks!
