### ISSUE TITLE
Get all items on map (clusters and/or markers)

### ISSUE THREAD

**Issue by breakline87** [googlemaps/google-maps-ios-utils#193]
Is this possible? I don't see any method which makes the markers accessible except during rendering.

Consider a scenario like:

1. user taps on a marker
2. all markers and clusters should get an opacity of 0.5
3. user taps on anywhere on the map
4. all markers and clusters should get an opacity of 1.0

My only idea is to redraw the whole thing, but is that economical?

Thanks

**Comment by arriolac** [comment]
Relates to #269
