### ISSUE TITLE
Adding this library to my swift framework

### ISSUE THREAD

**Issue by bussalleu2** [googlemaps/google-maps-ios-utils#199]
I'm developing a framework library in swift, so I can not add the library using pods and I can not follow the solution proposed here: https://github.com/googlemaps/google-maps-ios-utils/blob/d45945c6ff0937568aa7068502b2ad12dcdb0b50/ Swift.md since as I am developing a framework, it is not allowed to put a bridging-header.
How can I include this library in my swift framework?

**Comment by chris-paterson** [comment]
This is something I am also interested in doing. I'm currently running into `Include of non-modular header inside framework module...`.

**Comment by arriolac** [comment]
There's an answer on Stackoverflow related to this issue: https://stackoverflow.com/a/28552525 @bussalleu2 @chris-paterson. Does this help?

**Comment by nayooti** [comment]
I think this has been fixed in #183
