### ISSUE TITLE
get feature clicked?

### ISSUE THREAD

**Issue by fukemy** [googlemaps/google-maps-ios-utils#205]
hello. I have a question:
 How to get GMUGeometry coordinates when click on map

**Comment by kwilk83** [comment]
You want to use the GMSProjection object within the GMSMapView object.  It should be able to translate lat/long to a CGPoint referencing the screen coords.

**Comment by prachiFam** [comment]
Hi I also need the same thing. Could you explain this further

**Comment by prachiFam** [comment]
I was able to detect click using below code:

you can call this function when mapview is tapped ie. inside below method.
 func mapView(_ mapView: GMSMapView, didTapAt coordinate: CLLocationCoordinate2D) 


 func regionIsSelected(coordinates : CLLocationCoordinate2D) throws {
        let path = Bundle.main.path(forResource: "dld_areas", ofType: "json")
        let url = URL(fileURLWithPath: path!)
      
        let data: Data = try! Data.init(contentsOf: url)
        let json = try JSON(data: data)
        //our json is having properties containing area name and area id, bacause the properties field inside the GMUFeature is retuning us nil, we have to pase it indivisually
        let jsonFeatures: [JSON] = json["features"].array ?? []
        
        geoJsonParser = GMUGeoJSONParser.init(data: data)
        geoJsonParser.parse()
        
        var index = 0
        
        for feature in geoJsonParser.features {
            
            
            var innerFeature = feature
            while(innerFeature.geometry.type != "GeometryCollection"){
                print("type is" + innerFeature.geometry.type)
                
                innerFeature = innerFeature.geometry as! GMUGeometryContainer
                
            }
            
            
            let collection = innerFeature.geometry as! GMUGeometryCollection
            
            let polygon:GMUPolygon = collection.geometries.first as! GMUPolygon
            var isAreaObtained = false
            
            for path in polygon.paths{
                
                //check if the coordinates lie within the polygon
                if (GMSGeometryContainsLocation(coordinates, path, true)) {
                    
                    isAreaObtained = true
                    print(jsonFeatures[index]["properties"]["NAME_EN"])
                    print(jsonFeatures[index]["properties"]["AREA_ID"])
                    
                    print("location inside polygon")
                    break;
                    
                    
                }
            }
            if(isAreaObtained){
                break
            }
            
            index = index + 1
        }
        
    }
