### ISSUE TITLE
 install manual without CocoaPods

### ISSUE THREAD

**Issue by muhammadalkhalaf** [googlemaps/google-maps-ios-utils#211]
As a new iOS developer, it took me a few hours of messing with ObjectiveC headers to make it work in the end but most of them does't work :(
 The guide "https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md" is very basic and doesn't mention the need to change almost all header files
Is there any full guid for that please

**Comment by wiktoriatomzik** [comment]
Yeah, I feel like this step by step is not specific enough either. I'd be very thankful for a more detailed guide. For a person that's coming from a JavaScript background to XCode/Swift environment (I'm developing an app with React Native now and I need an integration) this is kinda not enough. I think adding paths where things should be placed (with screenshots preferably) would be really great.
