### ISSUE TITLE
KMLParser returns empty array

### ISSUE THREAD

**Issue by Scarnet** [googlemaps/google-maps-ios-utils#212]
Hello, 
I tried parsing the KML string but it returns an empty array of place marks and styles

[SwiftDemoApp.zip](https://github.com/googlemaps/google-maps-ios-utils/files/2694588/SwiftDemoApp.zip)

**Comment by chadbrochill317** [comment]
Hello, 
I am also having this problem!

**Comment by nathjyo** [comment]
I am also
