### ISSUE TITLE
2 POItems at 1 point don't clustering

### ISSUE THREAD

**Issue by eldarkk** [googlemaps/google-maps-ios-utils#213]
Good day. Im developing for Ios Swift Project.
I have 2 POItems (2 markers) which have same(identical) coordinates, but they dont clustering. I see 1 POItem(marker) on map. By tapping i see 1 infoWindow of them. For next tap on this POItem i see infoWindow of second POItem. I want make 2 POItems clustering in 1 cluster with 2 items in it.
I added buckets to my cod like so:

        let iconGenerator = GMUDefaultClusterIconGenerator(buckets: [2, 5, 10, 15, 20, 30, 40, 50, 100])
        let algorithm = GMUNonHierarchicalDistanceBasedAlgorithm()
        let renderer = GMUDefaultClusterRenderer(mapView: mapView,
                                                 clusterIconGenerator: iconGenerator)
        renderer.delegate = self
        clusterManager = GMUClusterManager(map: mapView, algorithm: algorithm,
                                           renderer: renderer)
        addMarkerItems()
        clusterManager.cluster()
    }

And buckets are working for POItems, located closely. But for POItems, located at 1 coordinate, clustering doesnt work.

For tapping on cluster i realized customTableView  as InfoWindow. For tapping on POItem(marker) - same customTableView with 1 row in it.

Need youre help please.

![simulator screen shot - iphone 8 plus - 2019-01-08 at 17 06 09](https://user-images.githubusercontent.com/6400167/50827167-f08f6780-1367-11e9-8276-2875c34826f7.png)

**Comment by DancingWind** [comment]
Same issue - if 3 point in same coordiante + 1 nearby POI nearby they group and all points at some distance will cluster and can be selected by custom list. But if zoom in on thsoe 3 at exact same coordinates then random POI is on top and only that one is selectable.

**Comment by Kevin-Xiaoran** [comment]
The default value of renderer.minimumClusterSize is "4". Just reset this value to "2" will simply fix your issue.
