### ISSUE TITLE
Small Scale Heatmaps Nearly Useless

### ISSUE THREAD

**Issue by mumphus** [googlemaps/google-maps-ios-utils#214]
I am working on an app that takes measurements along with coordinates and I wanted to map areas where the measurements are high in certain areas so people could visualize this as well as coming back to the area to find why the measurements were high. My issue comes when zooming in on the map, the points are just shadows and have no representation of intensity. It seems the more you zoom out the better the intensity is visualized but then you cannot tell where the high points are. I want "red" areas to be areas of high measurement rather than amount of points as well. Adding more points, changing intensity scale, and changing radius did not fix the issue.

![img_0014](https://user-images.githubusercontent.com/40215561/50938141-872d5880-143c-11e9-944d-5e7f10bae929.PNG)
![img_0015](https://user-images.githubusercontent.com/40215561/50938146-8d233980-143c-11e9-9847-e8affcbe00ce.PNG)
![img_0016](https://user-images.githubusercontent.com/40215561/50938160-957b7480-143c-11e9-86f3-8d4ef5385689.PNG)

**Comment by saqibomer** [comment]
I am having same issue, did you mange to solve this? @darbysauter

**Comment by darbysauter** [comment]
@saqibomer Sorry for the late reply

I ended up writing my own heatmapping library that would add an overlay to the map.

**Comment by thealpa** [comment]
@darbysauter Would you mind publishing your heatmapping library?
