### ISSUE TITLE
Random KVO block crashes when allocating mapView, happens only when open/close screen several times

### ISSUE THREAD

**Issue by aliakhtar49** [googlemaps/google-maps-ios-utils#215]
App is crashing on a map screen when it open and close several times. (Mostly on 6th attempt)
Class that inherits from GMSMapView

````class AirportMapView: GMSMapView , AirportMapViewProtocol{

weak var airportMapViewModuleDelegate: AirportMapViewModuleProtocol?

required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
 }
override init(frame: CGRect) {
    super.init(frame: frame)
 }
convenience init(from frame: CGRect, with cameraPosition: GMSCameraPosition) {
    self.init(frame: frame)
    self.camera = cameraPosition
 }
  func setCluster() {

    let algorithm = CustomGoogleMapsClusteringAlgorithm.init();
    mapIconGenerator = VJAirportIconGrayClusterGenerator.init()
    let renderer = VJGoogleMapsClusterRenderer(mapView: self,
                                               clusterIconGenerator: mapIconGenerator!)
    clusterManager = GMUClusterManager.init(map: self, algorithm: algorithm, renderer: renderer)
    clusterManager?.setDelegate(self, mapDelegate: self)

 }
}

**Comment by aliakhtar49** [comment]
App is crashing on a map screen when it open and close several times. (Mostly on 6th attempt)
**Class that inherits from `GMSMapView`**


In ViewController viewDidLoad I am calling init method of mapView

**Comment by iKorich** [comment]
I have got same crash

helped that - https://bluearoma.tistory.com/15

need remove 

[_mapView addObserver:self
               forKeyPath:kGMUCameraKeyPath
                  options:NSKeyValueObservingOptionNew
                  context:nil];

[_mapView removeObserver:self forKeyPath:kGMUCameraKeyPath];

from init/dealloc and add it on viewDidAppear and remove on viewDidDisappear in VC that contains MAP
