### ISSUE TITLE
no count number after customize cluster marker 

### ISSUE THREAD

**Issue by zhuxinyu2468** [googlemaps/google-maps-ios-utils#219]
I'm new to Objective-c and I'm trying to get the count number of the item marker after customized the cluster marker icon. Can anyone give me some help please? Thanks.

here is the code that I used for customize the cluster marker icon

- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker {
    
    
    if ([marker.userData conformsToProtocol:@protocol(GMUCluster)]) {
        marker.icon=[UIImage imageNamed:@"1"];
    }else if ([marker.userData conformsToProtocol:@protocol(GMUClusterItem)]) {
        marker.icon=[UIImage imageNamed:@"2"];
    }
    if ([marker.userData isKindOfClass:[POIItem class]]) {
        POIItem *item = marker.userData;
        marker.title = item.name;
       }
    
}

**Comment by nnhubbard** [comment]
```
- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker {
    
    if ([marker.userData conformsToProtocol:@protocol(GMUCluster)]) {
        
        GMUStaticCluster *cluster = marker.userData;
        NSUInteger count = cluster.count;
        
    }
    
}
```

Then you can use `count` for whatever you need.
