### ISSUE TITLE
Native Swift

### ISSUE THREAD

**Issue by fahlout** [googlemaps/google-maps-ios-utils#22]
I was wondering if a native Swift code base is in the works as I would like to use Swift code only in my app and Swift is the way to go in the long run. Just wondering if that is on the road map currently. Thanks!

**Comment by domesticmouse** [comment]
The underlying Google Maps SDK for iOS is implemented in a mix of C++ and Objective C, so a pure Swift application involving Google Maps isn't realistic. Porting Google Maps iOS Utils to Swift, however, sounds eminently reasonable thing to do.

However we aren't going to remove support for this Objective C version, as Objective C libraries are usable in Swift, but the reverse isn't true, last I checked.
