### ISSUE TITLE
High CPU and Memory usage with trackViewChanges property.

### ISSUE THREAD

**Issue by malavagile** [googlemaps/google-maps-ios-utils#224]
Hello @mountainvat,

I did use iconView for cluster and marker but it uses huge memory and CPU.

In Icon view, I am loading images of the user for cluster and marker. Since I am loading images from the server asynchronously, I have to keep the trackViewChanges property true otherwise it's not reflecting the image downloaded from the server on the map. If I keep turn on the property It takes a huge amount of CPU.

Can you help me out here?

I am enabling the tracksViewChanges from willRenderMarker method of GMUClusterRendererDelegate.

Thanks,
Malav Soni

_Originally posted by @malavagile in https://github.com/googlemaps/google-maps-ios-utils/issues/48#issuecomment-471506446_

**Comment by ivitoria** [comment]
Hi malagavile,

I used to have the same performance problem. What I do now is set trackViewChanges to false until I receive the image of the server. Then, set trackViewChanges to true, change the image and set it to false again. That solves the performance problem.
