### ISSUE TITLE
mapViewSnapshotReady not being called after setDelegate

### ISSUE THREAD

**Issue by fotiDim** [googlemaps/google-maps-ios-utils#227]
After setting the delegate: `clusterManager.setDelegate(self, mapDelegate: self)` the `func mapViewSnapshotReady(_ mapView: GMSMapView)` delegate method of `GMSMapViewDelegate` stops getting called. Weirdly enough the rest of the delegate methods like `mapViewDidFinishTileRendering` keep getting called.

**Comment by g012** [comment]
This is a pretty troublesome issue. It should remain open.

**Comment by behenate** [comment]
I'm having the same issue. Has anyone figured out how to fix it?

**Comment by mercierj** [comment]
same here

**Comment by MadanDipika** [comment]
Happening for me too
