### ISSUE TITLE
How to hide the default red pin while using clustering

### ISSUE THREAD

**Issue by StellarKuldeep** [googlemaps/google-maps-ios-utils#234]
I had load customView in marker iconView and it works fine as display in below screen but I'm unable to hide the GoogleMap default red pin.

![IMG_0039](https://user-images.githubusercontent.com/38131385/61432763-043b0c80-a94f-11e9-97d2-45cbe8909234.PNG)

To hide the GoogleMap default red pin, I have tried this `marker.icon = nil` but it doesn't work.

Please tell me how can I hide this?

**Comment by Rohit-jft** [comment]
Hi @StellarKuldeep, I appreciate it if you suggest the best possible way to resolve this. We are stuck in this.
