### ISSUE TITLE
Add a bridging header file with #import "GMUMarkerClustering.h" (note the relative path).

### ISSUE THREAD

**Issue by delphiy** [googlemaps/google-maps-ios-utils#237]
Hi,
How I do this step 

Add a bridging header file with #import "GMUMarkerClustering.h" (note the relative path).

**Comment by VictorAugustoDn** [comment]
I needed too

**Comment by jpoehnelt** [comment]
Please direct any further discussion and challenges to https://github.com/googlemaps/google-maps-ios-utils/issues/86.
