### ISSUE TITLE
no icon generator

### ISSUE THREAD

**Issue by ravindramukund** [googlemaps/google-maps-ios-utils#24]
there is no icon generator for ios, but it exists for android which is a huge help.Please include an icon generator for ios

**Comment by mountainvat** [comment]
There is an icon generator protocol and a default implementation GMUDefaultClusterIconGenerator. You can see if the default implementation help with your use cases or provide a custom implementation.

The icon generator is passed into the GMUDefaultClusterRenderer initWithMapView method.

Hope it helps.

**Comment by NeoElit** [comment]
@mountainvat yeah, but it would be an interesting helper function if there is an equivalent of [IconGenerator](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/ui/IconGenerator.java) for single markers with same features and shape.

**Comment by mountainvat** [comment]
FYI: if you wanted to customize single markers please take a look at this issue thread:
https://github.com/googlemaps/google-maps-ios-utils/issues/21

**Comment by NeoElit** [comment]
@mountainvat yeah, but still we need to provide the custom UIImage rt? I was looking for some helper which will create the UIImage from the text provided as in the map utils for android.

**Comment by mountainvat** [comment]
Yes you would have to generate the image yourself. What you can do is look at the GMUDefaultClusterIconGenerator to see how images are generated from text?

For better performance, please remember to cache the generated image(s) if there are only a handful of them.
