### ISSUE TITLE
myLocation marker is disappearing on iOS 13.1

### ISSUE THREAD

**Issue by umair-citrusbits** [googlemaps/google-maps-ios-utils#243]
I am using GoogIeMap pod in my app. I have been facing an issue with the mylocation marker disappearing and the only fix is to Reset the location & Privacy in the iPhone settings app. 

**Environment details**
OS version: iOS 13.1
GoogleMaps version: 3.1.0
Xcode version: 10.1

**Steps to reproduce**
1. Launch app 
2. Select permission "Allow while using" 
3. myLocation marker is visible
4. Quit and Launch the app 
5. myLocation marker disappears
6. Reset the location & Privacy in the iPhone settings app
7. myLocation marker is visible
8. Quit and Launch the app 
9. myLocation marker disappears

**Sample Code**
I set the value of "isMyLocationEnabled" in CLLocationManagerDelegate method
```
func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
    
    if status == CLAuthorizationStatus.authorizedWhenInUse || status == CLAuthorizationStatus.authorizedAlways {
        mapView.isMyLocationEnabled = true
    }
}
```
Do i need to update the pod for iOS 13 and create build using latest xcode?
Is it possible that I can apply a fix using Xcode 10.1? I want to avoid the latest Xcode migration/conversions.

**Comment by jpoehnelt** [comment]
Can you report this here instead: https://developers.google.com/maps/documentation/ios-sdk/support?
