### ISSUE TITLE
Marker decluster at certain zoom level

### ISSUE THREAD

**Issue by vikrantrajput** [googlemaps/google-maps-ios-utils#246]
Hello, I am working on swift 4 with xcode 10.3. I am using google map with cocoa pods
  pod 'GoogleMaps'
Now I am using cluster functionality in my app. Now I want to de cluster the marker at zoom level 12. So how I can do it in my app. I didn't get any help full code related to my requirement. 
Please suggest and help.
Thanks

**Comment by arriolac** [comment]
You should be able to prevent marker clustering once a certain zoom level is passed by using the `maximumClusterZoom` property on the **GMUDefaultClusterRenderer** object. Can you confirm that this is what you need @vikrantrajput?

**Comment by arriolac** [comment]
Please reopen if you find that the approach I mentioned doesn't work for your use case.
