### ISSUE TITLE
GMSMarkers disappearing when zoom

### ISSUE THREAD

**Issue by Avi-Ways** [googlemaps/google-maps-ios-utils#247]
I am adding 500 markers in google map and using clustering for them. I have used custom GMSMarkers by setting iconView property. It is nicely making clusters and cluster dissolves to create separate markers. But when I am trying to zoom more GMSMarker disappears. I am using swift language for iOS.

[I am adding a link for the exemplary project.](https://github.com/Avi-Ways/Cluster)

**Comment by arriolac** [comment]
@Avi-Ways looks like the markers were disappearing because this line was being called when the map view would be idle:

https://github.com/Avi-Ways/Cluster/blob/master/Cluster/ViewController.swift#L92

Removing that line fixes it.
