### ISSUE TITLE
Error building code using Carthage

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [googlemaps/google-maps-ios-utils#249]
Hello Team,

I'm getting below error while using carthage to build google maps SDK.

Skipped building google-maps-ios-utils due to the error:
Dependency "google-maps-ios-utils" has no shared framework schemes for any of the platforms: iOS

Could you please let me know why I'm getting this error?

And how do I build the framework in my project.

Thanks and Regards,
Abhishek.

**Comment by arriolac** [comment]
Carthage is not officially supported by this library yet as Carthage only supports dynamic frameworks (see: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework). Related to #99.

**Comment by kikettas** [comment]
Well, Carthage actually does support `static` frameworks since 0.30.1, and having support for Carthage would be pretty awesome for this library. Also, I saw that you became very active in the repo lately @arriolac, any plans on releasing a new stable version for the library?

**Comment by arriolac** [comment]
@kikettas good to know about Carthage. I agree that it'd be good to add support for this.

I'm doing an audit of all the commits pushed since the last release (2.1) and am planning on pushing out a `3.0` stable release in the next day or so. Stay tuned.

**Comment by kikettas** [comment]
Wow, that sounds great! Looking forward to seeing what's next!

**Comment by arriolac** [comment]
Released [v3.0.0](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v3.0.0) 🎉

**Comment by kikettas** [comment]
Cool! Nice job @arriolac, our team was looking forward to this! 💯 Will the Carthage support be the next step? 😉

**Comment by arriolac** [comment]
Thanks!

Adding Carthage support is definitely something on my list but it's probably not something I can get to yet right away. Contributions are always welcome 😃

**Comment by kikettas** [comment]
Dope! @arriolac

**Comment by arriolac** [comment]
@kikettas lmk if you run into any issues with it. There's also a silent additional feature in there... including this library via Carthage will also pull in the Maps SDK for iOS binaries (see the [Cartfile](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Cartfile#L1)). If we can get enough community excitement around this, perhaps this is something we can officially support. I filed #297 for this—feel free to use the necessary emojis 👍 👎 🎉 🚀  😃
