### ISSUE TITLE
Use of undeclared type 'GMUClusterManager'

### ISSUE THREAD

**Issue by loghozinsky** [googlemaps/google-maps-ios-utils#257]
#### Environment details

1. Google Maps Utils - clusters
2. iOS 11.2 - 13.3
3. Latest availability

#### Steps to reproduce

  0. Need Google Maps with Clusters

  1. Working with CocoaPods
  2. Library "Google-Maps-iOS-Utils" installs "correctly" (without "use frameworks" in Podfile)
  3. Project didn't see the GMUClusterManager or other types

#### Code example

My project:
import UIKit
import CoreLocation
import GoogleMaps

class ViewController: UIViewController {
    ..
    private var clusterManager: GMUClusterManager! (!) Use of undeclared type 'GMUClusterManager'
    ..
}

Podfile is as follows:
platform :ios, '7.0'

target 'PCU' do

  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

end

```
Guide me on the right track, please. 
Thanks!

**Comment by arriolac** [comment]
You are missing an import statement in your ViewController.

```
import UIKit
import CoreLocation
import GoogleMaps
import GoogleMapsUtilities // Need to import this

class ViewController: UIViewController {
..
private var clusterManager: GMUClusterManager! (!) Use of undeclared type 'GMUClusterManager'
..
}
```

**Comment by karthikasdas** [comment]
Hello

Having this issue even after importing GoogleMapsUtilities. It says no such module GoogleMapsUtilities. Plz help
