### ISSUE TITLE
Place autocomplete closed automatically without any log while typing

### ISSUE THREAD

**Issue by developerawt** [googlemaps/google-maps-ios-utils#258]
I am using google place autocomplete UI Control (https://developers.google.com/places/ios-sdk/autocomplete#add_an_autocomplete_ui_control) and getting a problem when user starts typing in search bar it closes automatically 

I am using google Places Pod (version 3.7.0) and google map Pod(version 3.7.0)
previously it is working good but when I updated both the pods then I am getting this problem
and I checked on three different version of iOS (11, 12, and 13) latest also and problem is same

I am providing you a video of the problem
https://drive.google.com/file/d/1L8ijZJxkeI1ShqbIGEvSA3klPK3fdMb0/view?usp=sharing

**Comment by arriolac** [comment]
Yikes—that does seem like a bad 🐛

I'm closing this issue though because it is not related to this library. Please refer to [GMP support page](https://developers.google.com/maps/support/) for how to best receive help for this issue.
