### ISSUE TITLE
How to change icon on cluster item or set specific cluster marker to selected? 

### ISSUE THREAD

**Issue by zubair-ets** [googlemaps/google-maps-ios-utils#269]
I have a tableView and map view on same screen. 
table is showing all custom objects and from these objects I have rendered clustering and add markers via clusterManager.

Initially I can change icons from below method 
- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker
// check if cluster item and then setting images ... etc... 

that is good and I can show my objects with custom images on markers and on clusters. 

but My requirement is to change after rendering complete. I m showing a list of objects in a separate TableView and on tapping specific row of table (object) I have to select that object's marker on map. I m using clustering. I m struggling how to get all markers. 

I have got all cluster items from 

NSArray *clusters = [_clusterManager.algorithm clustersAtZoom:20];

How can I get marker object from GMUStaticCluster item. My final requirement is to change the image and set selected to marker. 

Also this is private method in your SDK. Otherwise I can use this method to get the marker to update
- (GMSMarker *)markerWithPosition:(CLLocationCoordinate2D)position
                         from:(CLLocationCoordinate2D)from
                     userData:(id)userData
                  clusterIcon:(UIImage *)clusterIcon
                     animated:(BOOL)animated

even in Android SDK we can get all markers using this 
clusterManager.getMarkerCollection().getMarkers()

How to achieve this in iOS? Please guide...

**Comment by arriolac** [comment]
`GMUDefaultClusterRenderer` has a `markers` property (currently a private property but exposed for testing). See: https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/View/GMUDefaultClusterRenderer.m#L42

Does this accomplish what you need? This is perhaps something we can expose but need to assess if it makes sense to do so since it was hidden by design. Another way is to expose markers via `GMUClusterMamager`.

**Comment by zubair-ets** [comment]
@arriolac thanks for your response. Yes this markers `array` in `GMUDefaultClusterRenderer` helped me a lot and I have achieved my goal. Please expose it in `GMUDefaultClusterRenderer.h` file so that we can get this array directly on renderer. 

Currently I am getting this as 

    NSString *refMethodName = @"markers";
    SEL selector = NSSelectorFromString(refMethodName);
    if ([renderer respondsToSelector:selector]) {
        markersArray = [renderer performSelector:selector];
    }

If it will be in .h file we can get directly as
[renderer markers];
I m using CocoaPods 

Thank you again.

**Comment by arriolac** [comment]
This is available in 3.0.1
