### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by chlebta** [googlemaps/google-maps-ios-utils#27]
I get this error : 
```
    NSAssert(itemToClusterDistanceMap.count == _items.count,
             @"All items should be mapped to a distance");
```

in line 168 at `GMUNonHierarchicalDistanceBasedAlgorithm.m` file

Debug helpers : 
**_items** contain 2 elements 
**itemToClusterDistanceMap** contain 1 key

debug of `for loop` at line 133  :
 

1.  In the first execution he will add the second item (in _items array) to `processedItems` array.

2. In the second execution he will  check `if ([processedItems containsObject:item]) continue;` which return true because second item was add at first execution.
3. As result he has **_items** and **itemToClusterDistanceMap** with different count which cause the issue

**Comment by mountainvat** [comment]
Is it possible to include some code snippet of your GMUClusterItem implementation? I think it might be something to do with the 2 items are considered "equal".

**Comment by mountainvat** [comment]
@chlebta : any update on this?

**Comment by singhmanpreet1** [comment]
I think its happening if the latitude and longitude of more than one item are exactly same. 
Assertion failure in -[GMUNonHierarchicalDistanceBasedAlgorithm clustersAtZoom:], /Users/***/Documents/***/***/Pods/Google-Maps-iOS-Utils/src/Clustering/Algo/GMUNonHierarchicalDistanceBasedAlgorithm.m:169
2016-11-17 14:27:34.539 ***[3332:495234] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'All items should be mapped to a distance'

**Comment by mountainvat** [comment]
Items are compared by reference so having the same lat,lng should not trigger the assert. I tried clearing the items using [clusterManager clearItems] and readd them and it seemed fine.

Do you have a reproduction case that I can have a look at?

**Comment by singhmanpreet1** [comment]
It was because of the wrong latitudes and longitudes. I removed them and it works fine. 
Thanks for the response.

**Comment by singhmanpreet1** [comment]
Hello @mountainvat while working more on it, I found that the library is considering values less than -88 as invalid. But the value of should be valid upto -90 as the range of latitude is -90 to 90. Please let me know if this is the case you also facing at your end.

**Comment by manpreetg** [comment]
Hello @mountainvat ,

I am unable to place latitude -90 and 0 clusters on the map. 

Error - All items should be mapped to a distance

There are almost 1140 item on same location.

Thanks.

**Comment by mountainvat** [comment]
@manpreetg latitude has to be within this range [-85, +85] for it to be valid on the Mercator map. This assumption is implicit and we do not validate either on the GoogleMaps itself or this library.

However I am not sure that's related. So if you can fix the latitude first and see how it goes. Thanks.

**Comment by manpreetg** [comment]
@mountainvat Right. The -90 goes out of the map. I fixed with the condition of the latitude. But the Google map Android not giving any crash. Strange!!!

**Comment by mountainvat** [comment]
Certainly worth keeping this ticket open and we'll investigate for the next release.

**Comment by Bit2Dev** [comment]
If you add to map GMSMarker, and don't add this to GMUClusterManager, this XCTAssert is triggered. But if you comment out this lines, clustering is working except for this marker.

I don't want clustering this single marker. I think in some point you get all markers from GMSMapView, instead from added to GMUClusterManager.

**Comment by manpreetg** [comment]
@Bit2Dev Thanks. It helps.

**Comment by Mehul18292** [comment]
//  NSAssert(itemToClusterDistanceMap.count == _items.count,
//           @"All items should be mapped to a distance");
//  NSAssert(itemToClusterMap.count == _items.count,
//           @"All items should be mapped to a cluster");

#if DEBUG
  NSUInteger totalCount = 0;
  for (id<GMUCluster> cluster in clusters) {
    totalCount += cluster.count;
  }
//  NSAssert(_items.count == totalCount, @"All clusters combined should make up original item set");
#endif
  return clusters;



Commenting the lines as shown above.. this one is working fine.

**Comment by artemsmikh** [comment]
@Mehul18292 I don't think this is a good idea to comment assertion lines. Now you probably have issues with markers that won't show up on the map.

**Comment by ttmdung203** [comment]
@mountainvat Could you give me an idea? I have the same problem, maybe I got crash when I override `isEqual:` function of id<GMUClusterItem>. But I don't know why. Just a simple function. If I remove this code, app not crash when I rotate device quickly anymore.
`open override func isEqual(_ object: Any?) -> Bool {
        if let marker = object as? ClusterMarkerItem {
            let content = userData as? Report
            let markerContent = marker.userData as? Report
            if content != nil && markerContent != nil {
                return content == markerContent
            }
        }
        return super.isEqual(object)
    }`

**Comment by chanonly123** [comment]
This is happening when I am changing position(CLLocationCoordinate2D) of GMUClusterItem that is already added to clusterManager. To fix this I removed old GMUClusterItem and added new one and then called clusterManager.cluster(), and it worked. 
Is there a better way to update existing GMUClusterItem?

**Comment by mountainvat** [comment]
Unfortunately this is the current behaviour. Being able to update existing items would be a non trivial effort.

**Comment by chitgoks** [comment]
This is frustrating if that is the cause. i am using external data sources and i do not have issues with the android library, but  with the ios version, i get the exception.

**Comment by AlexandrGraschenkov** [comment]
I've discovered that changes in `marker.lalyer.latitude` and `marker.lalyer.longitude` affect `marker.position`. Therefore, when the clasterization changes layer position, it also affects `marker.position`. The simplest way to solve this is to simply disable these animations:
```
let renderer = GMUDefaultClusterRenderer(mapView: map, clusterIconGenerator: generator)
renderer.animatesClusters = false
```

The correct way to resolve the issue is: 
- to gain access to the private `GoogleMaps` framework and fix the logic there
- or create fake markers and animate them instead of the original ones
