### ISSUE TITLE
Kml files not displaying properly

### ISSUE THREAD

**Issue by nathjyo** [googlemaps/google-maps-ios-utils#270]
kml files not displaying properly in app

Kml files created in google earth pro, will display info in the bubble correctly and will also display correctly in google maps android.

But when using the same kml file in Xcode it displays empty bubble windows.

Is there a specific way the kml file needs to be compiled for GMS iOS 

Thanks

**Comment by arriolac** [comment]
Hi @nathjyo, thanks for reporting. 

Would you mind sharing the KML file you generated so I can look into this more? Perhaps some screenshots would help, too.

**Comment by arriolac** [comment]
Closing this in favor of tracking this issue in #278.
