### ISSUE TITLE
How can I get GMSPath from GMUKMLParser so I can use this function GMSGeometryContainsLocation ?

### ISSUE THREAD

**Issue by Mina-M-Malak** [googlemaps/google-maps-ios-utils#276]
I am trying to use GMSGeometryContainsLocation to check if this coordinates inside the polygon that I got from GMUKMLParser but this function require GMSPath so How. can I get it ?!

**Comment by arriolac** [comment]
@Mina-M-Malak you should be able to inspect the property `parser.placemarks` after invoking the `parse` method on a `GMUKMLParser`. Assuming one of the parsed properties is an instance of `GMUPolygon`, you can then get the paths via `polygon.path`.
