### ISSUE TITLE
KML file isn't renderer correctly.

### ISSUE THREAD

**Issue by ginesdeka** [googlemaps/google-maps-ios-utils#278]
Hi,

I am rendering a file using GMUKMLParser and GMUGeometryRenderer and the place marks icons and route style aren't render correctly. I have attached the file. In Android works fine.

Thanks

[VALENCIA.kml.zip](https://github.com/googlemaps/google-maps-ios-utils/files/4280627/VALENCIA.kml.zip)

**Comment by arriolac** [comment]
Thanks for reporting. I haven't had a chance yet to look into this, but I plan on doing so. In the meantime, contributions are certainly welcome.

**Comment by arriolac** [comment]
To match what's displayed on Android, I've filed #285 and #286 @ginesdeka Take a look and see if those are the issues that you meant. Note that the marker on Android is also the default one (red pin).

**Comment by arriolac** [comment]
Please see #285 and #286 instead for this issue.
