### ISSUE TITLE
How to use GMSGeometryContainsLocation for GeoJsonParser

### ISSUE THREAD

**Issue by mallikarjuna0308** [googlemaps/google-maps-ios-utils#280]
I have drawn some polygons on the google map using geojson. Now whenever the user long presses on the map, I want to check whether the long press was in the polygon or not. But unable to convert GMUFeature to GMSPath to use in GMSGeometryContainsLocation. Could anybody suggest me how to do this?

**Comment by arriolac** [comment]
@mallikarjuna0308 you can access the `geometry` object of the `GMUFeature` and get the path that way. Note that you will have to check the type of the `GMUGeometry` to ensure it contains a `GMSPath`.

e.g.

```swift
if let polygon = feature.geometry as? GMUPolygon {
    let paths = polygon.paths
    // Do something with paths here
}
```
