### ISSUE TITLE
Heatmap rendering crashes iOS when adding custom HeatmapGradient

### ISSUE THREAD

**Issue by LucaJeevanjee** [googlemaps/google-maps-ios-utils#284]
Using a branch of flutter_google_maps with an implemented heatmap layer

I am running on iOS 13.3 iPhone XS emulator and on iPad Pro

I am currently able to display a heatmap in my app using this however when I add the `gradient` parameter, it seems to cause the app to crash when it tries to render the heatmap

The error I am getting is this:

`*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   Runner                              0x00000001044cb68f -[GMUGradient interpolateColorFrom:to:ratio:] + 255
	6   Runner                              0x00000001044cb4ca -[GMUGradient generateColorMap] + 1178
	7   Runner                              0x00000001044cd8e2 -[GMUHeatmapTileLayer prepare] + 738
	8   Runner         <…>
`

This is an example of my code:

This does not crash:
```
final Heatmap heatmap = Heatmap(
        heatmapId: HeatmapId('${heatmaps.length + 1}'),
        radius: 40,
        points: points,
        opacity: 1.0);
```

This crashes:

```
final Heatmap heatmap = Heatmap(
        heatmapId: HeatmapId('${heatmaps.length + 1}'),
        radius: 40,
        points: points,
        gradient: HeatmapGradient(
            colors: [Colors.green, Colors.red],
            startPoints: [0.1, 0.6],
            colorMapSize: 8),
        opacity: 1.0);
```

**Comment by arriolac** [comment]
Hi @LucaJeevanjee, can you fill out the questions in the above issue template? This'll help us debug the issue so we can address it. Thanks!

**Comment by LucaJeevanjee** [comment]
I edited the issue to answer the questions

**Comment by arriolac** [comment]
HI @LucaJeevanjee, I have not been able to reproduce your bug. On the `SwiftDemoApp` project I tested similar parameters as yours. See 2a8057f.

Curious how you are using the library? The code snippet you shared is not Swift nor Objective-C. If you can give me more info on how you are integrating the library that might help. The stacktrace you shared implies missing symbols.

**Comment by LucaJeevanjee** [comment]
I am using `flutter` with a custom branch of `google-maps-flutter` which has the heatmap feature. The heatmap seems to be working on android and ios without a `gradient` parameter.

**Comment by arriolac** [comment]
Interesting! The Flutter version of this library is not something we maintain in this GitHub org. 

Are you referring to this package https://pub.dev/packages/google_maps_flutter_heatmap ? If so, perhaps filing an issue in the repo linked there would allow you to receive better support.
