### ISSUE TITLE
Customize cluster distance points in GMUNonHierarchicalDistanceBasedAlgorithm

### ISSUE THREAD

**Issue by malomartin** [googlemaps/google-maps-ios-utils#289]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

 **Is your feature request related to a problem? Please describe.**
As a developer, I'm very frustrated that the distance between points is not customizable in GMUNonHierarchicalDistanceBasedAlgorithm. At the moment, we need to write everything from scratch in a custom algorithm class.

 **Describe the solution you'd like**
Instead of having a constant distance of 100pts (kGMUClusterDistancePoints), a simple public property and an init taking a distance parameter could give users the opportunity to customize the algorithm. By the way, it is available on the Android version.

 **Describe alternatives you've considered**
None.

 **Additional context**
The default algorithms available at the moment don't quite fit our needs.

**Comment by arriolac** [comment]
Agreed that customizing this would be good. Feel free to submit a PR for this.

**Comment by malomartin** [comment]
> Agreed that customizing this would be good. Feel free to submit a PR for this.

Already tried. I can't push on the repo 🤷‍♂

**Comment by arriolac** [comment]
This is available on [3.1.0](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v3.1.0).
