### ISSUE TITLE
No info window shown

### ISSUE THREAD

**Issue by theolof** [googlemaps/google-maps-ios-utils#29]
I'm trying to get the info window to show when a marker is tapped.
In `didTapMarker` I set the title manually with `marker.title = "THE TITLE"`
Nothing is shown.

It works if I add the markers directly like this:
`            let marker = GMSMarker(position: initialPosition)
            marker.map = self.mapView
`
but not when I add it via the cluster.

Any suggestions?

**Comment by mountainvat** [comment]
I am unable to reproduce the issue on the individual marker level. Did you mean the cluster marker? Did it break when you set the breakpoint?

**Comment by theolof** [comment]
I did the clustering in `viewDidLayoutSubviews` which led to the problem I think.
`viewDidLayoutSubviews` can be called several times and for some reason the info window wasn't shown. When I moved the clustering to `viewDidLoad` they started showing.
