### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by kushalpal17** [googlemaps/google-maps-ios-utils#290]
pod version GoogleMaps (3.8.0)

https://stackoverflow.com/questions/52182577/ios-google-maps-sdk-crashing?rq=1

**Comment by arriolac** [comment]
Hi @kushalpal17, sorry that you are seeing a crash in your app. Since it's not related to this library (iOS utils), the open issue in https://issuetracker.google.com/113978690 would be the best place to receive support.
