### ISSUE TITLE
[Build]: Upload GoogleMapsUtils.xcframework as an artifact on a new release

### ISSUE THREAD

**Issue by arriolac** [googlemaps/google-maps-ios-utils#292]
**Is your feature request related to a problem? Please describe.**
Users should be able to download the `.framework` on a new release.

 **Describe the solution you'd like**
Update the `release.yml` github action workflow so that this is done automatically on a new release.

 **Describe alternatives you've considered**
Manually doing it.

 **Additional context**
In the Discord channel, fawaz requested help for a Xamarin integration. While Xamarin is not a platform we officially support, users should be able to download the `.framework` file themselves without having to either integrate the lib via CocoaPods or build the project themselves.

**Comment by fawazbabu** [comment]
Hi Arriolac,

Could you please release a nuget beta version of this fix for the Xamarin.iOS

**Comment by arriolac** [comment]
@fawazbabu Xamarin and nuget is not a distribution mechanism we officially support. It looks like the version(s) there were uploaded by community contributors several years ago. You are more than welcome to use the `.framework` here: https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v3.1.0 directly.

**Comment by arriolac** [comment]
Bumping priority as this feature should be done once SPM is supported. Relates to #305

**Comment by Alex-Dobrynin** [comment]
This is still an issue. Newer releases come without .xcframework
