### ISSUE TITLE
Officially support Carthage for Maps SDK for iOS

### ISSUE THREAD

**Issue by arriolac** [googlemaps/google-maps-ios-utils#297]
This is an issue to track community input and feedback on officially supporting Carthage as a dependency manager for the [Maps SDK for iOS](https://developers.google.com/maps/documentation/ios-sdk/intro) library. Note that this issue does not pertain to this utility library as [Carthage](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Carthage.md) is already supported.

 **Is your feature request related to a problem? Please describe.**
The Maps SDK for iOS currently supports CocoaPods and installing the SDK manually by downloading the binaries. This feature request is for the SDK to officially support Carthage and appropriately reflected on the documentation page under [Get Started - Install the SDK](https://developers.google.com/maps/documentation/ios-sdk/start#step_2_install_the_sdk).

 **Describe the solution you'd like**
Developers should be able to include the Maps SDK for iOS binaries by including the following in their `Cartfile`:
e.g.
```
binary "https://path/to/GoogleMapsSDK-iOS.json" ~> 3.8.0
```

 **Describe alternatives you've considered**
N/A

 **Additional context**
See #99 #201 #249 #296

**Comment by kikettas** [comment]
This would definitely be a huge deal for our team and would make it easier and faster for us to update to the latest version. We know that the Carthage project is a kind of _[abandoned](https://github.com/Carthage/Carthage/issues/2925)_, but for us, it's way too soon to migrate to SPM (binaries are not yet supported though we can expect that for the next Xcode release in June). 
So, thanks for considering it and keep up the good work! 👍

**Comment by arriolac** [comment]
> This would definitely be a huge deal for our team and would make it easier and faster for us to update to the latest version. We know that the Carthage project is kind of _[abandoned](https://github.com/Carthage/Carthage/issues/2925)_, but for us, it's way too soon to migrate to SPM (binaries are not yet supported though we can expect that for the next Xcode release in June).
> So, thanks for considering it and keep up the good work! 👍

Ah, yeah I was looking into SPM support and was a bit disappointed to see that binaries are not yet supported. I'll be keenly waiting for that.

**Comment by arriolac** [comment]
Carthage is officially supported starting version 3.9.0. See: https://developers.google.com/maps/documentation/ios-sdk/start#use-carthage

**Comment by kikettas** [comment]
Great work @arriolac! 💯 👏
