### ISSUE TITLE
Make DevApp work with GoogleMaps 2.x

### ISSUE THREAD

**Issue by mountainvat** [googlemaps/google-maps-ios-utils#30]
Currently DevApp does not compile with the new pod structure of GoogleMaps 2.0

**Comment by alexruperez** [comment]
[!] The 'Pods-MyProject' target has transitive dependencies that include static binaries: (/MyProject/Pods/GoogleMaps/Subspecs/Base/Frameworks/GoogleMapsBase.framework, /MyProject/Pods/GoogleMaps/Subspecs/Maps/Frameworks/GoogleMapsCore.framework, and /MyProject/Pods/GoogleMaps/Subspecs/Maps/Frameworks/GoogleMaps.framework)

**Comment by mountainvat** [comment]
Hi Alex,
I think your issue to integrate the utils lib with your project is probably resolved here:
https://github.com/googlemaps/google-maps-ios-utils/issues/23

This ticket is for the development workspace of the actual open source project.

**Comment by mountainvat** [comment]
Fixed in 1.0.1
