### ISSUE TITLE
Google Maps/Maps Util: Problems with GMSMarker title & Cluster Renderer

### ISSUE THREAD

**Issue by michael-mckenna** [googlemaps/google-maps-ios-utils#300]
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version: iOS 13
3. Library version and other environment information Google Maps 3.8.0, Google Maps Utils 3.1.2

#### Steps to reproduce

  1. Download the binaries via Carthage `github "googlemaps/google-maps-ios-utils"       ~> 3.1.2`
  2. Create a GMSMarker
  3. Try to set the title. You'll get the error: `Cannot assign to property: 'title' is immutable`
  4. Remove instances where the title for markers is being set since this can't be done in the late version (apparently?)
  5. Attempt to render a cluster, and the app will crash

#### Code example

Crashing here in GMUDefaultClusterRenderer, specifically inside the conditional:
```
        if (item.title && item.snippet) {
          marker.title = item.title;
          marker.snippet = item.snippet;
        }
```

#### Stack trace
![Screen Shot 2020-05-12 at 7 13 53 PM](https://user-images.githubusercontent.com/14035148/81759102-612d2380-9489-11ea-83c5-1c00e6b5c5a0.png)

Weird that `title` is immutable. This obviously is wrong. The crash might be because the title is nil since I removed all instances where it was being set in my code, or there is something behind the scenes I'm unaware of that's causing a crash when accessing this property.

**Comment by michael-mckenna** [comment]
I was able to avoid the crash by adding a "title" property to my `POIItem` class that implements `GMUClusterItem`. UNLESS I do `marker.setValue("hi", forKey: "title")` which feels dirty.

**Comment by arriolac** [comment]
Confirmed the crash. Will have a patch in a few. Thanks for reporting!

**Comment by michael-mckenna** [comment]
That was quick, thanks! Also will the patch fix the issue preventing me from setting the marker title by doing “marker.title = ...”?

**Comment by arriolac** [comment]
No—the upcoming patch will address the crash but it will not allow you to do that as all of the properties within `GMUClusterItem` are deliberately defined as readonly. This is much safer and it's a pretty consistent pattern across this library. If you do need to change the title after it has been added into the `GMUClusterManager`, I recommend removing it and adding it back.

**Comment by michael-mckenna** [comment]
Sorry I wasn’t more explicit in my question. I am actually referring to setting the title in GMSMarker. According to the example in the docs here https://developers.google.com/maps/documentation/ios-sdk/marker I should be able to set the title. 

If this is not related to the above issue, please let me know and I can instead submit a new issue on google maps repo.

**Comment by arriolac** [comment]
Ah, yes you should be able to. Can you send a larger snippet so I'm able to understand the context?

**Comment by michael-mckenna** [comment]
@arriolac Yep.

So let's say you are doing some basic set up with a marker.
```
            let marker = GMSMarker(position: coordinate)
            marker.title = "Home"
            marker.map = self.mapView
```

This will fail to build as Xcode gives an error `Cannot assign to property: 'title' is immutable`.
This happens regardless of what constructor is used when instantiating a `GMSMarker`.

**Comment by arriolac** [comment]
@michael-mckenna I see what you mean now. Looks like the `readonly` keyword on the `GMSMarker+ClusterItem` is what's causing that. Will have a fix shortly.

**Comment by arriolac** [comment]
@michael-mckenna can you confirm that 3.1.4 addresses the bug you were seeing?

**Comment by michael-mckenna** [comment]
@arriolac LGTM. Thanks for the swift responses!
