### ISSUE TITLE
Title not showing in GeoJson feature

### ISSUE THREAD

**Issue by Gustavopcaiafa** [googlemaps/google-maps-ios-utils#304]
Hi there.

I'm trying to show the title of the area using GeoJson but somehow it just doesn't shows on the map. Im using iOS 11.0 and pod Google-Maps-iOS-Utils 3.1.4 & GoogleMaps 3.9.0

I just posted on StackOverflow with more details : https://stackoverflow.com/questions/62135450/cannot-display-title-in-googlemaps-geojson-swift

if someone can help i'll be very gratefull. Thanks !

**Comment by arriolac** [comment]
I don't see a title or label referenced in the Geo JSON file you shared in the Stackoverflow post. Where/what do you expect it to show?

**Comment by Gustavopcaiafa** [comment]
> I don't see a title or label referenced in the Geo JSON file you shared in the Stackoverflow post. Where/what do you expect it to show?

Yes, you are correct, there's no tittle in the GeoJson but i am setting it manually in the geoJsonParser, looping through features, setting it in feature.style, so it should work and show the title in the area i just rendered, right? 
Also, do you know exacly how it should be in the GeoJson so it would render automatically?

**Comment by arriolac** [comment]
The title will only be applied in that case if the feature is of type "Point" and not of type "Polygon" (see: https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Geometry/GMUGeometryRenderer.m#L190...L196).  Polygons do not support displaying the title on the map. 

You should still be able to listen to tap events on the map though and display the title that way.

**Comment by Gustavopcaiafa** [comment]
Oh! Im farly new to this framework, I didn't know that,  sorry.

But then how can i achieve someting like this, with some kind of title showing in that area? I tought it was the title attribute. Should i use an overlay? 

![image](https://user-images.githubusercontent.com/29412585/83514348-dba9fb80-a4a9-11ea-8809-0f8de5575bb1.png)

**Comment by arriolac** [comment]
Still an issue
