### ISSUE TITLE
Carthage Build Failing

### ISSUE THREAD

**Issue by michael-mckenna** [googlemaps/google-maps-ios-utils#307]
Thanks for stopping by to let us know something could be better!

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
google-maps-ios-utils 
2. OS type and version
Catalina 10.15.5
3. Library version and other environment information
3.1.4
Xcode 11.5

#### Steps to reproduce

  1. Run `carthage bootstrap --platform ios --no-use-binaries --cache-builds` or `carthage update google-maps-ios-utils --platform iOS`
#### Stack trace
```
*** Fetching ocmock
*** Downloading binary-only framework GoogleMapsSDK-iOS at "https://googlemaps.github.io/google-maps-ios-utils/GoogleMapsSDK-iOS.json"
*** Checking out ocmock at "v3.6"
*** Checking out google-maps-ios-utils at "v3.1.4"
*** xcodebuild output can be found in /var/folders/nx/rv8gthqs599_hhh5yfnhfpkr0000gn/T/carthage-xcodebuild.xNoKQP.log
*** Downloading binary-only framework GoogleMapsSDK-iOS at "https://googlemaps.github.io/google-maps-ios-utils/GoogleMapsSDK-iOS.json"
*** Downloading GoogleMapsSDK-iOS.framework binary at "3.8.0"
*** Downloading ocmock.framework binary at "OCMock 3.6"
*** Building scheme "GoogleMapsUtils" in GoogleMapsUtils.xcodeproj
*** Building scheme "GoogleMapsUtils" in GoogleMapsUtils.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/me/Coding/iOS/company/project/Carthage/Checkouts/google-maps-ios-utils/workspace/GoogleMapsUtils.xcodeproj -scheme GoogleMapsUtils -configuration Release -derivedDataPath /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/11.5_11E608c/google-maps-ios-utils/v3.1.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nx/rv8gthqs599_hhh5yfnhfpkr0000gn/T/google-maps-ios-utils SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/me/Coding/iOS/company/project/Carthage/Checkouts/google-maps-ios-utils)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/nx/rv8gthqs599_hhh5yfnhfpkr0000gn/T/carthage-xcodebuild.BBFGJ4.log
```

Here's the output when running in verbose mode:

```
Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos13.4
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: /Users/michaelmckenna/Coding/iOS/Carthage/Checkouts/google-maps-ios-utils/workspace/XcodeConfig/GMU-DevApp.release.xcconfig:1: could not find included file '../Pods/Target Support Files/Pods-DevApp/Pods-DevApp.release.xcconfig' in search paths (in target 'GoogleMapsUtils' from project 'GoogleMapsUtils')

** ARCHIVE FAILED **
```

**Comment by michael-mckenna** [comment]
Maybe it has something to do with it trying to build the scheme twice? See
```
*** Building scheme "GoogleMapsUtils" in GoogleMapsUtils.xcodeproj
*** Building scheme "GoogleMapsUtils" in GoogleMapsUtils.xcodeproj
```

**Comment by arriolac** [comment]
Hi @michael-mckenna, I was not able to reproduce this. I tested this with the following contents in my `Cartfile`:

```
github "googlemaps/google-maps-ios-utils"
```

I'm also using `carthage` version 0.35.0.

Can you share the contents of your `Cartfile`?

**Comment by michael-mckenna** [comment]
Thanks for taking a look. Here's my `Cartfile`:
```
github "Alamofire/Alamofire"                    ~> 4.7.2
github "Alamofire/AlamofireImage"               ~> 3.4
github "PromiseKit/PMKAlamofire"                ~> 3.0
github "PromiseKit/CoreLocation"                ~> 3.0
github "tristanhimmelman/AlamofireObjectMapper" ~> 5.2
github "mixpanel/mixpanel-swift"                ~> 2.3.1
github "evgenyneu/keychain-swift"               ~> 19.0
github "zvonicek/ImageSlideshow"                ~> 1.8
github "bugsnag/bugsnag-cocoa"                  ~> 5.23.2
github "IBAnimatable/IBAnimatable"              ~> 5.2.1
github "kean/Nuke"                              ~> 7.6.3
github "Flipboard/FLAnimatedImage"              ~> 1.0
github "OneSignal/OneSignal-iOS-SDK"            ~> 2.9.4
github "teambition/RRuleSwift"                  ~> 0.4.2
github "googlemaps/google-maps-ios-utils"       ~> 3.1.4
github "scalessec/Toast-Swift"                  ~> 5.0.1

# Firebase/Firestore
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionTextModelBinary.json"
```

I have also tried clearing Carthage cache with `rm -rf ~/Library/Caches/org.carthage.CarthageKit`

**Comment by michael-mckenna** [comment]
@arriolac Just updated the post with output after running in verbose mode

**Comment by arriolac** [comment]
Based on the error you shared, specifically  this line:
```
error: /Users/michaelmckenna/Coding/iOS/Carthage/Checkouts/google-maps-ios-utils/workspace/XcodeConfig/GMU-DevApp.release.xcconfig:1: could not find included file '../Pods/Target Support Files/Pods-DevApp/Pods-DevApp.release.xcconfig' in search paths (in target 'GoogleMapsUtils' from project 'GoogleMapsUtils')
```

It seems to be referencing a CocoaPods specific generated file (i.e. `Pods-DevApp.release.xcconfig`). Are you by any chance using CocoaPods along with Carthage? I just tried running `carthage update` on the `Cartfile` you shared and was able to pull the dependencies just fine.

**Comment by michael-mckenna** [comment]
No Cocoapods, and no reference to Pods in my framework search paths. I did notice these two lines in your `project.pbxproj`:

```
		02B36AE91D1B922800EA3A86 /* Pods-SwiftDemoApp.debug.xcconfig */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.xcconfig; name = "Pods-SwiftDemoApp.debug.xcconfig"; path = "Pods/Target Support Files/Pods-SwiftDemoApp/Pods-SwiftDemoApp.debug.xcconfig"; sourceTree = "<group>"; };
		02B36AEA1D1B922800EA3A86 /* Pods-SwiftDemoApp.release.xcconfig */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.xcconfig; name = "Pods-SwiftDemoApp.release.xcconfig"; path = "Pods/Target Support Files/Pods-SwiftDemoApp/Pods-SwiftDemoApp.release.xcconfig"; sourceTree = "<group>"; };
```

Do you see these causing any potential issue with Carthage (grasping at straws here). Interesting you were able to run it on your end, not sure what's different on mine.

**Comment by michael-mckenna** [comment]
Looks like another framework had the same issue, see [this issue](https://github.com/Brightify/Cuckoo/issues/309). The solutions before a fix was released is in that thread. I tried the equivalent which turned out to be `carthage update --no-build && pushd Carthage/Checkouts/google-maps-ios-utils/GoogleMapsUtils.xcodeproj/xcshareddata/xcschemes && find . ! -name "GoogleMapsUtils.xcscheme" ! -name "GoogleMapsUtils.xcscheme" -delete && popd && carthage build --verbose --platform iOS`, but didn't have any luck with it. 

Looks like their fix is in [this PR](https://github.com/Brightify/Cuckoo/pull/338) which was put into their v1.4 release. This is all I could dig up on Google so far regarding my issue :/

**Comment by arriolac** [comment]
The issue you linked should not apply here since ocmock is included in this library's `Cartfile` and is configured to work with a Carthage configuration in the `.xcodeproj` file.

Can you try replacing the iOS utils dependency in your `Cartfile` so that it explicitly points to the `master` branch? It's not clear to me why the error log you shared is pulling a file no longer in `master` so perhaps changing the `Cartfile` to point explicitly to `master` might work or at least point to a different error.

> github "googlemaps/google-maps-ios-utils" "master"

**Comment by michael-mckenna** [comment]
That didn't work either. I got fed up with trying everything and nuked my laptop, and everything works now /shrug

Thanks for working with me through this thought. Feel free to close this issue.

**Comment by arriolac** [comment]
Glad you were able to resolve it!
