### ISSUE TITLE
Unable to find a specification for `Google-Maps-iOS-Utils (~> 1.0)`

### ISSUE THREAD

**Issue by shahchirag2110** [googlemaps/google-maps-ios-utils#31]
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftDemoApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for SwiftDemoApp
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils', '~> 1.0'
end
This is pod file code but still i get same error "Unable to find a specification for `Google-Maps-iOS-Utils (~> 1.0)`"
I reinstall cocoapod then also i get this type of error

**Comment by barracudalll** [comment]
Try "pod update".

**Comment by domesticmouse** [comment]
Here is what I get when I run the above Podfile through `pod install` on my mac:

```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing Google-Maps-iOS-Utils (1.0.1)
Installing GoogleMaps (2.0.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Google Maps iOS Utils test.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total
pods installed.
```

I suspect you might need to shake your CocoaPod installation.

**Comment by mountainvat** [comment]
You can try running the command below to sync your pods repo.
pod repo update
