### ISSUE TITLE
Is it possible to parse altitudes embedded in <Point> lng,lat,alt </Point> using the GMUKMLParser? 

### ISSUE THREAD

**Issue by vsars7** [googlemaps/google-maps-ios-utils#311]
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

**Comment by arriolac** [comment]
Hi @vsars7, yes, GMUKMLParser will parse lat, lng and altitude into a `CLLocation` object. Are you having issues with this?

**Comment by vsars7** [comment]
Hi @arriolac appreciate the quick response, could you provide a code example? We're currently using:

let kmlParser     = GMUKMLParser(url: url)
kmlParser.parse()
let placemarks = kmlParser.placemarks
let lineString    = placemark.geometry as! GMULineString // assuming placemark.geometry.isKind(of: GMULineString.self)
for i in 0...lineString.path.count() - 1{
     let coordinate = lineString.path.coordinate(at: i) // this provides 2D coordinate, not 3D? 
}

**Comment by arriolac** [comment]
@vsars7 I thought you were asking about [Point](https://developers.google.com/kml/documentation/kmlreference#point) but based on the code snippet you shared it looks like you need altitude parsed for [LineString](https://developers.google.com/kml/documentation/kmlreference#linestring) which parses to a `GMSPath` that does not have altitude stored as you pointed out. 

Can you confirm that `LineString` is what you need and not `Point`? If so, unfortunately this is not parsed and so this issue can be marked as a feature request.

**Comment by vsars7** [comment]
@arriolac That's right, we're currently looking to parse altitude on import of a  LineString, thanks for pointer, will mark as feature request
