### ISSUE TITLE
Cannot install via SwiftPM

### ISSUE THREAD

**Issue by michael-mckenna** [googlemaps/google-maps-ios-utils#322]
Sorry, it's me again!

Please be sure to include as much information as possible:

#### Environment details

1. Catalina 10.15.5
2. Xcode 12 Beta 4
3. google-maps-ios-utils 3.2.0

#### Steps to reproduce

 In Xcode, go to Project -> Swift Packages -> Add this repo (https://github.com/googlemaps/google-maps-ios-utils) -> For rule, choose Version, Up to Next Minor, at 3.2.0

#### Stack trace
```
There is no Info.plist found at '/Users/michaelmckenna/Library/Developer/Xcode/DerivedData/appname-beajpewuolqlhkceldxreyaspxhw/SourcePackages/artifacts/GoogleMapsUtils/GoogleMapsUtils.xcframework/Info.plist'.
```

I tried this for the sample swift app and got the same error. I've tried:
1. File -> Swift Packages -> Reset Package Caches
2. File -> Swift Packages -> Resolve Package Versions
3. Deleting everything in derived data and reinstalling packages
4. Rebooting Xcode, rebooting computer

**Comment by arriolac** [comment]
Thanks for reporting this. Looks like there is an issue with the generated .xcframework.zip file in the 3.2.0 release. I'll look into fixing this, in the meantime, you can try setting the version to 3.1.4 which should work.

**Comment by michael-mckenna** [comment]
@arriolac Unfortunately 3.1.4 doesn't seem to work either. I get
```
https://github.com/googlemaps/google-maps-ios-utils has no Package.swift manifest for version 3.1.4
```

**Comment by michael-mckenna** [comment]
![Screen Shot 2020-08-10 at 1 39 22 PM](https://user-images.githubusercontent.com/14035148/89818221-039f8600-db0f-11ea-8bb8-6ed2423e196a.png)

**Comment by arriolac** [comment]
I have 3.2.1

**Comment by michael-mckenna** [comment]
Thanks

**Comment by arriolac** [comment]
Running into some build failures. Will keep you posted.

**Comment by arriolac** [comment]
Version 3.2.1 should be available. Let me know if you run into any issues.

**Comment by michael-mckenna** [comment]
LGTM!
