### ISSUE TITLE
Show blocks of place in GMSAutocompletePrediction

### ISSUE THREAD

**Issue by Ganyev** [googlemaps/google-maps-ios-utils#324]
Hello,
I'm trying to modify our GMSAutocompletePrediction to show blocks like in screenshot below (Screenshot made from Grab app):

<img width="293" alt="Снимок экрана 2020-08-10 в 12 06 16" src="https://user-images.githubusercontent.com/41617899/89756418-3b550080-db04-11ea-9cfc-112d89b49b2d.png">

But I cannot find any info about this. And I'm not sure if this linked with GMSAutocompletePrediction
Can you please help to figure it out?

**Comment by arriolac** [comment]
Hi @Ganyev, unfortunately block information is not provided by the API so you will need to augment the Places API to produce a result like this.

**Comment by Ganyev** [comment]
@arriolac thanks for answer,
Let me clarify one more time, 
not Places API, nor Directions API are not provided with such entrances\blocks of building like in screenshot below? :
<img width="293" alt="Снимок экрана 2020-08-12 в 07 17 08" src="https://user-images.githubusercontent.com/41617899/89964537-44f97800-dc6c-11ea-9323-8f35e365c369.png">

**Comment by arriolac** [comment]
That is correct, @Ganyev. The Places API needs to be augmented with additional information from another data source to be able to produce block level information. Closing this issue.
