### ISSUE TITLE
Project Doesn't Build With SwiftPM

### ISSUE THREAD

**Issue by michael-mckenna** [googlemaps/google-maps-ios-utils#326]
#### Environment details

OS type and version: Xcode 12 Beta 4, MacOS Catalina
Library version and other environment information: 3.2.1

#### Steps to reproduce

  1. Create a new Xcode project with Storyboard
  2. Add this dependency via SwiftPM
  3. Build (CMD+B)

#### Code example

_No Code Required_

#### Stack trace
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GMSMutablePath", referenced from:
      objc-class-ref in GoogleMapsUtils(GMUGeoJSONParser.o)
      objc-class-ref in GoogleMapsUtils(GMUKMLParser.o)
  "_OBJC_CLASS_$_GMSGroundOverlay", referenced from:
      objc-class-ref in GoogleMapsUtils(GMUGeometryRenderer.o)
  "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
      objc-class-ref in GoogleMapsUtils(GMUGeometryRenderer.o)
      objc-class-ref in GoogleMapsUtils(GMUDefaultClusterRenderer.o)
      objc-class-ref in GoogleMapsUtils(GMUGeoJSONParser.o)
  "_OBJC_CLASS_$_GMSPolygon", referenced from:
      objc-class-ref in GoogleMapsUtils(GMUGeometryRenderer.o)
  "_OBJC_CLASS_$_GMSMarker", referenced from:
      objc-class-ref in GoogleMapsUtils(GMUGeometryRenderer.o)
      objc-class-ref in GoogleMapsUtils(GMUDefaultClusterRenderer.o)
      __OBJC_$_CATEGORY_GMSMarker_$_GMSMarker_GMUClusteritem in GoogleMapsUtils(GMSMarker+GMUClusteritem.o)
  "_OBJC_METACLASS_$_GMSSyncTileLayer", referenced from:
      _OBJC_METACLASS_$_GMUHeatmapTileLayer in GoogleMapsUtils(GMUHeatmapTileLayer.o)
  "_OBJC_CLASS_$_GMSPolyline", referenced from:
      objc-class-ref in GoogleMapsUtils(GMUGeometryRenderer.o)
  "_OBJC_CLASS_$_GMSSyncTileLayer", referenced from:
      _OBJC_CLASS_$_GMUHeatmapTileLayer in GoogleMapsUtils(GMUHeatmapTileLayer.o)
  "_kGMSTileLayerNoTile", referenced from:
      -[GMUHeatmapTileLayer tileForX:y:zoom:] in GoogleMapsUtils(GMUHeatmapTileLayer.o)
  "_GMSProject", referenced from:
      -[GMUGridBasedClusterAlgorithm clustersAtZoom:] in GoogleMapsUtils(GMUGridBasedClusterAlgorithm.o)
      -[GMUWeightedLatLng initWithCoordinate:intensity:] in GoogleMapsUtils(GMUWeightedLatLng.o)
      -[GMUClusterItemQuadItem initWithClusterItem:] in GoogleMapsUtils(GMUNonHierarchicalDistanceBasedAlgorithm.o)
      -[GMUNonHierarchicalDistanceBasedAlgorithm clustersAtZoom:] in GoogleMapsUtils(GMUNonHierarchicalDistanceBasedAlgorithm.o)
  "_GMSUnproject", referenced from:
      -[GMUGridBasedClusterAlgorithm clustersAtZoom:] in GoogleMapsUtils(GMUGridBasedClusterAlgorithm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by michael-mckenna** [comment]
@arriolac I had a bunch of misc build errors I had to resolve. After resolving I tried building the project but got an issue with this library. I was able to replicate on a brand new project.

**Comment by arriolac** [comment]
hmm strange. x86_64 is a supported architecture. I will take a look

**Comment by arriolac** [comment]
I was able to add this library via SPM on the `SwiftDemoApp` under `samples/SwiftDemoApp`. You can check my branch `chris/fix/326`.

Are there other steps you can share so I can try to repro? I also double checked the architectures included in the `.xcframework` and confirmed that "x86_64" was included.

**Comment by michael-mckenna** [comment]
I couldn't load your sample. 
![Screen Shot 2020-08-12 at 5 17 47 PM](https://user-images.githubusercontent.com/14035148/90073972-d5ad7380-dcbf-11ea-8c0d-ec3212368f44.png)
even after logging in.

However, I noticed the url you're using is `git@github.com:googlemaps/google-maps-ios-utils.git` but I'm using `https://github.com/googlemaps/google-maps-ios-utils.git`.  Not sure if that will make a difference.

I have pushed a sample app [here](https://github.com/michael-mckenna/gmaps-test). All I did was:

1. Create a new Xcode project with Storyboard selected
![Screen Shot 2020-08-12 at 5 21 15 PM](https://user-images.githubusercontent.com/14035148/90074207-553b4280-dcc0-11ea-94dd-638d4976c21a.png)

2. Add this dependency via SwiftPM at version 3.2.1 with url `https://github.com/googlemaps/google-maps-ios-utils.git`
![Screen Shot 2020-08-12 at 5 20 12 PM](https://user-images.githubusercontent.com/14035148/90074226-5f5d4100-dcc0-11ea-96f6-792b6a40f6b4.png)
![Screen Shot 2020-08-12 at 5 20 17 PM](https://user-images.githubusercontent.com/14035148/90074232-62583180-dcc0-11ea-9df0-67b3992d9d46.png)

3. Build (CMD+B)
![Screen Shot 2020-08-12 at 5 20 58 PM](https://user-images.githubusercontent.com/14035148/90074247-68e6a900-dcc0-11ea-911c-3a2dc8ae8b14.png)

**Comment by michael-mckenna** [comment]
Using the linked repo on another device I was able to replicate the same issue. So unlike the Carthage issue I had a while back, I don't think the issue is device based this time =P

**Comment by arriolac** [comment]
Have you included the Maps SDK (either via CocoaPods or Carthage) to your project? Note that the Maps SDK does not support SPM yet.

**Comment by michael-mckenna** [comment]
Awkward, no I did not lol. Makes sense. In all fairness I thought it would've been automatically pulled in, which seemed to be the case with Carthage where google maps was a transitive dependency so I didn't add a separate line for that

**Comment by arriolac** [comment]
Maps SDK can definitely be packaged transitively. I choose not to go that route, but now thinking about it, that's probably a lower friction integration.

**Comment by arriolac** [comment]
@michael-mckenna I'm going to close this issue. Let's continue the discussion of packaging Maps SDK for iOS transitively in #329. Thanks for bringing this up, hopefully implementing #329 will ease some integration pains!
