### ISSUE TITLE
Package Maps SDK for iOS in .xcframework to ease SPM integration

### ISSUE THREAD

**Issue by arriolac** [googlemaps/google-maps-ios-utils#329]
Comment or +1 this issue if this is something you'd like to see in the library so it can be prioritized. Also a good candidate for contributions.

 **Is your feature request related to a problem? Please describe.**
Currently, integrating this library with SPM requires that developers additionally include Maps SDK for iOS either via CocoaPods or Carthage. In other words, the Maps SDK is not packaged in the `.xcframework` which causes additional friction and confusion (see #326) while using this library.

 **Describe the solution you'd like**
The Maps SDK for iOS should be included in the `.xcframework.zip` asset on each release so that developers can just include the iOS Utils library.

 **Describe alternatives you've considered**
Keep existing integration.

 **Additional context**
See #326

**Comment by michael-mckenna** [comment]
As the confused in #326 I'm a proponent. Without it being included I have to maintain Google Maps manually or use Carthage, both of which require a lot of [extra steps](https://developers.google.com/maps/documentation/ios-sdk/start) I'd rather not mess with again. Cocoapods is not an option for my team. Additionally I think it'd be a great idea so the google-maps-ios-utils can maintain the proper corresponding Google Maps version. If there is an version incompatibility down the road, it'd be on the developer to figure out the issue and update either this or Google Maps to the appropriate version.

**Comment by arriolac** [comment]
@michael-mckenna curious... why is CocoaPods not an option for your team?

**Comment by michael-mckenna** [comment]
Mainly two reasons. The primary is that we are transitioning to SwiftPM as it's the officially supported dependency manager. The second is that cocoapods lead to dreadfully slow incremental build times which slowed the development cycle. Switching to Carthage remediated that issue, so there's no looking back for us ;) if memory serves me correctly, we got our incremental build times down from 1m45s on cocoapods to 23s with Carthage. This was also 2-3 years ago.

**Comment by arriolac** [comment]
Wow, that's quite a huge difference 😅  Thanks for providing context.

**Comment by arriolac** [comment]
@michael-mckenna the built XCFramework simply mirrors the architectures that are currently supported by the SDK (arm64
 & armv7 for iPhones, and i386 & x86_6 for Simulators). Adding support for Mac Catalyst, which we are evaluating and will eventually support, would be a separate step.

**Comment by luispadron** [comment]
+1 for a solution that would allow using only the officially supported dependency manager.

**Comment by Scvairy** [comment]
> @michael-mckenna the built XCFramework simply mirrors the architectures that are currently supported by the SDK (arm64
> & armv7 for iPhones, and i386 & x86_6 for Simulators). Adding support for Mac Catalyst, which we are evaluating and will eventually support, would be a separate step.

Don't forget add arm64 for Simulators, so we can use it on new arm macs 😉

**Comment by cltnschlosser** [comment]
This is marked as good first issue, but it’s really up to the maintainers and distributors of https://cocoapods.org/pods/GoogleMaps. There is a lot of good information on xcframeworks here: https://github.com/bielikb/xcframeworks. It’s likely a simplification of the existing process for packaging the GoogleMaps framework and wouldn’t take much effort for someone to repackage it.

It is probably possible that someone external to google could download the existing release and repackage it as an xcframework, but I doubt Google wants the officially supported way to use google maps for spm and m1 macs to be: download a modified version of our binaries from someone else...

**Comment by arriolac** [comment]
I filed this issue considering that the existing Maps SDK for iOS .framework could be packaged into the Maps SDK for iOS Utility library .xcframework. However, that's not really how SPM packages work. 

Rather, the steps to mark this issue fixed would be: (1) for the Maps SDK for iOS to support .xcframeworks, and (2) update Package.swift for this repo and specify Maps SDK for iOS as a dependency. (1) needs to be done by us, and (2) can be done by us or a contributor. Since this issue is blocked by (1), I'll remove the `good first issue` label since you are correct that this needs to be provided by us. 

(1) currently has no ETA so if you are using .xcframework version of this library you will need to include the Maps SDK for iOS dependency in addition using one of the installation options (CocoaPods, Carthage, or manual).

**Comment by mthole** [comment]
Big +1 to this issue. I'd love to see GoogleMaps properly available via SPM. It's the primary blocker in moving my large app fully onto SPM now.

**Comment by luispadron** [comment]
Any update on this issue? It’s a blocker for a lot of users.

**Comment by arriolac** [comment]
Please see my comment here https://github.com/googlemaps/maps-sdk-for-ios-samples/issues/70#issuecomment-811231129

**Comment by SaidAlSouti** [comment]
Any update on this feature request?

**Comment by iserbius** [comment]
+1, still waiting `. xcframework`

**Comment by federicopolesello** [comment]
+1

**Comment by RyuX51** [comment]
+1

**Comment by steffenbirkis** [comment]
+1

**Comment by piotrekjeremicz** [comment]
+1

**Comment by twprzybysz** [comment]
+1

**Comment by mathaeus** [comment]
+1

After the release of the SPM-compatible GoogleSignIn SDK this week, the Google Maps SDK is the last one for us that does not yet support SPM. So this would be highly appreciated🤞

**Comment by kemalenver** [comment]
Any updates on SPM and Apple Silicon slices?  This is also our last one that we need to update before we can go 100% SPM, and not need to run our project with Rosetta.

**Comment by thehavre** [comment]
@arriolac Hi! Could you please clarify, since new 6.0.0 version of Google Maps SDK is available and #355 is closed, may we use this new XCFramework version in our local Swift Packages?

**Comment by ElysiumWhale** [comment]
+1

**Comment by thr1llseek3r** [comment]
+1

**Comment by EastHell** [comment]
+1

**Comment by Vl330** [comment]
+1

**Comment by petropavel13** [comment]
+1

**Comment by akhakimzyanov** [comment]
+1

**Comment by Neilfau** [comment]
+1

**Comment by VincentDurandChewbi** [comment]
+1

**Comment by Neilfau** [comment]
+1

**Comment by leenatekani5** [comment]
Any update on when SPM will be available for google maps.

**Comment by VincentDurandChewbi** [comment]
+1 still waiting for this update.
Last version of google maps sdk allows build on new arm mac so is there anything still blocking the SPM migration ?

**Comment by blazek** [comment]
+1

**Comment by TaimoorSaeed** [comment]
+1

**Comment by Neilfau** [comment]
+1

**Comment by stherold** [comment]
+1

**Comment by ARamy23** [comment]
+1

**Comment by StefanNestorov** [comment]
+1

**Comment by DanijelHuis** [comment]
+1

**Comment by AmarSinghRajput** [comment]
Any update on when SPM will be available for google maps

**Comment by ARamy23** [comment]
+1

**Comment by emilismayilov095** [comment]
+10

**Comment by wangela** [comment]
Hi folks, I see the need here. I recommend ["starring" the issue](https://issuetracker.google.com/issues/141721633) on the Maps SDK for iOS Public Issue Tracker as the best way to get notified when SPM support is available for the Maps SDK for iOS. That's the first priority, then the subsequent packaging in this Utils library will be easier.

**Comment by tuananhdoqm** [comment]
It is now officially supported https://cloud.google.com/blog/products/maps-platform/google-maps-platform-sdks-for-ios-now-available-through-swift-package-manager
