### ISSUE TITLE
marker custom icon and info window

### ISSUE THREAD

**Issue by dimitrisddd** [googlemaps/google-maps-ios-utils#34]
Before I attempt adding marker clusterer to my project, I would like to ask this:

Right now in my project I create a marker for every object of my data model
let marker = GMSMarker(position: position)
....
marker.map = mapView

And I override the following method for presenting my own info window
func mapView(mapView: GMSMapView, markerInfoWindow marker: GMSMarker) -> UIView? {
    let infoWindow = NSBundle.mainBundle().loadNibNamed("InfoWindow", owner: self, options: nil)[0] as! CustomInfoWindow
    //customization code for the infoWindow 
    .......
    return infoWindow
}
 
When my data model changes I call 
mapView.clear()
and I add the new markers

If I use marker clusterer 
Will I be able to add GMSMarker objects to the clusterer. Can they have custom icons (per marker) and custom info windows?
Will I be able to clear all markers from the clusterer and add new ones (when I get new data from my backend)?

Thanks in advance for any help / advice

**Comment by ajPT** [comment]
I have the same doubt.
Is it possible to add a GMSMarker instead of POItem? If so, how can we do this?

**Comment by mountainvat** [comment]
At this stage we do not have a plan to support adding GMSMarker directly to the GMSClusterManager. We'd like to have complete control of the markers we created to avoid confusion like a GMSMarker is added and an animation is performed on its location.

The good news is that the marker is completely customizable. Please take a look at this thread for some discussion on how to achieve it: https://github.com/googlemaps/google-maps-ios-utils/issues/21.

We are planning to add some more events or methods to make it easier to customize cluster or cluster item markers. We will keep you posted when it's available.

**Comment by mountainvat** [comment]
We have released a new version 1.1.x with easy marker customization. Please update your cocoapod or source files.
For more details see https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md

**Comment by hyd00** [comment]
@mountainvat Thank you for the CustomMarkers example. It works fine with _Synchronous_ methods, however it freezes UI until it's finished downloading the images, which I do not wish. 

I have implemented _**Async**_ downloading and it's working fine. **However, while it's loading the image for a single marker or creating the mashed up cluster icon, it displays the default pink marker for cluster item and a default cluster round blue color icon with number.** 

When the images are loaded, the default icons get replaced with the custom images. 

**My question is how to disable the showing of default icons?** Please help!! Thanks!

**Comment by kumrDeepak** [comment]
Hi,  I am fresher in swift and i want add a custom marker icon in  clustering. so Please give me any suggestion as a code.

Thanks.
