### ISSUE TITLE
GMSMapView: adding custom styling creates ranges in the zoom where map doesn't render any labels

### ISSUE THREAD

**Issue by botfantasy** [googlemaps/google-maps-ios-utils#346]
#### Environment details

GoogleMaps 4.0.0 & GoogleMaps 3.10.0-beta 
Xcode 12.1
any iOS version

#### Steps to reproduce

  1. Add a `GMSMapView` to a view or a view-controller per documentation instructions.
  2. Run the map and notice the map renders labels correctly (as expected). To be more specific, pick a large city like Los Angeles and zoom all the way out so its label is not rendered. Slowly zoom inward and once the Los Angeles label appears, it will never disappear as zoom increases.
  3. Add any styling to the map using any method (JSON, inline, cloud-based). In my test, I just added the following using the JSON method:

```
[
    {
        "featureType": "water",
        "elementType": "labels.text.fill",
        "stylers": [
            { "color": "#ffffff" }
        ]
    }
]
```
   4. Run the map and recreate step 2. The map's labels will not render in certain zoom ranges (6.75-6.9, 7.75-7.9, etc.).

**Comment by botfantasy** [comment]
@arriolac can you at least confirm that you experience this same problem?

**Comment by arriolac** [comment]
Hey @botfantasy, based on your description, it looks like this might be a bug on the Maps SDK for iOS itself, not on a feature on this Utility Library. I've looked through the list of bugs filed in our public issue tracker but no mention of this issue. I recommend reporting this [here](https://issuetracker.google.com/issues/new?component=188833&template=789005) to receive better support.

**Comment by botfantasy** [comment]
Will do, thanks for the help.
