### ISSUE TITLE
iOS marker.userData nil after cluster/deCluster

### ISSUE THREAD

**Issue by G-Steve-E** [googlemaps/google-maps-ios-utils#349]
This is occurring in my iOS app using the “utility library for the Maps SDK for iOS.”  

The app first displays the Map at a zoom level of 5 and shows individual markers.  Tapping an individual marker when they are first displayed does work correctly and marker.userData contains the “markerKey” data set when the marker was created.
If you then Zoom the Map out to display clusters and tap on a cluster marker the “didTap marker” IF statement in the code below is TRUE and the map is centered on the cluster marker and zooms in potentially displaying smaller clusters.  After tapping on subsequent cluster markers you can zoom to a level where individual markers are displayed.  Tapping on an individual marker at this point results in marker.userData being NIL.  This always happens if individual markers have been clustered and then de-clustered.

#### Environment details
This is occurring in my iOS app using the “utility library for the Maps SDK for iOS.” 
App works fine before attempting to implement clustering

#### Steps to reproduce

1. The app first displays the Map at a zoom level of 5 and shows individual markers.  Tapping an individual marker when they are first displayed does work correctly and marker.userData contains the “markerKey” data set when the marker was created.

2. Zoom the Map out to display clusters and tap on a cluster marker the “didTap marker” IF statement in the code below is TRUE and the map is centered on the cluster marker and zooms in potentially displaying smaller clusters.  

3. After tapping on subsequent cluster markers you can zoom to a level where individual markers are displayed.  Tapping on an individual marker at this point results in marker.userData being NIL.  This always happens if individual markers have been clustered and then de-clustered.

#### Code example
Here is the Swift code where the cluster Manager is initialized:
```
    import GoogleMaps
    import GoogleMapsUtils
	...
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        // Set up the cluster manager with the supplied icon generator and
        // renderer.
        let iconGenerator = GMUDefaultClusterIconGenerator()
        let algorithm = GMUNonHierarchicalDistanceBasedAlgorithm()
        let renderer = GMUDefaultClusterRenderer(mapView: viewMap,
                                    clusterIconGenerator: iconGenerator)
        clusterManager = GMUClusterManager(map: viewMap, algorithm: algorithm,
                                                          renderer: renderer)
        // Register self to listen to GMSMapViewDelegate events.
        clusterManager.setMapDelegate(self)
		...
```

Here is the Swift code where the app sets the marker.userData property for a marker:
```
	let position = CLLocationCoordinate2D(latitude: y ?? 0.0 , longitude: x ?? 0.0)
	let marker = GMSMarker(position: position)
	marker.icon = UIImage(named: "VerifiedPin")
	marker.userData = markerKey
	self.markerArray.append(marker)
	//print("marker Array: ", self.markerArray)
	clusterManager.add(marker)
```
Once all markers have been added the app calls: 
```
	self.clusterManager.cluster()
```
And here is where the app is notified when a user taps a cluster marker or an individual marker that the app created above.
```
    func mapView(_ mapView: GMSMapView, didTap marker: GMSMarker) -> Bool {
        print("marker.userData = ", marker.userData)
	//Check to see if tapped marker is cluster marker or individual marker
        if marker.userData is GMUCluster {
            // center the map on tapped Cluster marker
            viewMap.animate(toLocation: marker.position)
            // zoom in on tapped cluster
            viewMap.animate(toZoom: viewMap.camera.zoom + 1)
            print("Did tap cluster")
            return true
        }
	//We get here because the user tapped an individual marker, not a cluster marker
        tappedMarker = marker
        print("marker.userData = ", marker.userData)
        let markerKey = marker.userData as! String       <====== marker.userData is nil once the markers are clustered and then de-clustered
        print("Did tap marker w/key: ", markerKey)
```
=============================
This was reported to Google Maps support team - Case #33946296
Here is their response:

My name is Jab and I am a colleague of Christine here on the Maps Platform Support team. I've recently been reassigned to your case as Christine is currently off shift. 

First off, please note that the Marker Clustering library is out of our support scope and documentation. Therefore, we can only help you in a best effort manner. 

Upon further checking the code you provided, I was able to reproduce the issue and it looks like this is an issue with the Marker Clustering library. For further assistance regarding this matter, please check the library issue tracker here: https://github.com/googlemaps/google-maps-ios-utils/issues

You can also check for similar issue/topics in our StackOverflow community at http://stackoverflow.com/questions/tagged/google-maps.  This community is also monitored by Google Advocates that will provide assistance where needed.
 
Thank you and have a great day!

Regards,
Jab
Google Maps Platform Technical Support (APAC)
ref:_00Df423Flu._5004MgXmAr:ref

**Comment by arriolac** [comment]
I think the issue is related to adding a `GMSMarker` directly to `GMUClusterManager`, this is a bug that needs to be addressed.

As a workaround, you can create a wrapper class that conforms to `GMUClusterItem`, create instances of that class, and add it directly to the `GMUClusterManager`. An earlier version of the [ClusteringViewController](https://github.com/googlemaps/google-maps-ios-utils/blob/7a820a122f270740da13bb63445727b62f86502e/samples/SwiftDemoApp/SwiftDemoApp/ClusteringViewController.swift) demonstrates this.

**Comment by G-Steve-E** [comment]
I made the proposed change to GMUDefaultClusterRenderer.m:

 


if ([marker.userData conformsToProtocol:@protocol(GMUCluster)]) { 

	

 

	

 


      marker.userData = nil; 

	

 

	

}

 

locally and that appears to fix the issue.

**Comment by G-Steve-E** [comment]
Haven’t tried yet but does this work properly in the Android Library?  I need to update the Android version of my App as well.

Thx,

Steve

 

From: Recreational Technologies <stephen.g.ellis@recreationaltech.com> 
Sent: Monday, November 23, 2020 3:13 PM
To: 'googlemaps/google-maps-ios-utils' <reply@reply.github.com>; 'googlemaps/google-maps-ios-utils' <google-maps-ios-utils@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [googlemaps/google-maps-ios-utils] iOS marker.userData nil after cluster/deCluster (#349)

 

I made the proposed change to GMUDefaultClusterRenderer.m:

 


if ([marker.userData conformsToProtocol:@protocol(GMUCluster)]) { 

	

 

	

 


      marker.userData = nil; 

	

 

	

}

 

locally and that appears to fix the issue.

**Comment by arriolac** [comment]
Great, glad that worked out for you. I'm looking into the build errors now and should release this change soon.

This issue is specific to iOS and should not be an issue on Android.

**Comment by G-Steve-E** [comment]
Thanks for the help. Let me know when the build is updated and I’ll update my cocoapod to the released version.

BTW, I posted this on stackoverflow if you want to update or I can once the fix is released.
