### ISSUE TITLE
Where is Geojson utils on IOS?

### ISSUE THREAD

**Issue by hoogw** [googlemaps/google-maps-ios-utils#35]
I had use google map android utils geojson, it is great! However, where is geojson utils on ios? I can't find it, the current ios utils only has cluster.

**Comment by domesticmouse** [comment]
We accept pull requests!

**Comment by manpreetg** [comment]
Is there any update on this? I also want o overlay a GeoJson File. Please let me know if there is any method any where. I tried my own but the map hangs because of the data.

**Comment by mountainvat** [comment]
We're working on the GeoJson and KML rendering. Just out of curiosity how
many geometries there are in your geojson file?

**Comment by manpreetg** [comment]
@mountainvat Thanks for the update. I have two geometries which is of Multipolygon type. There are number of nested polygons as well. Will you please let me know the expected date of completion?

I am in but hurry. I tried by creating GMSPolygon. But the map hangs if I try to to render using for loop.

**Comment by mountainvat** [comment]
@manpreetg we do not have a concrete date but hopefully in 2 to 3 months for both KML and GeoJSON rendering.

Would you mind sharing the GeoJSON file so that we can use it to test our code? If it contains confidential data it's fine to not to. Thanks.

**Comment by manpreetg** [comment]
Thanks again. I will share the GeoJson, no problem in that. I made the overlay of world in multipolygons, so that we can show the map in offline mode as well. It is possible if I can pull any progress on the GeoJSON. I don't need KML only for GeoJSON.

**Comment by mountainvat** [comment]
@manpreetg our code is not ready to share at the moment. Please check back in later.

**Comment by manpreetg** [comment]
@mountainvat Is it possible to use Javascript file to load Geojson on Map, as Javascript supports Geojson and also the Swift supports Javascript?

**Comment by mountainvat** [comment]
@manpreetg No we can only parse a GeoJSON format file.

**Comment by manpreetg** [comment]
@mountainvat Thanks. I will provide you the GeoJSON, once I will be sure its working fine. I will be testing it with the Javascript. Thanks for the marvellous Clusters. (y)

**Comment by domesticmouse** [comment]
I believe this issue is now closed. Please re-open if this isn't the case.
