### ISSUE TITLE
App Crashes when using renderer.render()

### ISSUE THREAD

**Issue by mallikarjuna0308** [googlemaps/google-maps-ios-utils#351]
#### Environment details

1. OS Type: MacOS Catalina; version: 10.15.7
2. Xcode version: 12.1
3. GoogleMapsUtils version: 3.1.4 

#### Steps to reproduce

  1. call a function in a scheduled timer
  2. the function contains the render function
  3. after calling the few times the app crashes due to memory issue.

#### Code example

```
var renderer: GMUGeometryRenderer!
var slotTimer: Timer?

func slotData() {
      autoreleasepool {
             DispatchQueue.main.async {
                    self.renderer.render()
             }
      }
}
   
    /// To run the timer every 5 seconds to update the data.
    func runSlotTimer() {
        if slotTimer == nil {
            slotTimer =  Timer.scheduledTimer(
                timeInterval: TimeInterval(5.0),
                target      : self,
                selector    :(#selector(slotstatusData)),
                userInfo    : nil,
                repeats     : true)
        }
    }

@objc func slotstatusData() {
        slotSeconds += 1 
        print("slotSeconds:", slotSeconds)
        if slotSeconds == 5 {
            slotData()
            slotSeconds = 0
        }
    }
```
I have a requirement where I need to call the render() every 5 seconds to update the colour of the parking slots based on the data I receive from the server. I tried commenting the some code to find the memory issue and finally I found that calling render() producing the memory issue. So could anybody help me in this regard. 
Thanks!

**Comment by arriolac** [comment]
HI @mallikarjuna0308, have you tried calling `clear()` before calling `render()`? Looking at the implementation of `render`, you will continually see objects rendered on top of each other for subsequent calls.

**Comment by mallikarjuna0308** [comment]
@arriolac, I tried it...and it worked. Thank you for support. :)
