### ISSUE TITLE
Help to check why this code fail in ios 

### ISSUE THREAD

**Issue by DurankGts** [googlemaps/google-maps-ios-utils#356]
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

this code is failing in ios side objetive c. Tested in iphone xs, ios 14
please I need support

-(void)addToPath:(long long)param param1:(double)param1 param2:(double)param2{
    GMSMutablePath *path = (GMSMutablePath*) param;
    [path addLatitude:param1 longitude:param2];
}

**Comment by arriolac** [comment]
Can you provide more context? Looking at the short snippet you shared that won't compile because `param` is not of type `GMSMutablePath`.
