### ISSUE TITLE
Readme pod suggested version mismatch with cocoapod version available

### ISSUE THREAD

**Issue by Iameora** [googlemaps/google-maps-ios-utils#363]
#### Steps to reproduce

  1. follow your readme file to add via cocoapods, it say "pod 'Google-Maps-iOS-Utils', '~> 3.8.0'"
  2. pod install return error since that version is not available on cocoapods https://cocoapods.org/pods/Google-Maps-iOS-Utils

Thanks in advance!

**Comment by arriolac** [comment]
Thanks for reporting! Looks like an issue with the publishing workflow. Will fix.

**Comment by arriolac** [comment]
3.8.0 should now be available on CocoaPods. I also created #364 to fix publishing workflow issues in the future.
