### ISSUE TITLE
no such module GoogleMapsUtilities

### ISSUE THREAD

**Issue by karthikasdas** [googlemaps/google-maps-ios-utils#372]
Hello

Having this issue even after importing GoogleMapsUtilities. It says no such module GoogleMapsUtilities. Plz help

_Originally posted by @karthikasdas in https://github.com/googlemaps/google-maps-ios-utils/issues/257#issuecomment-830837502_

**Comment by arriolac** [comment]
Please provide more details about your issue (package manager, versions, etc.)

**Comment by karthikasdas** [comment]
Hi I resolved it by using 3.4.1(if i remember correctly)..resolved it yesterday so don't remember the exact version..but i believe there is an issue with integrating using cocoapods without providing version number.

**Comment by arriolac** [comment]
Gotcha. Glad using 3.4.1 resolved the issue. Please reopen if you are still seeing this.
