### ISSUE TITLE
[Clustering] iOS SwiftUI Clustering doesn't work as expected.

### ISSUE THREAD

**Issue by dragosiancu0504** [googlemaps/google-maps-ios-utils#373]
Hello,

I'm trying to implement clustering in **Swift UI** using GoogleMapsUtils 3.9.0.
For this purpose I've created a `UIViewRepresentable` struct that has a Binding for GMSMarkers which are passed from calling an endpoint.

The problem is that the `ClusterManager` doesn't update pins on map when `updateUIView` is called. The map remains the same it was at first load.

I tried all kinds of workarounds but nothing worked.

Anyone else having this issue?

Below is the code:

```
struct GoogleMapsClusterView: UIViewRepresentable {
    @Binding var clusterItems: [GMSMarker]
    @Binding var externalRegion: VisibleRegionOnMap
    
    @State private var region = VisibleRegionOnMap()
    @StateObject var locationManager = LocationProvider()
   
    var clusterManager: GMUClusterManager!
    
    init(items: Binding<[GMSMarker]>,
         region: Binding<VisibleRegionOnMap>) {
        self._clusterItems = items
        self._externalRegion = region
        
    }
    
    func makeCoordinator() -> ClusterCoordinator {
        return ClusterCoordinator(region: $region.onChange({ newRegion in
            externalRegion = region
        }))
    }
    
    func makeUIView(context: Self.Context) -> GMSMapView {
        
        let camera = GMSCameraPosition.camera(withLatitude: externalRegion.center.latitude,
                                              longitude: externalRegion.center.longitude, zoom: 10.0)
        let googleMapView = GMSMapView.map(withFrame: CGRect.zero, camera: camera)
        googleMapView.isMyLocationEnabled = true
        googleMapView.settings.compassButton = true
        
        let iconGenerator = GMUDefaultClusterIconGenerator()
        let algorithm = GMUNonHierarchicalDistanceBasedAlgorithm()
        let renderer = GMUDefaultClusterRenderer(mapView: mapView, clusterIconGenerator: iconGenerator)
        self.clusterManager = GMUClusterManager(map: mapView, algorithm: algorithm, renderer: renderer)
        self.clusterManager.setDelegate(context.coordinator, mapDelegate: context.coordinator)

        return googleMapView
    }
    
    func updateUIView(_ mapView: GMSMapView, context: Self.Context) {
        
        self.clusterManager.clearItems()

        self.clusterManager.add(clusterItems)
        
        self.clusterManager.cluster()
     }

}
```

Thanks in advance for the help

**Comment by arriolac** [comment]
Hi @dragosiancu0504, I don't see any issues with the code snippet you shared. To help pinpoint the bug, what happens if you try adding/updating the map by adding markers directly without using clustering, do you see the same issue?

**Comment by dragosiancu0504** [comment]
Hey Chris,
Thanks a lot for the quick reply.

If I change my `updateUIView` method to only add markers to the map everything works fine. The only annoying thing is that I have to always call `mapView.clear()` or else the are not removed as that datasource changes.

Here is the current workaround that works fine but there's no clustering.

```
    func updateUIView(_ mapView: GMSMapView, context: Self.Context) {
        mapView.clear()
        for item in clusterItems {
            item.map = mapView
        }
    }
```

So this is why my guess is there is a problem with the `ClusterManager` and `SwiftUI` or I'm missing something.

Let me know if you come up with any idea.

Have a great day!

**Comment by arriolac** [comment]
How about conforming to `UIViewControllerRepresentable` to wrap a view controller instead? That view controller can host the `GMSMapView` and `GMUClusterManager`. My hunch is that the issue is related to `clusterManager` being a property of  `GoogleMapsClusterView` in your code snippet

**Comment by dragosiancu0504** [comment]
Hey @arriolac,

Your hunch was right. Transfering the map and cluster to a view controller did the job. 

Thanks a lot for the help.

**Comment by arriolac** [comment]
Glad that worked!
