### ISSUE TITLE
customize marker icon in marker clustering

### ISSUE THREAD

**Issue by nitisha1** [googlemaps/google-maps-ios-utils#38]
Hi,
Is there any way to change default marker icon in marker clustering?

**Comment by mountainvat** [comment]
Please take a look at this thread https://github.com/googlemaps/google-maps-ios-utils/issues/34 to see if it resolves the problem you are facing.

**Comment by nitisha1** [comment]
Hi,
That doesn't helped me.it's  not showing me  override method  "markerWithPosition" in my ViewController

**Comment by mountainvat** [comment]
You would have to add a custom renderer which extends the existing GMUDefaultClusterRenderer. (Note: your ViewController extends UIViewController, not GMUDefaultClusterRenderer).

**Comment by nitisha1** [comment]
Hi,
sorry but i'm not much familiar with Objective C .could you please post sample code how can i do in swift class?
what i'm trying is
Class MyCustomRenderer : GMUDefaultClusterRenderer
{
//cannot find override method here
}

**Comment by nitisha1** [comment]
Hi,

Below is my custom renderer class i created.but now my question where do i implement this? i cannot find it in  thread #34 .
`// Animation duration for marker splitting/merging effects.
let kGMUAnimationDuration: Double = 0.5
// seconds

class MyCustomRenderer: GMUDefaultClusterRenderer {
    
    var mapView:GMSMapView?
    
    override init(mapView: GMSMapView, clusterIconGenerator iconGenerator: GMUClusterIconGenerator) {
        
        super.init(mapView: mapView, clusterIconGenerator: iconGenerator)
    }
    
      func markerWithPosition(position: CLLocationCoordinate2D, from: CLLocationCoordinate2D, userData: AnyObject, clusterIcon: UIImage, animated: Bool) -> GMSMarker {
        let initialPosition = animated ? from : position
        let marker = GMSMarker(position: initialPosition)
        marker.userData! = userData
        if clusterIcon.CGImage != nil {
            marker.icon = clusterIcon
            marker.groundAnchor = CGPointMake(0.5, 0.5)
        }
        else {
            marker.icon = self.getCustomTitleItem(userData)
            
        }
        marker.map = mapView
        if animated
        {
            CATransaction.begin()
            CAAnimation.init().duration = kGMUAnimationDuration
            marker.layer.latitude = position.latitude
            marker.layer.longitude = position.longitude
            CATransaction.commit()
        }
        return marker
    }
    
    
    
    func getCustomTitleItem(userData: AnyObject) -> UIImage {
        var item = userData as! POItem
        return item.marker.icon!
    }
    
    
}`

**Comment by vjerryv** [comment]
Use of undeclared type 'POItem'

Do I need to import something?

**Comment by nitisha1** [comment]
@vjerryv it is a model class.
well i resolved by adding condition in GMUDefaultClusterRenderer class in utils library.

**Comment by vjerryv** [comment]
@nitisha1 could you tell me more about and what you resolved by adding condition in GMUDefaultClusterRenderer class?

I am getting stuck in this customize marker.

**Comment by nitisha1** [comment]
@vjerryv 
Look for method "markerWithPosition" in GMUDefaultClusterRenderer and the else condition
`// Returns a marker at final position of |position| with attached |userData|.
// If animated is YES, animates from the closest point from |points|.
- (GMSMarker *)markerWithPosition:(CLLocationCoordinate2D)position
                             from:(CLLocationCoordinate2D)from
                         userData:(id)userData
                      clusterIcon:(UIImage *)clusterIcon
                         animated:(BOOL)animated {
  CLLocationCoordinate2D initialPosition = animated ? from : position;
  GMSMarker *marker = [GMSMarker markerWithPosition:initialPosition];
  marker.userData = userData;
  if (clusterIcon != nil) {
    marker.icon = clusterIcon;
    marker.groundAnchor = CGPointMake(0.5, 0.5);
  }
    else
    {
      //added by Nitisha
     Spot *data = userData;
        if(data != nil)
        {
     marker.icon = data.marker.icon;
        }
      //ends here
    }
  marker.map = _mapView;

  if (animated) {
    [CATransaction begin];
    [CATransaction setAnimationDuration:kGMUAnimationDuration];
    marker.layer.latitude = position.latitude;
    marker.layer.longitude = position.longitude;
    [CATransaction commit];
  }
  return marker;
}
`
Spot is a Model class when you can declare variables as per your requirement.i added marker as a variable.and add that model class in clustering folder of utils library
This is my Spot.h
`#import <Foundation/Foundation.h>
@import CoreLocation;
#import "GMUClusterItem.h"
#import <GoogleMaps/GoogleMaps.h>


@interface Spot : NSObject <GMUClusterItem>

@property (nonatomic) CLLocationCoordinate2D location;

@property (nonatomic, strong) GMSMarker *marker;

@end`

**Comment by Villi14** [comment]
import UIKit

class CustomClusterRenderer: GMUDefaultClusterRenderer {
    let GMUAnimationDuration: Double = 0.5
    var mapView: GMSMapView?

    override init(mapView: GMSMapView, clusterIconGenerator iconGenerator: GMUClusterIconGenerator) {
        super.init(mapView: mapView, clusterIconGenerator: iconGenerator)
        self.mapView = mapView
    }

    func markerWith(position: CLLocationCoordinate2D, from: CLLocationCoordinate2D, userData: AnyObject,
                            clusterIcon: UIImage, animated: Bool) -> GMSMarker {
        let initialPosition = animated ? from : position
        let marker = GMSMarker(position: initialPosition)
        marker.userData = userData
        if clusterIcon.cgImage != nil {
            marker.icon = clusterIcon
            marker.groundAnchor = CGPoint(x: 0.5, y: 0.5)
        } else {
            marker.icon = self.getCustomUIImageItem(userData: userData)
        }

        marker.map = mapView
        if animated {
            CATransaction.begin()
            CAAnimation.init().duration = GMUAnimationDuration
            marker.layer.latitude = position.latitude
            marker.layer.longitude = position.longitude
            CATransaction.commit()
        }
        return marker
    }

    func getCustomUIImageItem(userData: AnyObject) -> UIImage {
        if let item = userData as? POIItem {
           return item.image!
        }
        return UIImage()
    }

}

class POIItem: NSObject, GMUClusterItem {
    var position: CLLocationCoordinate2D
    var image: UIImage!

    init(position: CLLocationCoordinate2D, image: UIImage) {
        self.position = position
        self.image = image
    }
}

**Comment by elvinaze** [comment]
I am getting error as cgImage is not type of UIImage, any help?

**Comment by ranjtha20** [comment]
how to implement GMUClusterRenderer for custom marker icon ?

**Comment by laurencechengithub** [comment]
Hi, I'm new in Swift, (don't understand obj-c)
after stuck for hours, could somebody be kind enough to give me guideline on how to implement customize marker?? 
i mean, where to put each func ? 
where should create new variable? 
and which files should i extension?

anyone please,
