### ISSUE TITLE
Missing xcframework in 3.10.0 release

### ISSUE THREAD

**Issue by talsec-app** [googlemaps/google-maps-ios-utils#380]
Hey!

Is there any option to add .xcframework for 3.10.0 version?

Thanks

**Comment by arriolac** [comment]
Yep, an .xcframework should be available but looks like the automated release process failed last week. Will push out an .xcframework shortly.

**Comment by arriolac** [comment]
This should now be available. Please reopen if you encounter any issues. Thanks!

**Comment by talsec-app** [comment]
@arriolac I have an issue with usage:

checksum of downloaded artifact of binary target 'GoogleMapsUtils' (23ac812e61eccdf1ec4cd77feb2614933ece96ade1e623dd43b8494df8d307b8) does not match checksum specified by the manifest (5d9218c7e3c67836218c2159d13a4d4e7ed1eae98be4a4c609dd89edb5c2c657)

**Comment by arriolac** [comment]
Will look into

**Comment by arriolac** [comment]
Please try with version 3.10.1 which should address the checksum issue
