### ISSUE TITLE
Associating data with GEO JSON features

### ISSUE THREAD

**Issue by zomein** [googlemaps/google-maps-ios-utils#383]
When features (overlays) are rendered on the map, there is no way to associate data with each overlay. The _userdata_ property or something should be writable before rendering the overlays on the map.  When tapping an overlay on the map devs should be able to get the feature properties for that specific overlay.

**Comment by idsky2** [comment]
This is needed!  I had my features rendering beautifully on my map but cannot determine which feature was tapped in the didTapOverlay function.  Crazy.  So I'm throwing out this whole library and rendering my own overlays with userData actually set to something.
