### ISSUE TITLE
Google-Maps-iOS-Utils not installing with cocoa pods.

### ISSUE THREAD

**Issue by mdabrarniyazi** [googlemaps/google-maps-ios-utils#39]
I am trying to use Google-Maps-iOS-Utils in my project through Podfile where I use use_fameworks!.
It's giving error because GoogleMaps is static. Then I tried to copy Google-Maps-iOS-Utils manually and install only GoogleMaps from Podfiles.  I am getting below error after that,

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GMUClusterManager", referenced from:
      type metadata accessor for __ObjC.GMUClusterManager in ViewController.o
  "_OBJC_CLASS_$_GMUDefaultClusterIconGenerator", referenced from:
      type metadata accessor for __ObjC.GMUDefaultClusterIconGenerator in ViewController.o
  "_OBJC_CLASS_$_GMUDefaultClusterRenderer", referenced from:
      type metadata accessor for __ObjC.GMUDefaultClusterRenderer in ViewController.o
  "_OBJC_CLASS_$_GMUNonHierarchicalDistanceBasedAlgorithm", referenced from:
      type metadata accessor for __ObjC.GMUNonHierarchicalDistanceBasedAlgorithm in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is a very serious problem and I am stuck here. Dropping use_frameworks! is not an option for me. I do not know if I have I added Google-Maps-iOS-Utils correctly. I need a serious help here.
Thanks.

**Comment by mountainvat** [comment]
Did you add the .m files to your app target?

**Comment by mdabrarniyazi** [comment]
@mountainvat I created a new group 'Google-Maps-iOS-Utils' and add both folders inside src folder here  to Xcode directly. Is that correct approach. I have also created bridging-header.h file and added  "#import <Google-Maps-iOS-Utils/GMUMarkerClustering.h>" in there. 

Here are errors :
1.  failed to import bridging header '/Users/BAPS/Documents/Backup/MapClusters/MapClusters/MapClusters-Bridging-Header.h'

2. /Users/BAPS/Documents/Backup/MapClusters/MapClusters/MapClusters-Bridging-Header.h:1:9: 'Google-Maps-iOS-Utils/GMUMarkerClustering.h' file not found

**Comment by mountainvat** [comment]
Hi there,
We've just added some instructions on how to add the utility library manually to your projects (mainly Swift but also works for ObjC). See it here [Swift.md](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md).

Hope it helps.

**Comment by mdabrarniyazi** [comment]
@mountainvat Thanks a lot. 
Though I had already solved the problem using same approach.

**Comment by mountainvat** [comment]
Great to hear that you've figured out the solution. Thanks for the update.

**Comment by deokarDattatray** [comment]
Is this library supporting GeoJSON now.

**Comment by ulaserdegor** [comment]
Same problem. Can you share your Bridging-header file and folder structure? @mountainvat  @mdabrarniyazi

**Comment by matthewdovey** [comment]
I can no longer see the steps for manual installation. Seems to only provide steps for CocoaPods.

**Comment by zyonnetworks** [comment]
I am getting Undefined Symbol's errors. I following the instructions here https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md. Please help.

`Undefined symbols for architecture x86_64:
  "_OBJC_METACLASS_$_GMSSyncTileLayer", referenced from:
      _OBJC_METACLASS_$_GMUHeatmapTileLayer in GMUHeatmapTileLayer.o
  "_kGMSTileLayerNoTile", referenced from:
      -[GMUHeatmapTileLayer tileForX:y:zoom:] in GMUHeatmapTileLayer.o
  "_GMSProject", referenced from:
      -[GMUGridBasedClusterAlgorithm clustersAtZoom:] in GMUGridBasedClusterAlgorithm.o
      -[GMUClusterItemQuadItem initWithClusterItem:] in GMUNonHierarchicalDistanceBasedAlgorithm.o
      -[GMUNonHierarchicalDistanceBasedAlgorithm clustersAtZoom:] in GMUNonHierarchicalDistanceBasedAlgorithm.o
      -[GMUWeightedLatLng initWithCoordinate:intensity:] in GMUWeightedLatLng.o
  "_GMSUnproject", referenced from:
      -[GMUGridBasedClusterAlgorithm clustersAtZoom:] in GMUGridBasedClusterAlgorithm.o
  "_OBJC_CLASS_$_GMSMarker", referenced from:
      objc-class-ref in GMUDefaultClusterRenderer.o
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSPolygon", referenced from:
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSMutablePath", referenced from:
      objc-class-ref in GMUGeoJSONParser.o
      objc-class-ref in GMUKMLParser.o
  "_OBJC_CLASS_$_GMSSyncTileLayer", referenced from:
      _OBJC_CLASS_$_GMUHeatmapTileLayer in GMUHeatmapTileLayer.o
  "_OBJC_CLASS_$_GMSPolyline", referenced from:
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSGroundOverlay", referenced from:
      objc-class-ref in GMUGeometryRenderer.o
  "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
      objc-class-ref in GMUDefaultClusterRenderer.o
      objc-class-ref in GMUGeoJSONParser.o
      objc-class-ref in GMUGeometryRenderer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by zyonnetworks** [comment]
Hopefully this helps someone running into this issue....

When running `pod install`, a library is created for `Google-Maps-iOS-Utils` in PODS, so when you build it will fail. Before following the manual instructions [here](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md), first comment out the pod dependency from the react-native-google-map podspec, then the manual instructions should give you a successful build. 

react-native 0.61.1
react-native-maps 0.26.1

**Comment by yuoppp** [comment]
@zyonnetworks 
react-native-maps podspec already has `Google-Maps-iOS-Utils` dependency. In my case, when I comment out the `Google-Maps-iOS-Utils` in my Podfile, `Google-Maps-iOS-Utils` still installs and xcode uses the files from pods.

How did you solve that?

**Comment by peterent** [comment]
This link, referenced several times on this pages, does not exist:
https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

**Comment by arriolac** [comment]
@peterent that file was removed since this Pod should install correctly with Swift now. Are you encountering issues?

**Comment by MujtabaFR** [comment]
@peterent here is the new link ..
[https://github.com/googlemaps/google-maps-ios-utils/blob/b721e95a500d0c9a4fd93738e83fc86c2a57ac89/Swift.md](https://github.com/googlemaps/google-maps-ios-utils/blob/b721e95a500d0c9a4fd93738e83fc86c2a57ac89/Swift.md)

**Comment by arriolac** [comment]
Just to clarify, the old `Swift.md` instructions should no longer apply. If you have a Swift app, you can use this library directly through CocoaPods and no longer have to copy all the files.

**Comment by ufoloko** [comment]
No, is not working, im having same issue too
