### ISSUE TITLE
Google Maps SDK for iOS version 6.0 can not run in Mac M1 simulator 

### ISSUE THREAD

**Issue by VanMinh-sudo** [googlemaps/google-maps-ios-utils#390]
Hi! I've found an issue that Google Maps SDK for iOS version 6.0 CAN NOT run in Mac M1 simulator on project written combined swift + objective c. If a project was written by only swift, it's working fine

error: building for iOS Simulator, but linking in object file built for iOS, file '...' for architecture arm64

1. Mac OS Big Sur 11.6.1, Xcode 13.1, Mac mini m1 2020
2. Google Maps version 6.0.0
3. Install framework via Cocoapod

Thanks

**Comment by dyegos** [comment]
I have the same issue. I have Xcode project in Swift on iOS 13.6, cocoa pods installation, MacOs 12.1. Google Maps 6.0.1

I get the following error building for iOS Simulator, but linking in object file built for iOS, file '/Path/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/GooglePlaces' for architecture arm64

I know there's was a fix released regarding the M1 macs and simulator, but it still does not work for me.
https://github.com/googlemaps/google-maps-ios-utils/issues/355
