### ISSUE TITLE
Podspec: invalid EXCLUDE_ARCHS value

### ISSUE THREAD

**Issue by gavrix** [googlemaps/google-maps-ios-utils#391]
This is an issue with [Podspec](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Google-Maps-iOS-Utils.podspec) defined in this repository. 

When the library is integrated using cocoapods, [these lines](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Google-Maps-iOS-Utils.podspec#L26-L27) make cocoapods insert in every `Pods-Project.xcconfig` this line:
```
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64
```
which was used as an [intermediate fix for XCode12 building for simulator](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io) but prevents building for arm-based simulator on M1 macs with XCode13. 

#### Environment details
1. API: Cocoapods -based integration
2. MacOS on M1 mac
3. 4.0.0; 3.x.x

#### Steps to reproduce
1. Add to podfile 
```
pod 'Google-Maps-iOS-Utils', '4.0.0'
```
2. `pod install`
3. Observe: all generated xcconfig files in Pods folder contain 
```
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64
```
3. Expected: there are not `EXCLUDED_ARCHS` injected in any xcconfig file

**Comment by arriolac** [comment]
Thanks for reporting. Yes, the podspec should be updated and a new version should be released to remove arm64 exclusion.

**Comment by arriolac** [comment]
Removing the `EXCLUDED_ARCHS` from the .podspec is actually blocked by the `GoogleMaps` pod which does not yet support XCFrameworks. If you are developing on an M1 machine, I recommend using either Carthage or SPM followed by installing the [.xcframework version of the Maps SDK](https://developers.google.com/maps/documentation/ios-sdk/start#install-the-xcframework).

**Comment by gavrix** [comment]
Thank you for looking into this! This is actually a transient dependency of the other dependency we use in RN environment. I'll patch that dependency and use a local podspec for Google-maps-ios-utils instead. It's all hacks and patches, but will work in the meantime.

**Comment by vincentisambart** [comment]
The CocoaPods version of Google Maps 7.3.0 [now uses XCFrameworks](https://developers.google.com/maps/documentation/ios-sdk/release-notes), so the `EXCLUDED_ARCHS` could be removed.
