### ISSUE TITLE
Can't run Google Maps 6 in the simulator in the M1

### ISSUE THREAD

**Issue by dyegos** [googlemaps/google-maps-ios-utils#394]
#### Environment details

- Google Maps 6.0.1
- Xcode 13.2.1
- iOS 13.6
- macOS 12.1
- Swift project
- Cocoapods 1.11.2

#### Steps to reproduce

  1. Use the project attached in an M1 mac [googlemapstest.zip](https://github.com/googlemaps/google-maps-ios-utils/files/7912091/googlemapstest.zip)
  2. pod install
  2. Build it for the simulator
  3. It can't build **_error building for iOS Simulator, but linking in object file built for iOS, file '/Path/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/GooglePlaces' for architecture arm64_**

**Comment by arriolac** [comment]
CocoaPods is not yet supported. If you are on an M1 machine, you will need to use the XCFramework version of the SDK. See: https://developers.google.com/maps/documentation/ios-sdk/config#install-the-xcframework 

If you'd like support for CocoaPods, please see the [public issue tracker](https://issuetracker.google.com/issues/new?component=188833&template=789005) for any existing issues on this topic (feel free to open one if none).

**Comment by billbonney** [comment]
> CocoaPods is not yet supported. If you are on an M1 machine, you will need to use the XCFramework version 
> of the SDK. See: https://developers.google.com/maps/documentation/ios-sdk/config#install-the-xcframework

There is also the simple solution of adding the GoogleMapUtils dependency using Swift Package Manager. You can do this using with Cocopods to install the GoogleMaps dependency. 

Or full SwiftPM for GoogleMaps dependency using a package.swift file created by a third-party 
e.g. https://github.com/YAtechnologies/GoogleMaps-SP

I'm not sure why Google haven't done this yet!
