### ISSUE TITLE
Randomly crash on map screen.

### ISSUE THREAD

**Issue by maulikm235** [googlemaps/google-maps-ios-utils#412]
#### Environment details
XCode : 13.4 (13F17a)
Simulator : iPhone 12 Pro Max (15.5)
macOS : 12.2.1 (21D62)
Pod version : GoogleMaps (6.2.1)

#### Steps to reproduce
- Set GoogleMaps as the first screen and open the application you will get that crash.

### gmscore::renderer::GLEntity::Draw(gmscore::renderer::EntityRenderer*, gmscore::renderer::RenderBin*, GMSPassID)
```
Crashed: com.apple.main-thread
0  libGLProgrammability.dylib     0x377d0 glvmRasterOpDepthStencilTest
1  libGLProgrammability.dylib     0x86195 glvmInterpretFPTransformFour
2  GLRendererFloat                0x12986 gldLLVMFPTransform2x2
3  GLRendererFloat                0x11af8 gldMergeScanlines2x2
4  GLRendererFloat                0x27feb gldLLVMVecPolyRender
5  GLRendererFloat                0xf540 gldRenderFillPolygonPtr
6  ???                            0x10a33b16e (Missing)
7  GLEngine                       0x1e6f7 gleFlushAtomicFunc
8  GLEngine                       0x6b10d glDrawElements_IMM_ES2Exec
9  Montana                        0x7e424d gmscore::renderer::GLEntity::Draw(gmscore::renderer::EntityRenderer*, gmscore::renderer::RenderBin*, GMSPassID) + 827
10 Montana                        0x7e8ac6 void gmscore::renderer::RenderBin::PerformDraw<std::__1::__tree_const_iterator<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, std::__1::__tree_node<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, void*>*, long> >(std::__1::__tree_const_iterator<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, std::__1::__tree_node<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, void*>*, long>, std::__1::__tree_const_iterator<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, std::__1::__tree_node<gmscore::base::reffed_ptr<gmscore::renderer::BaseEntity>, void*>*, long>, gmscore::renderer::EntityRenderer*, bool) + 134
11 Montana                        0x8d4545 gmscore::vector::GMSVectorTileRenderBin::Draw(gmscore::renderer::EntityRenderer*) + 87
12 Montana                        0x7e20a2 gmscore::renderer::EntityRenderer::Draw(bool) + 928
13 Montana                        0x8909b7 -[GMSPhoenixRenderer drawForced:] + 62
14 Montana                        0x870eca -[GMSEntityRendererView draw] + 406
15 Montana                        0x8c506e -[GMSVectorMapView draw] + 42
16 Montana                        0x86efed -[GMSEntityRendererView displayLinkFired:] + 45
17 Montana                        0x86cf2b -[GMSDisplayLink displayLinkFired:] + 529
18 QuartzCore                     0xe917 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 915
19 QuartzCore                     0x10daa6 display_timer_callback(__CFMachPort*, void*, long, void*) + 395
20 CoreFoundation                 0x4e8ae __CFMachPortPerform + 157
21 CoreFoundation                 0x82d99 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
22 CoreFoundation                 0x82140 __CFRunLoopDoSource1 + 617
23 CoreFoundation                 0x7c575 __CFRunLoopRun + 2420
24 CoreFoundation                 0x7b704 CFRunLoopRunSpecific + 562
25 GraphicsServices               0x3c8e GSEventRunModal + 139
26 UIKitCore                      0xcdb65a -[UIApplication _run] + 928
27 UIKitCore                      0xce02b5 UIApplicationMain + 101
28 libswiftUIKit.dylib            0x21cc2 UIApplicationMain(_:_:_:_:) + 98
29 Montana                        0x476be8 static UIApplicationDelegate.main() + 104 (<compiler-generated>:104)
30 Montana                        0x476b77 static AppDelegate.$main() + 39 (<compiler-generated>:39)
31 Montana                        0x47c5a8 main + 24 (<compiler-generated>:24)
32 ???                            0x10275cf21 (Missing)
33 ???                            0x10f87e4fe (Missing)
```

### Please check this screenshot for UIDebug from XCode, it looks like google maps have a runtime error.
![Screenshot 2022-05-31 at 1 14 00 PM](https://user-images.githubusercontent.com/69245102/171334058-d3e735ad-4d5d-4b3c-868b-163478d65701.png)

**Comment by eimantas** [comment]
+1

**Comment by VinayAzuga** [comment]
+1 
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1c20 objc_msgSend + 32
1  AppleMetalGLRenderer           0x7890 gldDestroyMemoryPlugin
2  GLEngine                       0x6bbd8 gleFreeOrphan
3  GLEngine                       0x6b80c gleCleanupOrphans
4  GLEngine                       0x6b6f8 gleOrphanBufferObject
5  GLEngine                       0x28b08 glDeleteBuffers_Exec
6  Azuga FleetMobile              0xadcae4 gmscore::renderer::GLState::RecoverResources() + 208
7  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
8  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
9  libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
10 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
11 CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12 CoreFoundation                 0x7c058 __CFRunLoopRun + 2036
13 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
14 GraphicsServices               0x1368 GSEventRunModal + 164
15 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
16 UIKitCore                      0x3a2034 UIApplicationMain + 340
17 APP              0x459954 main + 14 (main.m:14)

**Comment by wangela** [comment]
This appears to be obsolete per https://issuetracker.google.com/issues/224584852
