### ISSUE TITLE
GoogleMaps v 6.*.* with dark style blink white when navigating and loading map

### ISSUE THREAD

**Issue by olSolo** [googlemaps/google-maps-ios-utils#414]
I'm using GoogleMaps with dark style applied, and when moving the map or changing scale the not loaded piece blink white for a moment. If I turn off the Internet connection and move the map, I see that map is white with black labels in the not loaded areas. I tried different versions 6.*.*, including the latest one. Works fine with the same style on v 5.36

![Screenshot 2022-06-09 at 17 30 45](https://user-images.githubusercontent.com/4682149/172859430-a5aa014f-15db-4079-a7f8-89fc802384b4.png)

**Comment by wangela** [comment]
This appears to be a bug on the Maps SDK for iOS. If you are still experiencing it, please file it in the Issue Tracker for the Maps SDK for iOS at https://issuetracker.google.com/issues/new?component=188833&template=789005
