### ISSUE TITLE
Update Google Maps Dependency to 7.0.0-beta in Carthage

### ISSUE THREAD

**Issue by stherold** [googlemaps/google-maps-ios-utils#418]
Hey there,

I just wanted to know when the lib is ready to support Google Maps 7.0.0-beta and why it only supports Google Maps 6.0.1-Beta right now?

We established a fork which links to Google Maps 7.0.0-beta and it seems to work fine.

**Comment by Chanvannak52** [comment]
[]()

**Comment by wangela** [comment]
This is blocked by https://github.com/Carthage/Carthage/issues/3289.  We have submitted a PR with a fix but it has yet to be accepted by the Carthage project. Please consider engaging on the issue or https://github.com/Carthage/Carthage/pull/3290 to encourage the maintainers to prioritize.

**Comment by stherold** [comment]
There is already a PR open: https://github.com/Carthage/Carthage/pull/3290

Is that what you need?

**Comment by wangela** [comment]
Yes we submitted the PR but it's up to Carthage maintainers to approve and merge it. They have not merged it or many other PRs.

**Comment by wangela** [comment]
With no response from the Carthage maintainers in over 2 years and the consolidation of iOS dependencies to use Swift Package Manager, closing this issue as not planned.

**Comment by Blackjacx** [comment]
Perfect 👍 We already transitioned to SPM anyways 😃 

Good Job btw 🫶
