### ISSUE TITLE
Issue with Xcode Preview

### ISSUE THREAD

**Issue by dneykov** [googlemaps/google-maps-ios-utils#420]
Hi,

I'm having problems after adding this package in project. I'm using SwiftUI for part of my views but I'm not able to use the Xcode previews because of following error.

`SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600095ebb8a0):'GoogleMapsUtils'>)`

It happens when I try to resume the Preview. If I remove the package Previews are working again. Recently I updated to macOS Ventura but still same error.
The project build and run without any issue. I'm using clustering functionality from the package.
Is there something that I can try to fix that issue?

Thanks.

**Comment by wangela** [comment]
Please reopen if this is still an issue with the latest Xcode and latest version of this library.
