### ISSUE TITLE
[Question] Will you release e.g. 4.2.0 on cocoapods with latest commit regarding Apple Silicon support? 

### ISSUE THREAD

**Issue by lorenc-tomasz** [googlemaps/google-maps-ios-utils#437]
As on title, do you plan releasing new version with Apple Silicon support?

**Comment by aserdobintsev** [comment]
Looking forward to next release with changes regarding Apple Silicon support.
Definitely need this, especially because of Xcode 14.3 upcoming release.

**Comment by CyrilCermak** [comment]
That's exactly what I am doing, thank you @lorenc-tomasz. A version bump-up would be much better.

**Comment by zell180** [comment]
> You can use
> 
> ```
> pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :commit => '637954e5bcb2a879c11a6f2cead153a6bad5339f'
> ```
> 
> but it's not official release and doesn't look good on code review.

How and where i need to put this i Podfile? Thanks

**Comment by jcesarmobile** [comment]
We use it as a dependency in our Capacitor Google Maps plugin, so we can't do the Podfile trick since we declare the dependency in the .podspec and, as far as I know, you can't do the commit thing in the .podspec.
So a release would be very helpful.

**Comment by wangela** [comment]
[v4.2.0](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v4.2.0) is available now via CocoaPods and SPM.

**Comment by wangela** [comment]
Sorry, had some build and release issues. v4.2.2 should work.

**Comment by lorenc-tomasz** [comment]
Thank you for information.
