### ISSUE TITLE
using custom markers

### ISSUE THREAD

**Issue by yassinelmalyh** [googlemaps/google-maps-ios-utils#44]
please i need a full example to use custom markers "GMSMarker" with clustering , i'm not familar with objective c , i already tried to use https://github.com/googlemaps/google-maps-ios-utils/issues/21 but it doesn't work for me , please help!!

**Comment by mountainvat** [comment]
We have released a new version 1.1.x with easy marker customization. Please update your cocoapod or source files.
For more details see https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md

**Comment by mrsnax** [comment]
Hi,

How to use CustomMarkers in Swift ? Thank you
