### ISSUE TITLE
4.2.0 version not building cause of missing xframework file

### ISSUE THREAD

**Issue by corentios** [googlemaps/google-maps-ios-utils#445]
https://github.com/googlemaps/google-maps-ios-utils/blob/main/Package.swift

As you can here in the `Package.swift` file, we are getting a 404 because there is not xcframework file
`url: "https://github.com/googlemaps/google-maps-ios-utils/releases/download/v4.2.0/GoogleMapsUtils.xcframework.zip",`

So iOS project is not building.

Current fix is to stay in older version

**Comment by wangela** [comment]
Fixed the release workflow so please try again with 4.2.2 (fixed by #449)
