### ISSUE TITLE
TipKit: when adding popover tip to some view on top of GMSMapView tip starts flickering on every map move

### ISSUE THREAD

**Issue by yuliiaserdiuk** [googlemaps/google-maps-ios-utils#457]
To reproduce this issue you should add a popover tip using TipKit to some view on top of GMSMapView, when tip appears tap outside of the tip (for example on the map), tip is closed, but then on every move of the map tip appears again for few seconds with no ability to close it. It causes tip flickering.

**Comment by wangela** [comment]
This is a bug about the Maps SDK for iOS. If you are still experiencing it with the latest version of the Maps SDK, please file it in the Issue Tracker for the Maps SDK for iOS at https://issuetracker.google.com/issues/new?component=188833&template=789005
