### ISSUE TITLE
Invalid Bundle. The bundle Frameworks/GoogleMapsUtils.framework does not support the minimum OS Version specified in the Info.plist

### ISSUE THREAD

**Issue by salvatoreboemia** [googlemaps/google-maps-ios-utils#468]
Hi

do you know why I got this error?

- Xcode 15.3
- iOS min 16.4
- SPM google maps utils 4.2.2

Thanks

**Comment by serikabdirov** [comment]
Have you solved this problem?

**Comment by salvatoreboemia** [comment]
> Have you solved this problem?

Removed SPM and CocoaPods and imported as XCFramework

it's insane how a giant like Google has these ancient SDKs that aren't updated, don't support SPM, and create constant problems.

**Comment by serikabdirov** [comment]
I changed the xcode version to 15.2 and it fixed

**Comment by salvatoreboemia** [comment]
> I changed the xcode version to 15.2 and it fixed

I'm glad you solved it but it's not a fix, it's a workaround, due to Google's unwillingness to properly update these SDKs

**Comment by salvatoreboemia** [comment]
Goole, WAKE UP, please!!!!

**Comment by wangela** [comment]
Both the Maps SDK for iOS v9 and this [utility library v6](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v6.0.0) support a minimum of iOS 15. Please re-open if you still see this error after updating to google-maps-ios-utils v6.0.0. See the [README](https://github.com/googlemaps/google-maps-ios-utils?tab=readme-ov-file#swift-package-manager) for installation instructions.
