### ISSUE TITLE
GMUDefaultClusterRendererTest fails

### ISSUE THREAD

**Issue by sashok2k** [googlemaps/google-maps-ios-utils#47]
Was trying to understand why my code works not as expected and found issue with unit tests.
It seems to be issue with OCMock

Return value cannot be used for method; method signature declares '{?={?=dd}{?=dd}{?=dd}{?=dd}}' but value is '{?={CLLocationCoordinate2D=dd}{CLLocationCoordinate2D=dd}{CLLocationCoordinate2D=dd}{CLLocationCoordinate2D=dd}}

**Comment by mountainvat** [comment]
Which version of OCMock do you have? I cannot reproduce the issue on my end.

**Comment by sashok2k** [comment]
- OCMock (3.3.1)

**Comment by mountainvat** [comment]
It's interesting I also had 3.3.1. Which line in the GMUDefaultClusterRendererTest is that? Was it a compile error?

**Comment by sashok2k** [comment]
No, it occur during execution when code attempt to access visibleBounds of projection. Can give exact log later today

**Comment by sashok2k** [comment]
Here is full log http://pastebin.com/24L90vF1

**Comment by Petrachkov** [comment]
Hi there, I'm also facing the same issue. All the tests within GMUDefaultClusterRendererTest fail except for testShouldRenderAsClusterAtZoom. I do have the latest XCode and OCMock.

**Comment by sashok2k** [comment]
Any news on the issue? I'm sure issue is not on our side as I try on few other machines, result is always same. We use latest Xcode and latest SDK

**Comment by mountainvat** [comment]
I have been able to reproduce the issue with XCode 8 and OCMock 3.3.1. It seems OCMock does not allow stub method to return a struct in XCode 8.
If these tests are blocking your development on XCode 8, you can comment them out until we find a solution.

**Comment by julia-godoy** [comment]
Hello, I'm having a similar issue, also using XCode 8 and OCMock 3.3.1. But I found it curious that the test passes when I use the simulator on iOS 10, but the problem with the stub method appears when I use iOS 9.3.
Any updates on the issue?
