### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by Rexios80** [googlemaps/google-maps-ios-utils#472]
The last release was over a year ago now. What is going on? There are several blocking issues that have yet to be resolved and are necessary for other projects. Can we get a statement on the status of this repo?

**Comment by salvatoreboemia** [comment]
Google WEAK UP!!!

**Comment by lluisgerard** [comment]
It does seem abandoned, it would be nice to know what's going on internally at Google because this is getting ridiculous.

**Comment by patrickcapadmi** [comment]
I've reached out to Google sales and technical support on this today.

Sales pointed me to support and all support have done is point out that this is an open source library so it isn't supported at all. 

> I understand that this is very important to you and that you would like to receive a solution to this issue. However, the Utility Library is an open-source library, and while this is not stated clearly in our documentation and we have it documented, this library is not supported by the Google Maps Platform Technical support team.

https://github.com/googlemaps/google-maps-ios-utils?tab=readme-ov-file#support

Overall not a helpful response from Google. I've also asked previously about this on the Google Maps Discord to no avail. Not quite sure what to do but I might just investigate if we can extract the parts of this SDK we use and abandon the rest.

#abandonware

**Comment by Rexios80** [comment]
Are the web and Android equivalents of this still maintained? How can they abandon one platform but not the others? Or are the web and Android versions just more resilient to code rot?

**Comment by wangela** [comment]
Hi folks, I'm responsible for maintaining this library. I share in your frustration and wish the fix were simple enough to have gotten a new release out by now. Please see #473 for the challenges, current status, and roadmap.
