### ISSUE TITLE
Google-maps-ios-utils: Could not resolve package dependencies

### ISSUE THREAD

**Issue by carloshpdoc** [googlemaps/google-maps-ios-utils#478]
Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  I'm trying to generate a release of my app and I'm using google maps ios utils. However, I was presented with this error. I was wondering if the branch would now be wangela/release-please?

#### Code example

```
Package.remote(
            url: "https://github.com/googlemaps/google-maps-ios-utils.git",
            requirement: .branch("wangela/8-0-0")
        ),
```

#### Stack trace
```
Resolving package dependencies using xcodebuild
2024-07-30 21:45:42.177 xcodebuild[94670:128725] Writing error result bundle to /var/folders/7l/rszmbrmd6tv4pg52z6ql_5rc0000gn/T/ResultBundle_2024-30-07_21-45-0042.xcresult
xcodebuild: error: Could not resolve package dependencies:
  could not find a branch named ‘wangela/8-0-0’ in https://github.com/googlemaps/google-maps-ios-utils.git
The 'xcodebuild' command exited with error code 74 and message:
2024-07-30 21:45:42.177 xcodebuild[94670:128725] Writing error result bundle to /var/folders/7l/rszmbrmd6tv4pg52z6ql_5rc0000gn/T/ResultBundle_2024-30-07_21-45-0042.xcresult
xcodebuild: error: Could not resolve package dependencies:
  could not find a branch named ‘wangela/8-0-0’ in https://github.com/googlemaps/google-maps-ios-utils.git
```

Thanks!

**Comment by jcesarmobile** [comment]
wangela/8-0-0 was deleted once the PR was merged, you might want to use main branch until there is a final release

**Comment by carloshpdoc** [comment]
I put this master branch, and now I have this issue. 

`Modules/Map/MapViewController.swift:4:8: failed to build module 'GoogleMapsUtils'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.
`

And back to my swift version, I think that's no good.

**Comment by carloshpdoc** [comment]
I did find the same issue here: https://github.com/googlemaps/google-maps-ios-utils/issues/458.
