### ISSUE TITLE
Latest compatible versions of Maps and Utils SDK which supports iOS 14 and iOS 15

### ISSUE THREAD

**Issue by harikrishnank333** [googlemaps/google-maps-ios-utils#493]
Hi,

Currently our project has Google Maps (8.2.0) and Google Maps utils (4.1.0). But If I update the pods the map is not loading. Current minimum deployment target is iOS 14. We are planning to update the same to iOS 15 in next few days.

A few queries regarding the compatibility:

- Can you please let me know the latest COMPATIBLE version is Google Maps SDK and Google Maps Utils SDK which supports:
-  minimum deployment target of  iOS 14
- minimum deployment target of  iOS 15

Thank you.

**Comment by wangela** [comment]
**For apps that support a minimum of iOS 14**, use [Maps SDK for iOS v8.x](https://developers.google.com/maps/documentation/ios-sdk/release-notes#May_17_2023) with [Utility Library v5.0.0](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v5.0.0).

**For apps that support a minimum of iOS 15**, use [Maps SDK for iOS v9.x](https://developers.google.com/maps/documentation/ios-sdk/release-notes#May_28_2024) with [Utility Library v6.0.0](https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v6.0.0).

Bear in mind our guidance for [specifying versions](https://developers.google.com/maps/documentation/ios-sdk/versions) in your dependencies and the Google Maps Platform [SDK support policy](https://developers.google.com/maps/software-support#sdk-support).
