### ISSUE TITLE
Is this project abandonded? Its way behind than android

### ISSUE THREAD

**Issue by dkati** [googlemaps/google-maps-ios-utils#510]
Good evening. whats going on? Noone care around?

- KMZ is still not supported
- With KML renderer you cant access the overlays in order to implement click listeners to show data from kml

Its reaaaaaally behind android. whats going on?
Is there another version or utility around for ios?

**Comment by wangela** [comment]
As explained in the status and roadmap #473, we've had to do some foundation upgrades to this library for the past year+. Our current focus is to translate it all to Swift to make it more maintainable and to make it easier for the community to contribute.

The feature request (#395) and bug (#397) you listed have been prioritized as P3 based on the number of upvotes and comments.  Features and bugfixes are prioritized by triage of GitHub issues. We identify top issues that matter to you by upvoting as counted by comments and 👍 reactions to intial comment (these are the metrics that we're able to sort by in the GitHub browser UI). If you would like to see these completed sooner, please know that [contributions are welcome](https://github.com/googlemaps/google-maps-ios-utils/blob/main/CONTRIBUTING.md).
