### ISSUE TITLE
Algo/GMUClusterAlgorithm.h not found

### ISSUE THREAD

**Issue by matl89** [googlemaps/google-maps-ios-utils#52]
Hi there,

I just updated the pod to use the new marker icons, but I get a file not found error for Algo/GMUClusterAlgorithm.h in the GMUClusterManager.h file. 

My code is like it is in the example file.

Do you know what could be wrong?

**Comment by mountainvat** [comment]
Thanks for spotting this. We have pushed out a new fix so please update your pod.
