### ISSUE TITLE
Google Maps for Xcode 8

### ISSUE THREAD

**Issue by dtnguy72** [googlemaps/google-maps-ios-utils#54]
Hello,

Is there an updated version for the latest Swift 3 update?

**Comment by domesticmouse** [comment]
I'm confused, both Google Maps SDK for iOS, and this support library should work fine in Xcode 8 with Swift 3. What issues are you seeing?

**Comment by mountainvat** [comment]
Yes as of 2.0.0, demo samples have been upgraded to Swift 3 syntax.
