### ISSUE TITLE
Marker Customization Swift

### ISSUE THREAD

**Issue by jaimevz27** [googlemaps/google-maps-ios-utils#55]
Hello,  I'm trying to implement Marker Customization described here ->[https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md](url) where explains how to implement in objective C.  My project uses swift and my knowlegde in objective C is very low.  I've tried to convert the example to swift, but the project doesn't build, trhows an error (see attatchment). With this message i've sent 2 files, an image with the error, and a file with a  partial example of my code.  is there an issue with my code or something else? Thanks in advance. 

P.D. 
When i implement Clustering without custom markers everything works fine.
i'm using swift 2.3,  cocoapods with static libraries (using bridge header file)
Google-Maps-iOS-Utils (1.1.2), GoogleMaps (2.1.0), and xcode Version 8.0 (8A218a).
![error-swift-marker-custom](https://cloud.githubusercontent.com/assets/10619595/19392277/bf1f7d52-91f5-11e6-87f5-34f2d5cfc10d.jpg)
[example_swift_test.txt](https://github.com/googlemaps/google-maps-ios-utils/files/529827/example_swift_test.txt)
[POIItemClass.txt](https://github.com/googlemaps/google-maps-ios-utils/files/529837/POIItemClass.txt)

**Comment by domesticmouse** [comment]
Any chance of getting a minimal reproduction case uploaded a Github repo so that I can checkout your code and figure out what is going wrong?
