### ISSUE TITLE
Use of undeclared type 'GMUClusterManagerDelegate'

### ISSUE THREAD

**Issue by dayangxiang** [googlemaps/google-maps-ios-utils#56]
I followed the steps in Swift.md to manually add Google-Maps-iOS-Utils files to my project. And it succeeded in building. But when I try to get a view controller implement GMUClusterManagerDelegate, an error shows

> Use of undeclared type 'GMUClusterManagerDelegate'

Here are my screen shots -
- Bridging Header

<img width="299" alt="screen shot 2016-10-27 at 22 14 40" src="https://cloud.githubusercontent.com/assets/14340214/19793565/d14909c4-9c92-11e6-9d96-03424d6c9a29.png">
- GMUMarkerClustering.h

<img width="463" alt="screen shot 2016-10-27 at 22 15 36" src="https://cloud.githubusercontent.com/assets/14340214/19793607/ee921110-9c92-11e6-86ce-97ef6d0656c1.png">
- Group

<img width="230" alt="screen shot 2016-10-27 at 22 16 28" src="https://cloud.githubusercontent.com/assets/14340214/19793626/0d623778-9c93-11e6-9d18-8380527d52e7.png">
- Use Header Maps

<img width="476" alt="screen shot 2016-10-27 at 22 22 29" src="https://cloud.githubusercontent.com/assets/14340214/19793788/f8dad07a-9c93-11e6-90e3-f3314b619d18.png">

Can anyone help me with this? Thanks a lot!

**Comment by klwoon** [comment]
Can you try to add the header in Build Settings, such as:

![screen shot 2016-10-28 at 6 34 18 pm](https://cloud.githubusercontent.com/assets/9354867/19803808/54c213cc-9d3d-11e6-8252-47f5909d873f.png)

**Comment by dayangxiang** [comment]
@klwoon Yeah I have it

![screen shot 2016-10-28 at 13 43 12](https://cloud.githubusercontent.com/assets/14340214/19818318/ea4fc1ba-9d14-11e6-8a23-312235af1779.png)

**Comment by dayangxiang** [comment]
Solved. Something wrong happened to the path of my bridging header.
