### ISSUE TITLE
Collection was mutated while being enumerated

### ISSUE THREAD

**Issue by danartinho** [googlemaps/google-maps-ios-utils#57]
I am developing an app that show users in nearby area in the maps. I use cluster manager to cluster users. The users/cluster items are updated periodically from server. Steps are : 
- call [clusterManager clearItems]
- add all new item to the cluster manager
- call [clusterManager cluster]

But sometimes I got error : `Collection was mutated while being enumerated` in `GMUNonHierarchicalDistanceBasedAlgorithm.m`, particularly in this place : 

    /**
     * Returns the set of clusters of the added items.
     */
    - (NSArray<id<GMUCluster>> *)clustersAtZoom:(float)zoom {
      NSMutableArray<id<GMUCluster>> *clusters = [[NSMutableArray alloc] init];
      NSMutableDictionary<GMUWrappingDictionaryKey *, id<GMUCluster>> *itemToClusterMap =
          [[NSMutableDictionary alloc] init];
      NSMutableDictionary<GMUWrappingDictionaryKey *, NSNumber *>     *itemToClusterDistanceMap =
          [[NSMutableDictionary alloc] init];
      NSMutableSet<id<GMUClusterItem>> *processedItems = [[NSMutableSet alloc] init];

      for (id<GMUClusterItem> item in _items) {  <--- HERE
      ....    

Any advice how to prevent this error from occurring?

**Comment by domesticmouse** [comment]
Any chance of a minimal reproduction case that demonstrates the issue?

**Comment by domesticmouse** [comment]
Closing this out as stale. Please re-open when you have uploaded a minimal reproduction sample to a GitHub repo that I can checkout and use to debug what is going wrong, and verifying a fix. Thanks!

**Comment by dneykov** [comment]
I'm facing same issue but cannot reproduce it all the time. It happens sometimes as mentioned in the initial question. @danartinho did you manage to prevent it somehow?
