### ISSUE TITLE
Heat map request.

### ISSUE THREAD

**Issue by mdabrarniyazi** [googlemaps/google-maps-ios-utils#59]
Why there is no heat map utility for iOS like Android? Or is it there and I could not find it!

**Comment by mountainvat** [comment]
We haven't got around to add this feature. Are you interested in contributing?

**Comment by mdabrarniyazi** [comment]
@mountainvat I would love to contribute but I think I am not sophisticated enough to do right now. I have just started coding for iOS and that too in Swift. So I have no knowledge of Objective-C. 
It would be big help if somehow you could get this feature done in iOS because it is very important for my app. 

Thanks.

**Comment by mountainvat** [comment]
We will keep this thread updated once we've managed to deliver the feature.
Thanks for the interest.

**Comment by yozef** [comment]
+1

**Comment by minhvn** [comment]
@mountainvat  Hi aSon, this ext support to heatmaps layer?
Thank you very much.

**Comment by mountainvat** [comment]
Hi @minhvn , heatmap is still on our to do list. You are welcome to contribute to the library if you wish.

**Comment by minhvn** [comment]
Hi a Son,
If I can, i will do it.. But i cannot :( i hope it will avaliable soon
Thank aSon.

**Comment by domesticmouse** [comment]
To appropriately manage expectations, we are not currently working on a Heat Map feature for Google Maps iOS Utility library. We are, however, open to pull requests from the community. 

Thanks!

**Comment by sam2x** [comment]
Hey, there is maybe a solution about this. To be concise, it's about fundrasing it. I referenced this issue (see above mention, I dont want to crosslink issue). 

Discussions has started, and author of cordova-plugin-googlemaps may do it for 1k$ (him or someone else).If you are also interested, or just wants to give your point of view, please join the discussion. 

More we'll be, more we will understand the underlying requirements necessary to solve this.
Thanks.

**Comment by domesticmouse** [comment]
Actually, I spoke too soon. I don't think we will need to fund raise this specific feature at this point. Thanks!

**Comment by aedemo** [comment]
please provide heat map for IOS. :)

**Comment by domesticmouse** [comment]
We have just released v2.1.0 that now includes Heatmap support. =)

**Comment by minhvn** [comment]
Bravo team :)
