### ISSUE TITLE
Google Maps SDK for iOS Utility Library crashing issue

### ISSUE THREAD

**Issue by nitisha1** [googlemaps/google-maps-ios-utils#60]
i've implemented marker clustering(Google Maps SDK for iOS Utility Library ) along with google maps.crash i'm getting is on deallocating cluster manager object.i'm deallocating google map and cluster manager objects and delegate in viewDidDisappear and deinit as i'm initialising it in viewDidLoad.it works fine upto 10.0,but for higher when i'm doing same in deinit it's working fine but crashes in lower version.below is my code                                                               
 
  
```
deinit{
        print("DEINIT")
      
        if(googleMapView != nil){
            googleMapView!.removeObserver(self, forKeyPath: "myLocation")
        }
        if(clusterManager != nil)
        {
            clusterManager.clearItems()
            clusterManager.setDelegate(nil, mapDelegate: nil)
            clusterManager = nil
        }
    }`
```

**Comment by mountainvat** [comment]
Can you please list the iOS sdk & XCode versions here. And also do you have a stack trace of the crash?

**Comment by nitisha1** [comment]
ios version - 10.1.1
xcode version - 8.0

error throws when not deallocating cluster Manager objects and delegates in deinit method.
 
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fd7c5b14770 of class GMSMapView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000023bf00> (
<NSKeyValueObservance 0x600000455150: Observer: 0x600000465580, Key path: camera, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x6000004549a0>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010799f34b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010740021e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107a08265 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000106f36451 NSKVODeallocate + 293
	4   TabletPLUS                          0x00000001040a39c7 _TToFC10TabletPLUS25PropertyListingControllerE + 423
	5   libobjc.A.dylib                     0x00000001073fea0a _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	6   libobjc.A.dylib                     0x000000010740a4de objc_destructInstance + 129
	7   libobjc.A.dylib                     0x000000010740a510 object_dispose + 22
	8   UIKit                               0x000000010827ba72 -[UIResponder dealloc] + 146
	9   UIKit                               0x0000000108202cc9 -[UIViewController dealloc] + 1920
	10  TabletPLUS                          0x00000001040a37e6 _TFC10TabletPLUS25PropertyListingControllerD + 646
	11  TabletPLUS                          0x00000001040a3812 _TToFC10TabletPLUS25PropertyListingControllerD + 34
	12  TabletPLUS                          0x00000001040a9675 _TMaCSo14GMSMutablePath + 117
	13  TabletPLUS                          0x000000010408da18 _TFFC10TabletPLUS25PropertyListingController5delayFT7secondsSd10completionFT_T__T_U_FT_T_ + 88
	14  TabletPLUS                          0x000000010408dacd block_destroy_helper.77 + 13
	15  libsystem_blocks.dylib              0x000000010ae34952 _Block_release + 102
	16  libdispatch.dylib                   0x000000010ad98ea4 _dispatch_source_handler_dispose + 23
	17  libdispatch.dylib                   0x000000010ad9b218 _dispatch_source_latch_and_call + 249
	18  libdispatch.dylib                   0x000000010ad93d7d _dispatch_source_invoke + 1098
	19  libdispatch.dylib                   0x000000010ad8ab2e _dispatch_main_queue_callback_4CF + 1006
	20  CoreFoundation                      0x00000001079634f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	21  CoreFoundation                      0x0000000107928f8d __CFRunLoopRun + 2205
	22  CoreFoundation                      0x0000000107928494 CFRunLoopRunSpecific + 420
	23  GraphicsServices                    0x000000010d646a6f GSEventRunModal + 161
	24  UIKit                               0x0000000108064f34 UIApplicationMain + 159
	25  TabletPLUS                          0x00000001040bf23f main + 111
	26  libdyld.dylib                       0x000000010adf668d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

same error throws when deallocating clustermanager object and delegates in Deinit below ios 10.0.(xcode 7.3.1).
 Please suggest solution

**Comment by domesticmouse** [comment]
If this is still an issue, please re-open with a link to a minimal reproduction case.
