### ISSUE TITLE
Duplicated markers in to clusters

### ISSUE THREAD

**Issue by alejandrorbradford** [googlemaps/google-maps-ios-utils#61]
Looks like its adding the same location to a cluster when a zoom event happens. Do you know anything about this?

**Comment by mountainvat** [comment]
No we've never seen this unless the 2 markers have the same location. Do you have a reproduction case?

**Comment by SAPIENTechnologies** [comment]
Is this the same issue as https://github.com/googlemaps/google-maps-ios-utils/issues/58?

**Comment by SAPIENTechnologies** [comment]
Has the source of this issue been determined?

**Comment by domesticmouse** [comment]
Closing this issue out as stale. Please re-open with a link to a minimal reproduction case if this is still an issue.
