### ISSUE TITLE
Clustering Marker Customization Swift compile error

### ISSUE THREAD

**Issue by leonardom790** [googlemaps/google-maps-ios-utils#64]
When I try to make a class extended from GMUDefaultClusterRenderer, the compiler give me this error. 

Can someone help me please? or any idea why this happen?

![captura de pantalla 2016-12-22 a la s 16 46 20](https://cloud.githubusercontent.com/assets/22015397/21442853/60f65f50-c866-11e6-9717-db3977c06766.png)
![captura de pantalla 2016-12-22 a la s 16 45 57](https://cloud.githubusercontent.com/assets/22015397/21442852/60f65ba4-c866-11e6-9384-f02ad39cc48c.png)

**Comment by mountainvat** [comment]
Can you publish a repro project that we can take a look at?

**Comment by domesticmouse** [comment]
Closing this out as stale.
