### ISSUE TITLE
Asynchronous Cluster Icon Rendering 

### ISSUE THREAD

**Issue by hyd00** [googlemaps/google-maps-ios-utils#65]
According to [this example](https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md) I have successfully implemented custom icons in marker clustering, and also managed to do it _Asynchronously_. 

However, while the images are being downloaded/rendered, the **default Pink Google Map marker** is displayed for single markers, and a **Round Blue Color with Item Count icon** for cluster marker, respectively. 

**I do not want to show any default icon, and just want to show the custom icon, whenever they are ready.** 

Please help. Thanks.

**Comment by hyd00** [comment]
Found the solution. Just add an `else` in `GMUDefaultClusterRenderer.m`  as follows

`- (GMSMarker *)markerWithPosition:(CLLocationCoordinate2D)position
                             from:(CLLocationCoordinate2D)from
                         userData:(id)userData
                      clusterIcon:(UIImage *)clusterIcon
                         animated:(BOOL)animated {
  GMSMarker *marker = [self markerForObject:userData];
  CLLocationCoordinate2D initialPosition = animated ? from : position;
  marker.position = initialPosition;
  marker.userData = userData;
  if (clusterIcon != nil) {
    marker.icon = clusterIcon;
    marker.groundAnchor = CGPointMake(0.5, 0.5);
  }
  marker.zIndex = _zIndex;

  if ([_delegate respondsToSelector:@selector(renderer:willRenderMarker:)]) {
    [_delegate renderer:self willRenderMarker:marker];
  }
  else //added ELSE to not show any default marker unitl custom images have loaded, if delegate is persent.
      marker.map = _mapView;

  if (animated) {
    [CATransaction begin];
    [CATransaction setAnimationDuration:kGMUAnimationDuration];
    marker.layer.latitude = position.latitude;
    marker.layer.longitude = position.longitude;
    [CATransaction commit];
  }

  if ([_delegate respondsToSelector:@selector(renderer:didRenderMarker:)]) {
    [_delegate renderer:self didRenderMarker:marker];
  }
  return marker;
}`

and then do `marker.map = mapView` in your implementation of `- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker`

**Comment by mountainvat** [comment]
Either that or I can suggest having a fully transparent icon at the start (instead of the default icon) and then swap with the mashed up image once they are downloaded and computed (notes: remember to post to main thread when assigning icon).

Alternatively you can set the marker.map to nil in the ```renderer:didRenderMarker:``` delegate so you do not need to modify the ```GMUDefaultClusterRenderer.m``` to avoid future upgrade issues.
