### ISSUE TITLE
Google Maps SDK CoreData crashing issue

### ISSUE THREAD

**Issue by vinaykmr889** [googlemaps/google-maps-ios-utils#68]
@mountainvat 

ios version - 9.0
xcode version - 8.2

I am getting below crash when i am implementing Google map in my iOS project. I am using coredata also in my application. Can you plz give me some quick resolution for this? Please find the error and stack trace below:-

[error] error: The current thread is not the recognized owner of this NSManagedObjectContext(0x6080001d86f0).  Illegal access during objectRegisteredForID:
CoreData: error: The current thread is not the recognized owner of this NSManagedObjectContext(0x6080001d86f0).  Illegal access during objectRegisteredForID:
(lldb) bt
* thread #17: tid = 0x588886, 0x0000000107e66224 CoreData`+[NSManagedObjectContext __Multithreading_Violation_AllThatIsLeftToUsIsHonor__] + 4, queue = 'SQLQueue 0x7f8f26d33740 for Objects.sqlite', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x0000000107e66224 CoreData`+[NSManagedObjectContext __Multithreading_Violation_AllThatIsLeftToUsIsHonor__] + 4
    frame #1: 0x0000000107e66625 CoreData`_PFAssertSafeMultiThreadedAccess_impl + 645
    frame #2: 0x0000000107de5388 CoreData`-[NSManagedObjectContext objectRegisteredForID:] + 328
    frame #3: 0x0000000107ee45ab CoreData`-[NSSQLiteConnection updateRow:forRequestContext:] + 171
    frame #4: 0x0000000107f8c0fb CoreData`_writeChangesForSaveRequest + 2059
    frame #5: 0x0000000107f8d963 CoreData`_executeSaveChangesRequest + 291
    frame #6: 0x0000000107e1a856 CoreData`-[NSSQLSaveChangesRequestContext executeRequestUsingConnection:] + 38
    frame #7: 0x0000000107f33257 CoreData`__52-[NSSQLDefaultConnectionManager handleStoreRequest:]_block_invoke + 215
    frame #8: 0x000000010de8b0cd libdispatch.dylib`_dispatch_client_callout + 8
    frame #9: 0x000000010de682b6 libdispatch.dylib`_dispatch_barrier_sync_f_invoke + 340
    frame #10: 0x0000000107f3312c CoreData`-[NSSQLDefaultConnectionManager handleStoreRequest:] + 236
    frame #11: 0x0000000107f3a9bf CoreData`-[NSSQLCoreDispatchManager routeStoreRequest:] + 351
    frame #12: 0x0000000107ebb5c9 CoreData`-[NSSQLCore dispatchRequest:withRetries:] + 233
    frame #13: 0x0000000107eb7e7f CoreData`-[NSSQLCore processSaveChanges:forContext:] + 191
    frame #14: 0x0000000107dad88d CoreData`-[NSSQLCore executeRequest:withContext:error:] + 909
    frame #15: 0x0000000107ea2be9 CoreData`__65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke + 4169
    frame #16: 0x0000000107e9ac26 CoreData`-[NSPersistentStoreCoordinator _routeHeavyweightBlock:] + 390
    frame #17: 0x0000000107dad2be CoreData`-[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 654
    frame #18: 0x0000000107dd75ba CoreData`-[NSManagedObjectContext save:] + 3706
    frame #19: 0x000000010539a2f8 Owners.com`__72-[GMSObjectDataCache storeObjectNamesAndData:version:completionHandler:]_block_invoke + 400
    frame #20: 0x000000010de61978 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #21: 0x000000010de8b0cd libdispatch.dylib`_dispatch_client_callout + 8
    frame #22: 0x000000010de68f64 libdispatch.dylib`_dispatch_queue_serial_drain + 569
    frame #23: 0x000000010de69b4b libdispatch.dylib`_dispatch_queue_invoke + 1073
    frame #24: 0x000000010de6a02b libdispatch.dylib`_dispatch_queue_override_invoke + 683
    frame #25: 0x000000010de6c385 libdispatch.dylib`_dispatch_root_queue_drain + 720
    frame #26: 0x000000010de6c059 libdispatch.dylib`_dispatch_worker_thread3 + 123
    frame #27: 0x000000010e235736 libsystem_pthread.dylib`_pthread_wqthread + 1299
    frame #28: 0x000000010e235211 libsystem_pthread.dylib`start_wqthread + 13
(lldb)

**Comment by mountainvat** [comment]
Please raise this issue against the Google Maps SDK issue tracker 👍 

https://code.google.com/p/gmaps-api-issues/issues/entry?template=Maps%20SDK%20for%20iOS%20-%20Bug

**Comment by thomascalmon** [comment]
Still doens't work?

**Comment by domesticmouse** [comment]
The above error is not from this utility library, but instead from the underlying Google Maps SDK for iOS. Please raise an issue regarding this error on the bug tracker mentioned by @mountainvat so we can verify and track a fix. Thanks!
