### ISSUE TITLE
Customise GMUClusterItem to set custom icon

### ISSUE THREAD

**Issue by bharatmodi777** [googlemaps/google-maps-ios-utils#70]
I could not able to set custom icon for the GMUClusterItem (Marker) when i use google-maps-ios-utils library. I have to show different icon on GMUClusterItem based on the category selected by the user. Even i want to show two GMUClusterItem having different icons at the same time. I want to achieve this - 

![screen shot 2017-01-10 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/16378093/21796414/b2437c54-d72e-11e6-9825-9cf817a539ef.png)

**Comment by mountainvat** [comment]
@bharatmodi777 please take a look at this example: https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md

**Comment by bharatmodi777** [comment]
@mountainvat Thanks for your quick reply, i have added google-maps-ios-utils using pods. I have seen the example you have given in the link above but to do this do i need to added/modify classes manually? Because there are differences in the class GMUDefaultClusterRenderer in the Pods clustering folder and the downloaded google-maps-ios-utils library. Please suggest.

**Comment by mountainvat** [comment]
Did your pod file reference the latest version 1.1.2?

**Comment by bharatmodi777** [comment]
pod --version
1.1.1

I have installed the latest version of google-maps-ios-utils using 
pod 'Google-Maps-iOS-Utils'

**Comment by mountainvat** [comment]
Do you use a Podfile? What does it look like? Maybe try pod update?

**Comment by bharatmodi777** [comment]
Yes i am using Podfile, you can see the attached screen shot to get a look of it. Tried pod update but nothing improved. 
![screen shot 2017-01-17 at 12 00 26 pm](https://cloud.githubusercontent.com/assets/16378093/22010174/a3176c0c-dcad-11e6-8ae1-ac2ec2148d3c.png)

**Comment by bharatmodi777** [comment]
Also i have downloaded the same google-maps-ios-utils library manually for reference/sample app which has one sample app named 'GoogleMapsUtils'. In this project the Cluster classes are added manually and not using the Podfile. So do i need to integrate the google-maps-ios-utils library manually (i mean without using Podfile)? Kindly suggest.

**Comment by mountainvat** [comment]
If you are adding the files manually please remove the pod reference and use files from this specific release: https://github.com/googlemaps/google-maps-ios-utils/releases/tag/v1.1.2

Please let us know how you go.

**Comment by bharatmodi777** [comment]
Will update you shortly.

**Comment by yaronj3** [comment]
I just did it and everything works fine,
Thanks
