### ISSUE TITLE
Hiding and showing markers in a cluster in iOS

### ISSUE THREAD

**Issue by frios** [googlemaps/google-maps-ios-utils#71]
I am trying to quickly hide then show markers that are controlled by the clusterManager. Before I implemented the clusterManager, I would set the marker.map to nil then set it to my gmsMapView. This had the effect of "flashing" the marker which is what I was looking to do.

Now I have implemented the cluster manager. Since I cannot get direct access to the _items collection in the clusterManager, I keep a shadow copy of all of the items I add to the clusterManager. I assume that these items are added by reference?

I use the following code to "flash" my markers:

```
   func highlightMarker () {
        let markerCount = mapViewController.markers.count

        if firstTimeThrough { //randomize
            currentMarkerIndex = Int(arc4random_uniform(UInt32(markerCount - 1)))
            firstTimeThrough = false
        }
        if currentMarkerIndex == markerCount - 1 { 
            currentMarkerIndex = 0
        } else {
            currentMarkerIndex += 1
        }
        let highlightedMarker = mapViewController.markers[currentMarkerIndex]
        
         highlightedMarker.map = nil
         highlightedMarker.map = gmsMapView
        }
    }
```

But I don't get the markers to "flash" anymore. I have tried to call             mapViewController.clusterManager.cluster() after setting the map to nil and after setting the map back, but still no "flashing".

Any ideas on how best to achieve this effect?

**Comment by mountainvat** [comment]
I suspect your mapViewController.markers collection are not the same as the ones created by the cluster manager. How did you populate the mapViewController.markers collection?

**Comment by frios** [comment]
They are. I solved the problem by changing the removing and adding of the map to:

```
        DispatchQueue.main.async {
            self.hideMarker (marker : highlightedMarker)
            self.perform(#selector(self.showMarker), with : highlightedMarker, afterDelay: 0.1)
        }
    }
    
    func hideMarker (marker : GMSMarker) {
        marker.iconView?.alpha = 0.00
    }
    
    func showMarker (marker : Any?) {
        (marker as! GMSMarker).iconView?.alpha = 1.00
    }

```
