### ISSUE TITLE
Showing cluster item count on customized cluster marker icon

### ISSUE THREAD

**Issue by jhhomme** [googlemaps/google-maps-ios-utils#72]
Hi, is it possible to show the cluster count on a customized cluster marker icon?

The cluster count is not showing anymore after implementing customized cluster marker icon.

**Comment by jhhomme** [comment]
Also, in willRenderMarker, is there any way to identify which clustermanager the marker belongs to? I would like to render different cluster icons for different clustermanagers.

**Comment by mountainvat** [comment]
You would have to generate a custom icon with your icon + the number of items. You could use the drawing logic we have in the ```GMUDefaultClusterIconGenerator```.

As to knowing which cluster manager is associated with the willRenderMarker even you would have to manage that association yourself either by a mapping from the renderer to a cluster manager (meaning having 1 renderer per manager) or a mapping from a marker's userData to the cluster manager.

**Comment by tamhuynh-asnet** [comment]
I has seem issue when i use willRenderMarker to custom clustor icons but i can't see the  icon + the number of items.

**Comment by tamhuynh-asnet** [comment]
I had generel a custom icon by `GMUDefaultClusterIconGenerator(buckets: [ 100, 500, 1000, 2000, 5000], backgroundImages: images)`. Please help me on this. I'm using Swift language
<img width="281" alt="glass" src="https://cloud.githubusercontent.com/assets/12997798/22176147/1e9101a0-e036-11e6-9a26-368264552e16.png">

**Comment by mountainvat** [comment]
They seem to be single item or are they supposed to be a cluster?

**Comment by tamhuynh-asnet** [comment]
I resolved this issue. I set cluster icon be empty so showing the default icon. Thanks.

**Comment by grundmanise** [comment]
@mountainvat Hello, can't one just cast `marker.userData as! GMUCluster` like this:
```
func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
 let foo = marker.userData as! GMUCluster
 foo.count
}
```
 and get `.count` from there? Is it too expensive performance wise?

**Comment by mountainvat** [comment]
That is not expensive and seems reasonable. Beware that the marker.userData can also be a GMUClusterItem so maybe use `let foo = marker.userData as? GMUCluster` and check that foo is not nil.

**Comment by grundmanise** [comment]
@mountainvat yes, I actually have `if else` type checking implemented there. I truncated code for brevity. Thanks.

**Comment by domesticmouse** [comment]
Closing this issue out as it seems resolved. Please re-open if this isn't the case. Thanks!

**Comment by kalpeshjjethva** [comment]
I am using the POIItem() as nsobject but how can i store data? and how can i get the data? from the tap on cluseter.

**Comment by miragessee** [comment]
@kalpeshjjethva 

```
if let foo = marker.userData as? GMUCluster {
            NSLog("Did tap a gmucluster ")
            print(foo.items)
            
            for index in foo.items
            {
                let poiItem = index as? POIItem
                print(poiItem?.name)
            }
```

**Comment by amitbacd** [comment]
if any one have demo of this point please share with me...

thanks in advance.
