### ISSUE TITLE
GMUNonHierarchicalDistanceBasedAlgorithm doesn't make clusters for items with equal coordinates

### ISSUE THREAD

**Issue by SergeyCHiP** [googlemaps/google-maps-ios-utils#77]
If there are items with equal coordinates on map it seems like one ItemMarker... I think, it should look like clusters.

**Comment by CristianCardosoA** [comment]
Hi, you have to modify the constant: static const NSUInteger kGMUMinClusterSize = 2; 

Located in file: GMUDefaultClusterRenderer
