### ISSUE TITLE
I have to do clustering according to the CGPoint (x,y) along non mapping view, is it possible in iOS ?

### ISSUE THREAD

**Issue by Tamil-Arya** [googlemaps/google-maps-ios-utils#78]
I need to do pagination in the CATileLayer ( Blue print Map ) by ScrollView. 

Scenario : I implemented blue print using CATileLayer as Map for pointing particular location as well saving those data into the CouchDB. Now i have pointed more number of locations ( ex : 1000 location ) so now for this blue print i need to do pagination. is it possible to do by Google clustering ?

More info : http://stackoverflow.com/questions/42008564/in-objective-c-how-to-do-clustering-with-pagination-using-catilelayer

**Comment by domesticmouse** [comment]
I'm guessing you aren't using Google Maps SDK for iOS, so I don't think this support library is helpful as is. However, this library is open source, so you may be able to utilise the code from the library to help implement what you need. Thanks!
