### ISSUE TITLE
Create a best path process for using Google Maps iOS Utils with Swift

### ISSUE THREAD

**Issue by SAPIENTechnologies** [googlemaps/google-maps-ios-utils#86]
Used the instructions here 

https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md 

to set up project but compiler can't find the GMUMarkerClustering header. Any suggestions?

**Comment by accurate** [comment]
I can't seem to be able to get the instructions to work either. It's not specific either, it's quite vague. Like where does the header file go exactly?

**Comment by domesticmouse** [comment]
Is this still an issue?

**Comment by domesticmouse** [comment]
I'm changing this to "Create a best path process for using Google Maps iOS Utils with Swift" documentation, as that seems to be the issue here.

Please correct me if I am wrong. Thanks!

**Comment by juniorgarcia** [comment]
I "can" configure my project, although when I will make my `ViewController.swift` implements `GMUClusterManagerDelegate` my Xcode crashes instantly. I even created the class [as the docs say](https://developers.google.com/maps/documentation/ios-sdk/utility/marker-clustering#adicionar-um-clusterer-de-marcadores-simples), but can't go further. Tried to configure it manually and with CocoaPods, both give me the same crash.

**Comment by domesticmouse** [comment]
Crashing Xcode seems to be a rite of passage for iOS developers. It looks like Apple have rewritten their Swift parser in Xcode using Swift in Xcode 9, so hopefully this will cease to be an issue sooner rather than later.

**Comment by rajeejones** [comment]
The instructions aren't clear:

> Add a bridging header file with #import "GMUMarkerClustering.h" (note the relative path).
What does it mean releative path?
There is no "GMUMarkerClustering.h" in the entire repo, or am I missing something?

> Open the umbrella header GMUMarkerClustering.h (under the Google-Maps-iOS-Utils/Cluster group) and change all the import paths to relative. 

Again, I cant find this file

**Comment by rajeejones** [comment]
Solution:

1. Create a Swift Bridging Header

> File > New > File > Header File

2. Name it how you want. Usually **[Project Name]-Bridging-Header.h**

3. Make sure your target can read the file path
> Target > Build Settings > Swift Compiler - General > Objective-C Bridging Header

_(If you put the bridging header in the root of your project, then just put the file name. Otherwise put the path to the file. EX: **"[Project Name]/Resources/[Project Name]-Bridging-Header.h"** )_

4. Change the path of the imports to relative paths. (Meaning, they are not under "Google-Maps-iOS-Utils/Cluster")
```objective-c
#import "GMUMarkerClustering.h"
#import "GMUGeoJSONParser.h"
#import "GMUKMLParser.h"
#import "GMUGeometryRenderer.h"
```

5. Change the imports to relative in "GMUMarkerClustering.h" as well
```objective-c
#import "GMUCluster.h"
#import "GMUClusterItem.h"
#import "GMUClusterManager.h"
#import "GMUDefaultClusterIconGenerator.h"
#import "GMUDefaultClusterRenderer.h"
#import "GMUGridBasedClusterAlgorithm.h"
#import "GMUNonHierarchicalDistanceBasedAlgorithm.h"
#import "GMUStaticCluster.h"

#import "GQTPointQuadTree.h"
```

6. Clean/ Build

7. To use the file in your view controller, there is no need to import anything, it should just work.

Ex: (From : https://developers.google.com/maps/documentation/ios-sdk/utility/kml-geojson)

```swift
let path = Bundle.main.path(forResource: "GeoJSON_sample", ofType: "json")
let url = URL(fileURLWithPath: path!)
geoJsonParser = GMUGeoJSONParser(url: url)
geoJsonParser.parse()

renderer = GMUGeometryRenderer(map: mapView, geometries: geoJsonParser.features)

renderer.render()
```

**Comment by rodmaz** [comment]
This is still an ongoing issue as far as I can tell. We have a  framework, which uses other libraries.
This is fully supported by Apple through private modules. 

So we created a private module w/ all the headers making up this module:

    module GoogleMapsUtils {
      header "../../Vendor/google-maps-ios-utils/src/Clustering/GMUCluster.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/GMUStaticCluster.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/GMUClusterItem.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/GMUClusterManager.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/View/GMUDefaultClusterIconGenerator.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/View/GMUDefaultClusterRenderer.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/Algo/GMUGridBasedClusterAlgorithm.h"
      header "../../Vendor/google-maps-ios-utils/src/Clustering/Algo/GMUNonHierarchicalDistanceBasedAlgorithm.h"
      header "../../Vendor/google-maps-ios-utils/src/QuadTree/GQTPointQuadTree.h"
      export *
    }
    
We can use all classes in Swift as expected HOWEVER when a `UIViewController` implements `GMUClusterManagerDelegate`, hell breaks loose. (Very similar to the issues above).
There is something fishy how the delegate is implemented that breaks the module.

**Comment by Prathapreddy26** [comment]
I am done with the clustering. but the cluster count is not showing for me. Any help will be appreciable.
