### ISSUE TITLE
 _items collection in the clusterManager

### ISSUE THREAD

**Issue by SAPIENTechnologies** [googlemaps/google-maps-ios-utils#87]
Is there any chance that we can get access to the markers collection in the clusterManager in iOS? It seems to be available on Android.

**Comment by jhanzo** [comment]
Up @google-admin

**Comment by mountainvat** [comment]
The way we manage markers on the iOS library is different to the Android for performance reasons. Not all clusters or cluster items will have a marker associated unless they are visible on screen. What you can do is to register to willRenderMarker or didRenderMarker event on the GMUDefaultClusterRenderer to manage them. Unfortunate we don't have the corresponding willRemoveMarker/didRemoveMarker events so you may have to check that their map property is not nil to see if they are active (or else remove them from the collection).

**Comment by ahsanmisbah** [comment]
I searched so many sites how to get allItems when tapping on didTapCluster, actually i want to open list in a tableview when tap on cluster instead of it will divided in more clusters. Please help me out.

**Comment by domesticmouse** [comment]
@ahsanmisbah This is an issue tracker, not a Q&A site. I'd suggest you ask your programming questions on StackOverflow. Thanks!
