### ISSUE TITLE
Camera jumps to marker and when starts animation when tapping on markers

### ISSUE THREAD

**Issue by gytiskv** [googlemaps/google-maps-ios-utils#89]
I've a strange issue with tapping on markers and animating to them. The strangest thing is that it happens not every single time.

I'm using didTapMarker and markerInfoWindow functions to show marker's details or animate to it if needed.

The thing is, when tapping on marker, camera jumps to that marker position immediately and then jumps back to current position and animates to the marker.

```
func mapView(_ mapView: GMSMapView, didTap marker: GMSMarker) -> Bool {
        
        let item = marker.userData as! Marker
        
        let childs = self.childMarkers.filter { (obj) -> Bool in
            return obj.getParentId() == item.getId()
        }
        
        if childs.count > 0 {
            if self.tappedMarkersChilds[item.getId()] == nil && self.tappedMarkersLines[item.getId()] == nil {
                print("Adding childs")
                self.addChilds(forParent: item, childs: childs)
                return true
            } else {
                print("Removing childs")
                self.removeChilds(forParent: item)
                return true
            }
        } else {
            CATransaction.begin()
            CATransaction.setValue(ConstantValues.animationDuration, forKey: kCATransactionAnimationDuration)
            mapView.animate(toLocation: marker.position)
            CATransaction.commit()
            return false
        }
        
    }

```
And other functions just returns infoWindow and has no animation logic.

**Comment by mountainvat** [comment]
Should this be raised against the SDK issue tracker? https://code.google.com/p/gmaps-api-issues/issues/list?q=label:ApiType-IosSDK

**Comment by domesticmouse** [comment]
This doesn't appear to be an issue with the support library. Please see our [Google Maps SDK for iOS Support page](https://developers.google.com/maps/documentation/ios-sdk/support) for avenues of support. Thanks!
