### ISSUE TITLE
The Google map delegate broken

### ISSUE THREAD

**Issue by saviormike** [googlemaps/google-maps-ios-utils#9]
It seems like that when I implement the cluster function on my map, the idleAtCemeraPosition is not being called. It sounds like somewhere is holding the map from idle.

**Comment by domesticmouse** [comment]
Can you report this issue on the [Google Maps SDK for iOS bug tracker](https://code.google.com/p/gmaps-api-issues/issues/entry?template=Maps%20SDK%20for%20iOS%20-%20Bug) along with a reproduction sample, along the lines of my [MovingMarkerPosition](https://github.com/domesticmouse/MovingMarkerPosition) sample?
