### ISSUE TITLE
Super slow performance of GMUNonHierarchicalDistanceBasedAlgorithm with large data sets

### ISSUE THREAD

**Issue by SAPIENTechnologies** [googlemaps/google-maps-ios-utils#90]
I have a data set of about 750 points. When i use the GMUNonHierarchicalDistanceBasedAlgorithm, it takes about 10 seconds to render the clusters on an iPhone 6S. I have tracked the slowness to the clustering. When I change to the GMUGridBasedClusterAlgorithm, it only takes about 1/2 second. Anyone else see these issues?

**Comment by mountainvat** [comment]
That's interesting. Our sample demo can work on 10k points. The GMUNonHierarchicalDistanceBasedAlgorithm has a O(N*log(N)) complexity so 750 should not be a problem.

I'd be interested to see a repro case if possible.

**Comment by SAPIENTechnologies** [comment]
If I were to put together  a stripped down project, would I be able to send it to you somehow for you to take a look at?

**Comment by mountainvat** [comment]
Yeah sounds good to me. Thanks.

**Comment by SAPIENTechnologies** [comment]
Unknown to me why, this has started performing at orders of magnitude better. It still has a lag of a second or two when displaying 750+ items in clusters, but that is much better than 8-10 seconds. 

I will keep an eye on thins and see what happens

**Comment by domesticmouse** [comment]
Closing this out for now. Please re-open with a link to a minimised repro case if you'd like us to dive into this issue further.
