### ISSUE TITLE
Marker pop/drop animation

### ISSUE THREAD

**Issue by Shahriyar495** [googlemaps/google-maps-ios-utils#92]
Hi Team, 

I want GMSMarker appear animation. But currently this code animates markers.
```
if (animated) {
    [CATransaction begin];
    [CATransaction setAnimationDuration:kGMUAnimationDuration];
    marker.layer.latitude = position.latitude;
    marker.layer.longitude = position.longitude;
    [CATransaction commit];
  }
```
and this doesn't have any effect 
`marker.appearAnimation = kGMSMarkerAnimationPop;`

Markers should appear popping when above animation is finished. How can i do this?

Thanks in advance

**Comment by AmmySingh** [comment]
Can I use this code in for loop to drop multiple pins? I tried but it's not working.

Thanks in advance

**Comment by domesticmouse** [comment]
This feels like an issue with Google Maps SDK for iOS, not for the support library. Please see our [support page](https://developers.google.com/maps/documentation/ios-sdk/support) for options on getting support for Google Maps SDK for iOS. Thanks!

**Comment by dstharding** [comment]
Try GMSMarkerAnimation.pop
