### ISSUE TITLE
dropping support for ios7 soon?

### ISSUE THREAD

**Issue by dvertovsek** [googlemaps/google-maps-ios-utils#93]
any news on dropping support for ios7 and making it a dynamic framework?

**Comment by dvertovsek** [comment]
@mountainvat ?

**Comment by mountainvat** [comment]
I think Google Maps SDK is dropping iOS 7 very soon but I am not sure of a timeline for making it into a dynamic framework yet.

**Comment by domesticmouse** [comment]
Please see [Google Maps SDK for iOS 2.3 release notes](https://developers.google.com/maps/documentation/ios-sdk/releases#version_23_-_may_30_2017) for more detail on iOS7 deprecation. Please feel free to raise an issue on the [Google Maps SDK for iOS issue tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker) for dynamic framework support. Thanks!
