### ISSUE TITLE
minClusterSize in DefaultRenderer

### ISSUE THREAD

**Issue by MohsenK** [googlemaps/google-maps-ios-utils#94]
In Android SDK there is minClusterSize property that  when we set it to 1 it show's every elements as cluster not marker.
But in iOS SDK doesn't exist minClusterSize and DefaultRenderer by default show's lower than 3 items as items not cluster.
There is any solution  ?
Thanks.

**Comment by domesticmouse** [comment]
We gladly accept Pull Requests for additional functionality.

**Comment by mountainvat** [comment]
You can extend GMUDefaultClusterRenderer and override `- (BOOL)shouldRenderAsCluster:(id<GMUCluster>)cluster atZoom:(float)zoom;`
