### ISSUE TITLE
guard / do not call [func render(renderer: _ , willRenderMarker: _ )] if nothing changed on the map.

### ISSUE THREAD

**Issue by grundmanise** [googlemaps/google-maps-ios-utils#96]
`func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) { }`

get's called every time there was a zoom level change even if no clustering / declustering happened.
Thus in this scenario:

```
func renderer(_ renderer: GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
      
      // Check if marker or cluster
      if marker.userData is PlaceMarker {

          if let userData = marker.userData as? PlaceMarker {
             // Apply custom view for cluster
             marker.iconView = MarkerView(caption: userData.caption)
          }

          marker.groundAnchor = CGPoint(x: 0.5, y: 1)
          marker.isFlat = true
          marker.appearAnimation = kGMSMarkerAnimationPop

      } else {
          // Apply custom view for cluster
          marker.iconView = ClusterViewIcon()
          
          // Show clusters above markers
          marker.zIndex = 1000;
          marker.groundAnchor = CGPoint(x: 0.5, y: 1)
          marker.isFlat = true
          marker.appearAnimation = kGMSMarkerAnimationPop
      }
  }
```

**we recreate already rendered markers and waste resources.**

This `func renderer()` should only be called if the clustering / declustering actually happened or there should be an option to `guard` if a particular marker was already setted up before and nothing changed.

Reference: https://github.com/googlemaps/google-maps-ios-utils/issues/21#issuecomment-298355409

**Comment by domesticmouse** [comment]
I'm unsure what change you are suggesting. Can you put together a PR that sketches out what you are envisioning?

**Comment by miragessee** [comment]
implementation GMUClusterRendererDelegate

renderer.delegate = self
