### ISSUE TITLE
could not Build module 'googlemaps'

### ISSUE THREAD

**Issue by AmeerChand** [googlemaps/google-maps-ios-utils#97]
![screen shot 2017-05-02 at 12 09 48 pm](https://cloud.githubusercontent.com/assets/26761721/25607579/a250e5ac-2f30-11e7-9836-940f8b887ad4.png)

**Comment by mountainvat** [comment]
How did you setup your project? If you are using Pods then you would probably want to open the workspace instead of the project.

**Comment by AmeerChand** [comment]
i opened the project using workspace but facing same issue.

**Comment by AmeerChand** [comment]
when i use this  in podfile
pod 'GooglePlaces', '2.1'
  pod 'GoogleMaps', '2.1'
  pod 'GooglePlacePicker', '2.1'
then it's working fine.

**Comment by domesticmouse** [comment]
Please create a GitHub repository with a minimal reproduction case. The above is not sufficient to understand what is going wrong for you. Thanks!

**Comment by AmeerChand** [comment]
off course we are opening workspace.
