### ISSUE TITLE
apply clustering to all markers except one marker

### ISSUE THREAD

**Issue by yassinelmalyh** [googlemaps/google-maps-ios-utils#98]
Hello,

i want all markers to be clustered except one marker, how can i do this please ?

thanks in advance.

**Comment by mountainvat** [comment]
Maybe you can do it by NOT adding the one marker to the ClusterManager? And just add it as a normal marker on the map?

**Comment by domesticmouse** [comment]
Please re-open this bug if you need more assistance. Thanks!
